#!/usr/bin/env python3
# This MobilityDB code is provided under The PostgreSQL License.
# Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
# contributors
"""Generate the time zone database compiled into standalone MEOS.

pgtypes/timezone/data/tzdata.zi is the IANA time zone source PostgreSQL ships
in src/timezone/data/tzdata.zi. This script compiles it with zic in the format
PostgreSQL's own zic writes by default (-b slim) and emits
pgtypes/timezone/data/tzdata_embedded.inc: one byte array holding every
distinct compiled zone, and an index of zone names sorted case-insensitively,
each naming the bytes of its zone. Names that are links to another zone share
that zone's bytes.

Run it after replacing tzdata.zi with the file of a newer PostgreSQL release:

    python3 tools/tzdata/generate_tzdata.py

It needs a zic on the PATH (or --zic).
"""

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
DATA = os.path.join(ROOT, "pgtypes", "timezone", "data")


def compile_zones(zic, source, outdir):
    subprocess.run([zic, "-b", "slim", "-d", outdir, source], check=True)
    zones = {}
    for dirpath, _dirnames, filenames in os.walk(outdir):
        for filename in filenames:
            path = os.path.join(dirpath, filename)
            name = os.path.relpath(path, outdir).replace(os.sep, "/")
            with open(path, "rb") as f:
                zones[name] = f.read()
    return zones


def source_version(source):
    with open(source, encoding="utf-8") as f:
        first = f.readline().strip()
    prefix = "# version "
    if not first.startswith(prefix):
        sys.exit(f"{source}: first line does not state the tzdata version")
    return first[len(prefix):]


def write_inc(zones, version, out):
    blob = bytearray()
    offsets = {}
    index = []
    # Assign bytes in name order so the output depends on the data alone.
    for name in sorted(zones, key=lambda n: (n.lower(), n)):
        data = zones[name]
        if not data.startswith(b"TZif"):
            sys.exit(f"{name}: zic did not write a TZif file")
        digest = hashlib.sha256(data).digest()
        if digest not in offsets:
            offsets[digest] = len(blob)
            blob += data
        index.append((name, offsets[digest], len(data)))

    lowered = [n.lower() for n, _, _ in index]
    if len(set(lowered)) != len(lowered):
        sys.exit("two zone names differ only in case")

    with open(out, "w", encoding="ascii", newline="\n") as f:
        f.write("/* Generated by tools/tzdata/generate_tzdata.py from\n")
        f.write(" * pgtypes/timezone/data/tzdata.zi (tzdata %s), compiled with\n" % version)
        f.write(" * zic -b slim. Do not edit. */\n\n")
        f.write('#define TZDATA_EMBEDDED_VERSION "%s"\n\n' % version)
        f.write("static const unsigned char tzdata_blob[%d] = {\n" % len(blob))
        for i in range(0, len(blob), 16):
            chunk = blob[i:i + 16]
            f.write("  " + ", ".join("0x%02x" % b for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write("static const TzdataEntry tzdata_entries[%d] = {\n" % len(index))
        for name, offset, size in index:
            f.write('  {"%s", %d, %d},\n' % (name, offset, size))
        f.write("};\n")
    return len(index), len(blob)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--zic", default="zic", help="zic executable")
    parser.add_argument("--source", default=os.path.join(DATA, "tzdata.zi"))
    parser.add_argument("--out", default=os.path.join(DATA, "tzdata_embedded.inc"))
    args = parser.parse_args()

    version = source_version(args.source)
    with tempfile.TemporaryDirectory() as outdir:
        zones = compile_zones(args.zic, args.source, outdir)
    count, size = write_inc(zones, version, args.out)
    print(f"{args.out}: tzdata {version}, {count} zone names, {size} bytes")


if __name__ == "__main__":
    main()
