#!/usr/bin/env python3
# This MobilityDB code is provided under The PostgreSQL License.
# Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
# contributors
"""Generate the time zone database compiled into standalone MEOS.

pgtypes/timezone/data/tzdata.zi is the IANA time zone source PostgreSQL ships
in src/timezone/data/tzdata.zi. This script compiles it with zic in the format
PostgreSQL's own zic writes by default (-b slim) and emits
pgtypes/timezone/data/tzdata_embedded.inc: one byte array holding every
distinct compiled zone, and an index of zone names sorted case-insensitively,
each naming the bytes of its zone. Names that are links to another zone share
that zone's bytes.

pgtypes/timezone/data/tznames/Default is the set of time zone abbreviations
PostgreSQL ships in src/timezone/tznames/Default. The script reads it as
PostgreSQL's tzparser.c does and emits pgtypes/timezone/data/tznames_default.inc,
its entries in the order PostgreSQL sorts them.

Run it after replacing tzdata.zi and tznames/Default with the files of a newer
PostgreSQL release:

    python3 tools/tzdata/generate_tzdata.py

It needs a zic on the PATH (or --zic).
"""

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
DATA = os.path.join(ROOT, "pgtypes", "timezone", "data")


def compile_zones(zic, source, outdir):
    subprocess.run([zic, "-b", "slim", "-d", outdir, source], check=True)
    zones = {}
    for dirpath, _dirnames, filenames in os.walk(outdir):
        for filename in filenames:
            path = os.path.join(dirpath, filename)
            name = os.path.relpath(path, outdir).replace(os.sep, "/")
            with open(path, "rb") as f:
                zones[name] = f.read()
    return zones


def source_version(source):
    with open(source, encoding="utf-8") as f:
        first = f.readline().strip()
    prefix = "# version "
    if not first.startswith(prefix):
        sys.exit(f"{source}: first line does not state the tzdata version")
    return first[len(prefix):]


def write_inc(zones, version, out):
    blob = bytearray()
    offsets = {}
    index = []
    # Assign bytes in name order so the output depends on the data alone.
    for name in sorted(zones, key=lambda n: (n.lower(), n)):
        data = zones[name]
        if not data.startswith(b"TZif"):
            sys.exit(f"{name}: zic did not write a TZif file")
        digest = hashlib.sha256(data).digest()
        if digest not in offsets:
            offsets[digest] = len(blob)
            blob += data
        index.append((name, offsets[digest], len(data)))

    lowered = [n.lower() for n, _, _ in index]
    if len(set(lowered)) != len(lowered):
        sys.exit("two zone names differ only in case")

    with open(out, "w", encoding="ascii", newline="\n") as f:
        f.write("/* Generated by tools/tzdata/generate_tzdata.py from\n")
        f.write(" * pgtypes/timezone/data/tzdata.zi (tzdata %s), compiled with\n" % version)
        f.write(" * zic -b slim. Do not edit. */\n\n")
        f.write('#define TZDATA_EMBEDDED_VERSION "%s"\n\n' % version)
        f.write("static const unsigned char tzdata_blob[%d] = {\n" % len(blob))
        for i in range(0, len(blob), 16):
            chunk = blob[i:i + 16]
            f.write("  " + ", ".join("0x%02x" % b for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write("static const TzdataEntry tzdata_entries[%d] = {\n" % len(index))
        for name, offset, size in index:
            f.write('  {"%s", %d, %d},\n' % (name, offset, size))
        f.write("};\n")
    return len(index), len(blob)


# The limits tzparser.c's validateTzEntry enforces
TOKMAXLEN = 10
MAX_OFFSET = 14 * 3600


def read_tznames(source, zones):
    """Read an abbreviation file as tzparser.c's splitTzLine and addToArray do"""
    entries = {}
    with open(source, encoding="utf-8") as f:
        for lineno, line in enumerate(f, 1):
            fields = line.split("#", 1)[0].split()
            if not fields:
                continue
            where = f"{source}, line {lineno}"
            if fields[0].startswith("@"):
                sys.exit(f"{where}: {fields[0]} is not supported")
            if len(fields) < 2:
                sys.exit(f"{where}: missing time zone offset")
            abbrev = fields[0].lower()
            if len(abbrev) > TOKMAXLEN:
                sys.exit(f"{where}: {abbrev} is longer than {TOKMAXLEN}")
            if fields[1][0].isdigit() or fields[1][0] in "+-":
                offset = int(fields[1])
                if abs(offset) > MAX_OFFSET:
                    sys.exit(f"{where}: offset {offset} is out of range")
                is_dst = len(fields) > 2 and fields[2].upper() == "D"
                rest = fields[3:] if is_dst else fields[2:]
                entry = (None, offset, is_dst)
            else:
                if fields[1] not in zones:
                    sys.exit(f"{where}: {fields[1]} is not a zone of tzdata.zi")
                rest = fields[2:]
                entry = (fields[1], 0, False)
            if rest:
                sys.exit(f"{where}: invalid syntax")
            if entries.get(abbrev, entry) != entry:
                sys.exit(f"{where}: {abbrev} conflicts with an earlier entry")
            entries[abbrev] = entry
    # tzparser.c sorts by strcmp, which the byte order of ASCII reproduces
    return sorted(entries.items(), key=lambda item: item[0].encode("ascii"))


def write_tznames_inc(entries, source, out):
    with open(out, "w", encoding="ascii", newline="\n") as f:
        f.write("/* Generated by tools/tzdata/generate_tzdata.py from\n")
        f.write(" * pgtypes/timezone/data/tznames/%s. Do not edit. */\n\n"
            % os.path.basename(source))
        f.write("static tzEntry tznames_default[%d] = {\n" % len(entries))
        for abbrev, (zone, offset, is_dst) in entries:
            if zone:
                f.write('  {.abbrev = "%s", .zone = "%s"},\n' % (abbrev, zone))
            elif is_dst:
                f.write('  {.abbrev = "%s", .offset = %d, .is_dst = true},\n'
                    % (abbrev, offset))
            else:
                f.write('  {.abbrev = "%s", .offset = %d},\n' % (abbrev, offset))
        f.write("};\n")
    return len(entries)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--zic", default="zic", help="zic executable")
    parser.add_argument("--source", default=os.path.join(DATA, "tzdata.zi"))
    parser.add_argument("--out", default=os.path.join(DATA, "tzdata_embedded.inc"))
    parser.add_argument("--tznames",
        default=os.path.join(DATA, "tznames", "Default"))
    parser.add_argument("--tznames-out",
        default=os.path.join(DATA, "tznames_default.inc"))
    args = parser.parse_args()

    version = source_version(args.source)
    with tempfile.TemporaryDirectory() as outdir:
        zones = compile_zones(args.zic, args.source, outdir)
    count, size = write_inc(zones, version, args.out)
    print(f"{args.out}: tzdata {version}, {count} zone names, {size} bytes")
    entries = read_tznames(args.tznames, zones)
    count = write_tznames_inc(entries, args.tznames, args.tznames_out)
    print(f"{args.tznames_out}: {count} abbreviations")


if __name__ == "__main__":
    main()
