/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Universite libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2025, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief Set-set spatial-join functions for temporal points.
 *
 * GENERATED by tools/setset_join/generate.py -- DO NOT EDIT.
 * Each function is a thin wrapper over a type-generic C kernel; the surface
 * mirrors the type coverage of the scalar spatial relationships.
 */

CREATE FUNCTION minDistance(tgeompoint[], tgeompoint[])
  RETURNS float
  AS 'MODULE_PATHNAME', 'Mindistance_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION minDistance(tgeogpoint[], tgeogpoint[])
  RETURNS float
  AS 'MODULE_PATHNAME', 'Mindistance_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION minDistance(tgeompoint, geometry)
  RETURNS float
  AS 'MODULE_PATHNAME', 'NAD_tgeo_geo'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION minDistance(geometry, tgeompoint)
  RETURNS float
  AS 'MODULE_PATHNAME', 'NAD_geo_tgeo'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION minDistance(tgeogpoint, geography)
  RETURNS float
  AS 'MODULE_PATHNAME', 'NAD_tgeo_geo'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION minDistance(geography, tgeogpoint)
  RETURNS float
  AS 'MODULE_PATHNAME', 'NAD_geo_tgeo'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION minDistance_transfn(float, tgeompoint, tgeompoint)
  RETURNS float
  AS 'MODULE_PATHNAME', 'Mindistance_transfn'
  LANGUAGE C IMMUTABLE PARALLEL SAFE;
CREATE AGGREGATE minDistance(tgeompoint, tgeompoint) (
  SFUNC = minDistance_transfn,
  STYPE = float,
  COMBINEFUNC = float8smaller,
  PARALLEL = SAFE
);

CREATE FUNCTION minDistance_transfn(float, tgeogpoint, tgeogpoint)
  RETURNS float
  AS 'MODULE_PATHNAME', 'Mindistance_transfn'
  LANGUAGE C IMMUTABLE PARALLEL SAFE;
CREATE AGGREGATE minDistance(tgeogpoint, tgeogpoint) (
  SFUNC = minDistance_transfn,
  STYPE = float,
  COMBINEFUNC = float8smaller,
  PARALLEL = SAFE
);

CREATE FUNCTION eDwithinPairs(tgeompoint[], tgeompoint[], dist float,
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Edwithin_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION aDwithinPairs(tgeompoint[], tgeompoint[], dist float,
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Adwithin_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION eIntersectsPairs(tgeompoint[], tgeompoint[],
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Eintersects_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION aIntersectsPairs(tgeompoint[], tgeompoint[],
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Aintersects_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION eDisjointPairs(tgeompoint[], tgeompoint[],
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Edisjoint_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION aDisjointPairs(tgeompoint[], tgeompoint[],
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Adisjoint_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION eDwithinPairs(tgeogpoint[], tgeogpoint[], dist float,
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Edwithin_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION aDwithinPairs(tgeogpoint[], tgeogpoint[], dist float,
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Adwithin_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION eIntersectsPairs(tgeogpoint[], tgeogpoint[],
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Eintersects_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION aIntersectsPairs(tgeogpoint[], tgeogpoint[],
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Aintersects_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION eDisjointPairs(tgeogpoint[], tgeogpoint[],
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Edisjoint_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION aDisjointPairs(tgeogpoint[], tgeogpoint[],
    OUT i integer, OUT j integer)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Adisjoint_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION tDwithinPairs(tgeompoint[], tgeompoint[], dist float,
    OUT i integer, OUT j integer, OUT periods tstzspanset)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Tdwithin_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION tIntersectsPairs(tgeompoint[], tgeompoint[],
    OUT i integer, OUT j integer, OUT periods tstzspanset)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Tintersects_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION tDisjointPairs(tgeompoint[], tgeompoint[],
    OUT i integer, OUT j integer, OUT periods tstzspanset)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Tdisjoint_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION tIntersectsPairs(tgeogpoint[], tgeogpoint[],
    OUT i integer, OUT j integer, OUT periods tstzspanset)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Tintersects_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION tDisjointPairs(tgeogpoint[], tgeogpoint[],
    OUT i integer, OUT j integer, OUT periods tstzspanset)
  RETURNS setof record
  AS 'MODULE_PATHNAME', 'Tdisjoint_tgeoarr_tgeoarr'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
