/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/* GENERATED by tools/codegen/inherited/generate.py from templates/spatialrels.sql.tmpl — DO NOT EDIT BY HAND;
 * edit the template + tools/codegen/inherited/manifest.d and re-run. */

/**
 * @file
 * @brief Ever/always spatial relationships for temporal S2 cells
 * @details A `ts2cell` value holds one cell per instant, and a relationship is
 * that of the cell's boundary rather than of its centre. The cell is a region
 * of the sphere bounded by great-circle arcs, so each function converts its
 * operand through `cellToBoundary(ts2cell)`, a temporal geography, and
 * delegates to the ever/always spatial relationship of the temporal geography
 * with a geography, answered on the sphere. The functions are those a temporal
 * geography declares; the boundary is in SRID 4326.
 */

/*****************************************************************************
 * Ever/always disjoint
 *****************************************************************************/

CREATE FUNCTION eDisjoint(geography, ts2cell)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint($1, @extschema@.cellToBoundary($2)) $$;
CREATE FUNCTION aDisjoint(geography, ts2cell)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint($1, @extschema@.cellToBoundary($2)) $$;

CREATE FUNCTION eDisjoint(ts2cell, geography)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint(@extschema@.cellToBoundary($1), $2) $$;
CREATE FUNCTION aDisjoint(ts2cell, geography)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint(@extschema@.cellToBoundary($1), $2) $$;

CREATE FUNCTION eDisjoint(ts2cell, ts2cell)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint(@extschema@.cellToBoundary($1),
                          @extschema@.cellToBoundary($2)) $$;
CREATE FUNCTION aDisjoint(ts2cell, ts2cell)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint(@extschema@.cellToBoundary($1),
                          @extschema@.cellToBoundary($2)) $$;

/*****************************************************************************
 * Ever/always intersects
 *****************************************************************************/

CREATE FUNCTION eIntersects(geography, ts2cell)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects($1, @extschema@.cellToBoundary($2)) $$;
CREATE FUNCTION aIntersects(geography, ts2cell)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects($1, @extschema@.cellToBoundary($2)) $$;

CREATE FUNCTION eIntersects(ts2cell, geography)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects(@extschema@.cellToBoundary($1), $2) $$;
CREATE FUNCTION aIntersects(ts2cell, geography)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects(@extschema@.cellToBoundary($1), $2) $$;

CREATE FUNCTION eIntersects(ts2cell, ts2cell)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects(@extschema@.cellToBoundary($1),
                            @extschema@.cellToBoundary($2)) $$;
CREATE FUNCTION aIntersects(ts2cell, ts2cell)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects(@extschema@.cellToBoundary($1),
                            @extschema@.cellToBoundary($2)) $$;

/*****************************************************************************
 * Ever/always dwithin
 *****************************************************************************/

CREATE FUNCTION eDwithin(geography, ts2cell, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin($1, @extschema@.cellToBoundary($2), $3) $$;

CREATE FUNCTION eDwithin(ts2cell, geography, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin(@extschema@.cellToBoundary($1), $2, $3) $$;

CREATE FUNCTION eDwithin(ts2cell, ts2cell, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin(@extschema@.cellToBoundary($1),
                         @extschema@.cellToBoundary($2), $3) $$;
CREATE FUNCTION aDwithin(ts2cell, ts2cell, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin(@extschema@.cellToBoundary($1),
                         @extschema@.cellToBoundary($2), $3) $$;

/*****************************************************************************/
