---
engines:
  cppcheck:
    language: c
    exclude_paths:
      - "postgis/**"
      - "postgresql/**"
  duplication:
    exclude_paths:
      - "postgis/**"
      - "postgresql/**"
    config:
      languages:
        - "c"
exclude_paths:
  - "postgis/**"
  - "postgresql/**"
