---
engines:
  cppcheck:
    language: c
    exclude_paths:
      - "postgis/**"
      - "postgres/**"
  duplication:
    exclude_paths:
      - "postgis/**"
      - "postgres/**"
    config:
      languages:
        - "c"
exclude_paths:
  - "postgis/**"
  - "postgres/**"
