/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/* GENERATED by tools/codegen/inherited/generate.py from templates/compops.sql.tmpl — DO NOT EDIT BY HAND;
 * edit the template + tools/codegen/inherited/manifest.d and re-run. */

/**
 * @file
 * @brief Ever/always and temporal comparison functions and operators for
 * temporal poses
 */

/*****************************************************************************
 * Ever/Always Comparison Functions
 *****************************************************************************/

CREATE FUNCTION eEqual(pose, tpose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_eq_pose_tpose'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?= (
  LEFTARG = pose, RIGHTARG = tpose,
  PROCEDURE = eEqual,
  NEGATOR = %<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aEqual(pose, tpose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_eq_pose_tpose'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %= (
  LEFTARG = pose, RIGHTARG = tpose,
  PROCEDURE = aEqual,
  NEGATOR = ?<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION eNotEqual(pose, tpose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_ne_pose_tpose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?<> (
  LEFTARG = pose, RIGHTARG = tpose,
  PROCEDURE = eNotEqual,
  NEGATOR = %=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aNotEqual(pose, tpose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_ne_pose_tpose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %<> (
  LEFTARG = pose, RIGHTARG = tpose,
  PROCEDURE = aNotEqual,
  NEGATOR = ?=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

/*****************************************************************************/

CREATE FUNCTION eEqual(tpose, pose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_eq_tpose_pose'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?= (
  LEFTARG = tpose, RIGHTARG = pose,
  PROCEDURE = eEqual,
  NEGATOR = %<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aEqual(tpose, pose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_eq_tpose_pose'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %= (
  LEFTARG = tpose, RIGHTARG = pose,
  PROCEDURE = aEqual,
  NEGATOR = ?<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION eNotEqual(tpose, pose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_ne_tpose_pose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?<> (
  LEFTARG = tpose, RIGHTARG = pose,
  PROCEDURE = eNotEqual,
  NEGATOR = %=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aNotEqual(tpose, pose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_ne_tpose_pose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %<> (
  LEFTARG = tpose, RIGHTARG = pose,
  PROCEDURE = aNotEqual,
  NEGATOR = ?=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

/*****************************************************************************/

CREATE FUNCTION eEqual(tpose, tpose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_eq_tpose_tpose'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?= (
  LEFTARG = tpose, RIGHTARG = tpose,
  PROCEDURE = eEqual,
  NEGATOR = %<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aEqual(tpose, tpose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_eq_tpose_tpose'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %= (
  LEFTARG = tpose, RIGHTARG = tpose,
  PROCEDURE = aEqual,
  NEGATOR = ?<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION eNotEqual(tpose, tpose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_ne_tpose_tpose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?<> (
  LEFTARG = tpose, RIGHTARG = tpose,
  PROCEDURE = eNotEqual,
  NEGATOR = %=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aNotEqual(tpose, tpose)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_ne_tpose_tpose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %<> (
  LEFTARG = tpose, RIGHTARG = tpose,
  PROCEDURE = aNotEqual,
  NEGATOR = ?=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

/*****************************************************************************
 * Temporal equal
 *****************************************************************************/

CREATE FUNCTION tEqual(pose, tpose)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Teq_pose_tpose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tEqual(tpose, pose)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Teq_tpose_pose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tEqual(tpose, tpose)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Teq_temporal_temporal'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR #= (
  PROCEDURE = tEqual,
  LEFTARG = pose, RIGHTARG = tpose,
  COMMUTATOR = #=
);
CREATE OPERATOR #= (
  PROCEDURE = tEqual,
  LEFTARG = tpose, RIGHTARG = pose,
  COMMUTATOR = #=
);
CREATE OPERATOR #= (
  PROCEDURE = tEqual,
  LEFTARG = tpose, RIGHTARG = tpose,
  COMMUTATOR = #=
);

/*****************************************************************************
 * Temporal not equal
 *****************************************************************************/

CREATE FUNCTION tNotEqual(pose, tpose)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Tne_pose_tpose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tNotEqual(tpose, pose)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Tne_tpose_pose'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tNotEqual(tpose, tpose)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Tne_temporal_temporal'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR #<> (
  PROCEDURE = tNotEqual,
  LEFTARG = pose, RIGHTARG = tpose,
  COMMUTATOR = #<>
);
CREATE OPERATOR #<> (
  PROCEDURE = tNotEqual,
  LEFTARG = tpose, RIGHTARG = pose,
  COMMUTATOR = #<>
);
CREATE OPERATOR #<> (
  PROCEDURE = tNotEqual,
  LEFTARG = tpose, RIGHTARG = tpose,
  COMMUTATOR = #<>
);
/*****************************************************************************/
