/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2022, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2022, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS. 
 *
 *****************************************************************************/

/**
 * @brief A simple program that reads from a CSV file synthetic trip data in
 * Brussels generated by the MobilityDB-BerlinMOD generator 
 * https://github.com/MobilityDB/MobilityDB-BerlinMOD
 * and generate statics about the Brussels communes (or municipalities)
 * traversed the trips.
 *
 * The input files are
 * - `communes.csv`: data from the 19 communes composing Brussels obtained from
 *   OSM and publicly available statistical data
 * - `brussels_region.csv`: geometry of the Brussels region obtained from OSM.
 *   It is the spatial union of the 19 communes
 * - `trips.csv`: 64 trips from 5 cars during 4 days obtained from the
 *   generator at scale factor 0.005
 * In the above files, the coordinates are given in the 3857 coordinate system,
 * https://epsg.io/3857
 * and the timestamps are given in the Europe/Brussels time zone.
 * This simple program does not cope with erroneous inputs, such as missing
 * fields or invalid timestamp values.
 *
 * The program can be build as follows
 * @code
 * gcc -Wall -g -I. -o meos_read_berlinmod meos_read_berlinmod.c -L/usr/local/lib -lmeos
 * @endcode
 */

#include <stdio.h>
#include "meos.h"

#define MAX_LENGTH_NAME 50
#define MAX_VEHICLES 5
#define MAX_COMMUNES 19

typedef struct
{
  int id;
  char name[MAX_LENGTH_NAME];
  int population;
  GSERIALIZED *geom;
} commune_record;

typedef struct
{
  char name[MAX_LENGTH_NAME];
  GSERIALIZED *geom;
} region_record;

typedef struct
{
  int vehicle;
  DateADT day;
  int seq;
  Temporal *trip;
  GSERIALIZED *trajectory;
} trip_record;

/* Arrays to compute the results */
commune_record communes[19];
region_record brussels_region;
double length[MAX_VEHICLES + 2][MAX_COMMUNES + 2] = {0};

/* Maximum length in characters of a trip in the input data */
char trip_buffer[160000]; 
/* Maximum length in characters of a geometry in the input data */
char geo_buffer[100000]; 
/* Maximum length in characters of a date in the input data */
char date_buffer[12]; 

/* Read communes from file */
int read_communes(void)
{
  /* You may substitute the full file path in the first argument of fopen */
  FILE *file = fopen("communes.csv", "r");

  if (! file)
  {
    printf("Error opening file\n");
    return 1;
  }

  int read = 0;
  int records = 0;

  /* Read the first line of the file with the headers */
  fscanf(file, "%1024s\n", geo_buffer);

  /* Continue reading the file */
  do
  {
    // id, name, population, geom
    read = fscanf(file, "%d,%50[^,],%d,%100000[^\n]\n",
      &communes[records].id, communes[records].name,
      &communes[records].population, geo_buffer);
    /* Transform the string representing the geometry into a geometry value */
    communes[records++].geom = gserialized_in(geo_buffer, -1);

    if (read != 4 && !feof(file))
    {
      printf("Commune record with missing values\n");
      return 1;
    }

    if (ferror(file))
    {
      printf("Error reading file\n");
      return 1;
    }
  } while (!feof(file));

  printf("\n%d commune records read.", records);

  /* Close the file */
  fclose(file);

  return 0;
}

/* Read Brussels region from file */
int read_brussels_region(void)
{
  /* You may substitute the full file path in the first argument of fopen */
  FILE *file = fopen("brussels_region.csv", "r");

  if (! file)
  {
    printf("Error opening file\n");
    return 1;
  }

  int read = 0;

  /* Read the first line of the file with the headers */
  fscanf(file, "%1024s\n", geo_buffer);

  /* Continue reading the file */
  // id, geom
  read = fscanf(file, "%50[^,],%100000[^\n]\n",
    brussels_region.name, geo_buffer);
  /* Transform the string representing the geometry into a geometry value */
  brussels_region.geom = gserialized_in(geo_buffer, -1);

  if (read != 2 && !feof(file))
  {
    printf("Region record with missing values\n");
    return 1;
  }

  if (ferror(file))
  {
    printf("Error reading file\n");
    return 1;
  }

  printf("\nBrussels region record read.\n");

  /* Close the file */
  fclose(file);

  return 0;
}

/* Main program */
int main(void)
{
  /* Initialize MEOS */
  meos_initialize();

  /* Read communes file */
  read_communes();
  
  /* Read communes file */
  // read_brussels_region();
  
  /* You may substitute the full file path in the first argument of fopen */
  FILE *file = fopen("trips.csv", "r");

  if (! file)
  {
    printf("Error opening file\n");
    return 1;
  }

  trip_record trip_rec;
  int read = 0;
  int records = 0;

  /* Read the first line of the file with the headers */
  fscanf(file, "%1024s\n", geo_buffer);

  /* Continue reading the file */
  do
  {
    // vehicle,day,seq,trip,trajectory
    read = fscanf(file, "%d,%10[^,],%d,%160000[^,],%100000[^\n]\n",
      &trip_rec.vehicle, date_buffer, &trip_rec.seq, trip_buffer, geo_buffer);
    /* Transform the string representing the date into a date value */
    trip_rec.day = pg_date_in(date_buffer);
    /* Transform the string representing the trip into a temporal value */
    trip_rec.trip = temporal_from_hexwkb(trip_buffer);
    /* Transform the string representing the trajectory into a geometry value */
    trip_rec.trajectory = gserialized_in(geo_buffer, -1);

    if (read == 5)
      records++;

    if (read != 5 && !feof(file))
    {
      printf("Trip record with missing values\n");
      return 1;
    }

    if (ferror(file))
    {
      printf("Error reading file\n");
      return 1;
    }

    /* Compute the total length */
    length[trip_rec.vehicle - 1][0] = tpoint_length(trip_rec.trip) / 1000;
    /* Compute the length in each commune */
    for (int i = 0; i < 19; i ++)
    {
      Temporal *atgeom = tpoint_at_geometry(trip_rec.trip, communes[i].geom);
      if (atgeom)
        length[trip_rec.vehicle - 1][i + 1] += tpoint_length(atgeom) / 1000;
    }

  } while (!feof(file));

  printf("\n%d trip records read.\n", records);

  /* Close the file */
  fclose(file);

  /* Finalize MEOS */
  meos_finish();

  return 0;
}
