/* GENERATED by tools/codegen/inherited/generate.py from templates/compops.sql.tmpl — DO NOT EDIT BY HAND;
 * edit the template + tools/codegen/inherited/manifest.d and re-run. */
/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief Ever/always and temporal comparison functions and operators for
 * temporal pgpointcloud points
 */

/*****************************************************************************
 * Ever/Always Comparison Functions
 *****************************************************************************/

CREATE FUNCTION eEqual(pcpoint, tpcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_eq_pcpoint_tpcpoint'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?= (
  LEFTARG = pcpoint, RIGHTARG = tpcpoint,
  PROCEDURE = eEqual,
  NEGATOR = %<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aEqual(pcpoint, tpcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_eq_pcpoint_tpcpoint'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %= (
  LEFTARG = pcpoint, RIGHTARG = tpcpoint,
  PROCEDURE = aEqual,
  NEGATOR = ?<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION eNotEqual(pcpoint, tpcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_ne_pcpoint_tpcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?<> (
  LEFTARG = pcpoint, RIGHTARG = tpcpoint,
  PROCEDURE = eNotEqual,
  NEGATOR = %=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aNotEqual(pcpoint, tpcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_ne_pcpoint_tpcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %<> (
  LEFTARG = pcpoint, RIGHTARG = tpcpoint,
  PROCEDURE = aNotEqual,
  NEGATOR = ?=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

/*****************************************************************************/

CREATE FUNCTION eEqual(tpcpoint, pcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_eq_tpcpoint_pcpoint'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?= (
  LEFTARG = tpcpoint, RIGHTARG = pcpoint,
  PROCEDURE = eEqual,
  NEGATOR = %<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aEqual(tpcpoint, pcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_eq_tpcpoint_pcpoint'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %= (
  LEFTARG = tpcpoint, RIGHTARG = pcpoint,
  PROCEDURE = aEqual,
  NEGATOR = ?<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION eNotEqual(tpcpoint, pcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_ne_tpcpoint_pcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?<> (
  LEFTARG = tpcpoint, RIGHTARG = pcpoint,
  PROCEDURE = eNotEqual,
  NEGATOR = %=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aNotEqual(tpcpoint, pcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_ne_tpcpoint_pcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %<> (
  LEFTARG = tpcpoint, RIGHTARG = pcpoint,
  PROCEDURE = aNotEqual,
  NEGATOR = ?=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

/*****************************************************************************/

CREATE FUNCTION eEqual(tpcpoint, tpcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_eq_tpcpoint_tpcpoint'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?= (
  LEFTARG = tpcpoint, RIGHTARG = tpcpoint,
  PROCEDURE = eEqual,
  NEGATOR = %<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aEqual(tpcpoint, tpcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_eq_tpcpoint_tpcpoint'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %= (
  LEFTARG = tpcpoint, RIGHTARG = tpcpoint,
  PROCEDURE = aEqual,
  NEGATOR = ?<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION eNotEqual(tpcpoint, tpcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_ne_tpcpoint_tpcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?<> (
  LEFTARG = tpcpoint, RIGHTARG = tpcpoint,
  PROCEDURE = eNotEqual,
  NEGATOR = %=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aNotEqual(tpcpoint, tpcpoint)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_ne_tpcpoint_tpcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %<> (
  LEFTARG = tpcpoint, RIGHTARG = tpcpoint,
  PROCEDURE = aNotEqual,
  NEGATOR = ?=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

/*****************************************************************************
 * Temporal equal
 *****************************************************************************/

CREATE FUNCTION tEqual(pcpoint, tpcpoint)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Teq_pcpoint_tpcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tEqual(tpcpoint, pcpoint)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Teq_tpcpoint_pcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tEqual(tpcpoint, tpcpoint)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Teq_temporal_temporal'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR #= (
  PROCEDURE = tEqual,
  LEFTARG = pcpoint, RIGHTARG = tpcpoint,
  COMMUTATOR = #=
);
CREATE OPERATOR #= (
  PROCEDURE = tEqual,
  LEFTARG = tpcpoint, RIGHTARG = pcpoint,
  COMMUTATOR = #=
);
CREATE OPERATOR #= (
  PROCEDURE = tEqual,
  LEFTARG = tpcpoint, RIGHTARG = tpcpoint,
  COMMUTATOR = #=
);

/*****************************************************************************
 * Temporal not equal
 *****************************************************************************/

CREATE FUNCTION tNotEqual(pcpoint, tpcpoint)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Tne_pcpoint_tpcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tNotEqual(tpcpoint, pcpoint)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Tne_tpcpoint_pcpoint'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tNotEqual(tpcpoint, tpcpoint)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Tne_temporal_temporal'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR #<> (
  PROCEDURE = tNotEqual,
  LEFTARG = pcpoint, RIGHTARG = tpcpoint,
  COMMUTATOR = #<>
);
CREATE OPERATOR #<> (
  PROCEDURE = tNotEqual,
  LEFTARG = tpcpoint, RIGHTARG = pcpoint,
  COMMUTATOR = #<>
);
CREATE OPERATOR #<> (
  PROCEDURE = tNotEqual,
  LEFTARG = tpcpoint, RIGHTARG = tpcpoint,
  COMMUTATOR = #<>
);
/*****************************************************************************/
