/* GENERATED by tools/codegen/inherited/generate.py from templates/spatialrels.sql.tmpl — DO NOT EDIT BY HAND;
 * edit the template + tools/codegen/inherited/manifest.d and re-run. */
/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2025, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice
 * and this paragraph and the following two paragraphs appear in all
 * copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY
 * FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
 * INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND
 * ITS DOCUMENTATION, EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 * PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE
 * BRUXELLES HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief Ever/always spatial relationships for temporal pgpointcloud
 *   points
 *
 * Each function converts its point cloud operand to the temporal
 * geometry point its positions resolve to, through the standard
 * tpcpoint::tgeompoint cast, and delegates to the temporal geometry
 * point ever/always spatial relationship.
 */

/*****************************************************************************
 * Ever/always contains
 *****************************************************************************/

CREATE FUNCTION eContains(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eContains($1, $2::@extschema@.tgeompoint) $$;
CREATE FUNCTION aContains(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aContains($1, $2::@extschema@.tgeompoint) $$;

/*****************************************************************************
 * Ever/always covers
 *****************************************************************************/

CREATE FUNCTION eCovers(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eCovers($1, $2::@extschema@.tgeompoint) $$;
CREATE FUNCTION aCovers(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aCovers($1, $2::@extschema@.tgeompoint) $$;

/*****************************************************************************
 * Ever/always disjoint
 *****************************************************************************/

CREATE FUNCTION eDisjoint(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint($1, $2::@extschema@.tgeompoint) $$;
CREATE FUNCTION aDisjoint(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint($1, $2::@extschema@.tgeompoint) $$;

CREATE FUNCTION eDisjoint(tpcpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint($1::@extschema@.tgeompoint, $2) $$;
CREATE FUNCTION aDisjoint(tpcpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint($1::@extschema@.tgeompoint, $2) $$;

CREATE FUNCTION eDisjoint(tpcpoint, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint($1::@extschema@.tgeompoint,
                          $2::@extschema@.tgeompoint) $$;
CREATE FUNCTION aDisjoint(tpcpoint, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint($1::@extschema@.tgeompoint,
                          $2::@extschema@.tgeompoint) $$;

/*****************************************************************************
 * Ever/always intersects
 *****************************************************************************/

CREATE FUNCTION eIntersects(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects($1, $2::@extschema@.tgeompoint) $$;
CREATE FUNCTION aIntersects(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects($1, $2::@extschema@.tgeompoint) $$;

CREATE FUNCTION eIntersects(tpcpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects($1::@extschema@.tgeompoint, $2) $$;
CREATE FUNCTION aIntersects(tpcpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects($1::@extschema@.tgeompoint, $2) $$;

CREATE FUNCTION eIntersects(tpcpoint, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects($1::@extschema@.tgeompoint,
                            $2::@extschema@.tgeompoint) $$;
CREATE FUNCTION aIntersects(tpcpoint, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects($1::@extschema@.tgeompoint,
                            $2::@extschema@.tgeompoint) $$;

/*****************************************************************************
 * Ever/always touches
 *****************************************************************************/

CREATE FUNCTION eTouches(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eTouches($1, $2::@extschema@.tgeompoint) $$;
CREATE FUNCTION aTouches(geometry, tpcpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aTouches($1, $2::@extschema@.tgeompoint) $$;

CREATE FUNCTION eTouches(tpcpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eTouches($1::@extschema@.tgeompoint, $2) $$;
CREATE FUNCTION aTouches(tpcpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aTouches($1::@extschema@.tgeompoint, $2) $$;

/*****************************************************************************
 * Ever/always dwithin
 *****************************************************************************/

CREATE FUNCTION eDwithin(geometry, tpcpoint, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin($1, $2::@extschema@.tgeompoint, $3) $$;
CREATE FUNCTION aDwithin(geometry, tpcpoint, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin($1, $2::@extschema@.tgeompoint, $3) $$;

CREATE FUNCTION eDwithin(tpcpoint, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin($1::@extschema@.tgeompoint, $2, $3) $$;
CREATE FUNCTION aDwithin(tpcpoint, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin($1::@extschema@.tgeompoint, $2, $3) $$;

CREATE FUNCTION eDwithin(tpcpoint, tpcpoint, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin($1::@extschema@.tgeompoint,
                         $2::@extschema@.tgeompoint, $3) $$;
CREATE FUNCTION aDwithin(tpcpoint, tpcpoint, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin($1::@extschema@.tgeompoint,
                         $2::@extschema@.tgeompoint, $3) $$;

/*****************************************************************************/
