/*
 * GENERATED by scripts/h3pg_import/extract.py — DO NOT EDIT.
 */

#pragma once

#include <h3api.h>
#include <meos.h>

extern bool h3_are_neighbor_cells_meos(H3Index origin, H3Index destination);
extern H3Index h3_cells_to_directed_edge_meos(H3Index origin,
  H3Index destination);
extern bool h3_is_valid_directed_edge_meos(H3Index edge);
extern H3Index h3_get_directed_edge_origin_meos(H3Index edge);
extern H3Index h3_get_directed_edge_destination_meos(H3Index edge);
extern H3Index h3_cell_to_parent_meos(H3Index origin, int32 resolution);
extern H3Index h3_cell_to_center_child_meos(H3Index origin, int32 resolution);
extern int64 h3_cell_to_child_pos_meos(H3Index child, int32 parentRes);
extern H3Index h3_child_pos_to_cell_meos(int64 childPos, H3Index parent,
  int32 childRes);
extern int32 h3_get_resolution_meos(H3Index hex);
extern int32 h3_get_base_cell_number_meos(H3Index hex);
extern bool h3_is_valid_cell_meos(H3Index hex);
extern bool h3_is_res_class_iii_meos(H3Index hex);
extern bool h3_is_pentagon_meos(H3Index hex);
extern int64 h3_get_num_cells_meos(int32 resolution);
extern int64 h3_grid_distance_meos(H3Index originIndex, H3Index h3Index);
extern H3Index h3_cell_to_vertex_meos(H3Index cell, int32 vertexNum);
extern bool h3_is_valid_vertex_meos(H3Index vertex);
