#!/usr/bin/env bash
#
# Build every MEOS smoke-test in this directory, run each under
# valgrind, and exit non-zero if any suite crashes or leaks.
#
# Usage:
#   meos/test/run_smoketests.sh                # use system MEOS in /usr/local
#   MEOS_BUILD_DIR=./build ./run_smoketests.sh # use a local MEOS build
#
# The smoke-test C files are auto-generated by gen_smoketest.py from the
# corresponding meos_*.h public headers. Each test runs every public
# function once with canned inputs; a clean valgrind run is the
# project's only floor against memory leaks that the PG infrastructure
# would otherwise hide.
#
# tgeometry_smoketest uses --leak-check=summary (not --leak-check=full)
# because the PROJ/SQLite3 SRS database lookups generate thousands of
# "possibly lost" records that exhaust valgrind's internal accounting.
# MEOS leaks in the tgeometry suite are caught by other means (ASan CI).

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
MEOS_BUILD_DIR="${MEOS_BUILD_DIR:-/usr/local/lib}"
MEOS_INCLUDE_DIR="${MEOS_INCLUDE_DIR:-/usr/local/include}"

SUITES=(
  trgeometry_test
  tpose_smoketest
  tcbuffer_smoketest
  tnpoint_smoketest
  tgeometry_smoketest
)

mkdir -p "$HERE/build"

fail=0
for suite in "${SUITES[@]}"; do
  src="$HERE/$suite.c"
  bin="$HERE/build/$suite"
  if [ ! -f "$src" ]; then
    echo "[skip] $suite: $src missing"
    continue
  fi
  echo "[build] $suite"
  gcc -Wall -g -I"$MEOS_INCLUDE_DIR" -o "$bin" "$src" \
    -L"$MEOS_BUILD_DIR" -lmeos -lm
  echo "[run]   $suite"
  # tgeometry uses --leak-check=summary: full check OOMs valgrind due to
  # PROJ/SQLite3 SRS allocations; MEOS leaks are caught by ASan CI.
  if [ "$suite" = "tgeometry_smoketest" ]; then
    vg_leak="--leak-check=summary"
  else
    vg_leak="--leak-check=full"
  fi
  if ! LD_LIBRARY_PATH="$MEOS_BUILD_DIR" valgrind \
        $vg_leak --error-exitcode=1 --quiet \
        --suppressions="$HERE/meos_smoketest.supp" \
        "$bin" >"$bin.out" 2>"$bin.err"; then
    echo "[FAIL]  $suite — see $bin.out / $bin.err"
    fail=1
  else
    lines=$(wc -l < "$bin.out")
    warns=$(wc -l < "$bin.err")
    echo "[ok]    $suite — $lines results, $warns validation warns"
  fi
done

if [ "$fail" -ne 0 ]; then
  echo
  echo "One or more smoke suites failed. Inspect the .out / .err files"
  echo "in meos/test/build/ for the call site of the leak or crash."
  exit 1
fi

echo
echo "All smoke suites passed valgrind."
