#!/usr/bin/env bash
#
# This MobilityDB code is provided under The PostgreSQL License.
# Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
# contributors
#
# MobilityDB includes portions of PostGIS version 3 source code released
# under the GNU General Public License (GPLv2 or later).
# Copyright (c) 2001-2026, PostGIS contributors
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written
# agreement is hereby granted, provided that the above copyright notice and
# this paragraph and the following two paragraphs appear in all copies.
#
# IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
# DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
# LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
# EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.
#
# UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
# AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
# PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
#

#
# Build every MEOS smoke-test in this directory, run each under
# valgrind, and exit non-zero if any suite crashes or leaks.
#
# Usage:
#   meos/test/run_smoketests.sh                # use system MEOS in /usr/local
#   MEOS_BUILD_DIR=./build ./run_smoketests.sh # use a local MEOS build
#
# The smoke-test C files are auto-generated by gen_smoketest.py from the
# corresponding meos_*.h public headers. Each test runs every public
# function once with canned inputs; a clean valgrind run is the
# project's only floor against memory leaks that the PG infrastructure
# would otherwise hide.
#
# tgeometry_smoketest runs --leak-check=full: the possibly-lost PROJ/SQLite3
# SRS-database noise is filtered by meos_smoketest.supp, so the strict check
# only reports genuine MEOS/liblwgeom leaks.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
MEOS_BUILD_DIR="${MEOS_BUILD_DIR:-/usr/local/lib}"
MEOS_INCLUDE_DIR="${MEOS_INCLUDE_DIR:-/usr/local/include}"

GEN="$HERE/../../tools/codegen/gen_smoketest/gen_smoketest.py"
if ! command -v python3 >/dev/null 2>&1; then
  echo "[FAIL]  python3 is required to name and generate the smoke suites"
  exit 1
fi

# The suites are the ones the generator configures: its in-file configs and
# each meos/test/smoke/<family>.json a family drops, which it DISCOVERS rather
# than lists (the append_portable_aliases file(GLOB ...) model). Nothing here
# names a family, so adding one is adding its sidecar. A suite whose header did
# not install is still listed, and the loop below fails it.
mapfile -t SUITES < <(python3 "$GEN" --list)

# Regenerate the smoke-test C files from the INSTALLED MEOS headers so the
# suite always matches the library it is about to link against. Committed
# *.c files are generated artifacts and can go stale (e.g. when a public
# signature changes); regenerating here is the contract the CI step name
# ("Regenerate smoke suites and run") promises. gen_smoketest.py emits every
# configured family, including trgeometry_test.c.
if command -v python3 >/dev/null 2>&1; then
  echo "[gen]   regenerating smoke suites from $MEOS_INCLUDE_DIR"
  MEOS_INCLUDE_DIR="$MEOS_INCLUDE_DIR" python3 "$HERE/../../tools/codegen/gen_smoketest/gen_smoketest.py"
fi

mkdir -p "$HERE/build"

fail=0
ran=0
for suite in "${SUITES[@]}"; do
  src="$HERE/$suite.c"
  bin="$HERE/build/$suite"
  if [ ! -f "$src" ]; then
    # A named suite that does not generate is a suite nobody runs, and passing
    # over it left the run reporting "All smoke suites passed" while checking
    # less than it names. The generation step above reads the INSTALLED
    # headers, so a missing source means the family's header did not install --
    # the very condition these suites exist to catch.
    echo "[FAIL]  $suite: $src was not generated from $MEOS_INCLUDE_DIR"
    echo "          build every family (-DALL=on) so each public header installs"
    fail=1
    continue
  fi
  ran=$((ran + 1))
  echo "[build] $suite"
  gcc -Wall -g -I"$MEOS_INCLUDE_DIR" -o "$bin" "$src" \
    -L"$MEOS_BUILD_DIR" -lmeos -lm
  echo "[run]   $suite"
  # Every suite runs the strict full check. A suite running a weaker check than
  # its siblings reports the same green while measuring less, which is how the
  # moving-rigid-geometry surface kept a leak nothing reported: meos_smoketest.supp
  # filters the PROJ/SQLite3 SRS possibly-lost noise, so what full reports is a
  # genuine MEOS/liblwgeom leak in every suite alike.
  if ! LD_LIBRARY_PATH="$MEOS_BUILD_DIR" valgrind \
        --leak-check=full --error-exitcode=1 --quiet \
        --suppressions="$HERE/meos_smoketest.supp" \
        "$bin" >"$bin.out" 2>"$bin.err"; then
    echo "[FAIL]  $suite — see $bin.out / $bin.err"
    fail=1
  else
    lines=$(wc -l < "$bin.out")
    # A validation warning is a `[meos warn]` line, which the generated suite's
    # own error handler writes when MEOS REFUSES an input. Count that, not the
    # whole of stderr: PROJ writes its own notices there
    # (proj_normalize_for_visualization, from the reprojection entries), so a
    # line count reports a suite as carrying warnings it does not have.
    warns=$(grep -c '\[meos warn\]' "$bin.err" || true)
    notices=$(grep -vc '\[meos warn\]' "$bin.err" || true)
    if [ "$warns" -ne 0 ]; then
      # A refused input means the call returned at its guard and the function
      # body never ran, so the suite reports coverage it does not have and
      # anything wrong below that guard is unreachable. Every entry is to be
      # called with a value it ACCEPTS.
      echo "[FAIL]  $suite — $lines results, $warns validation warning(s):"
      grep '\[meos warn\]' "$bin.err" | sort | uniq -c | sed 's/^/          /'
      echo "          give each entry an input it accepts, then re-run"
      fail=1
    else
      echo "[ok]    $suite — $lines results, 0 validation warns, $notices library notice(s)"
    fi
  fi
done

# Refusing a skip leaves DELETION as the remaining way to stop running a suite,
# and a deleted config or sidecar reports nothing anywhere: the COUNT is the
# only thing that moves. The floor is the number of suites master runs -- the
# generator's six in-file configs plus its four meos/test/smoke/*.json
# sidecars -- so removing one reddens instead of quietly shrinking the run.
# Raise it when a family is added.
floor="${MEOS_SMOKE_FLOOR:-10}"
if [ "$ran" -lt "$floor" ]; then
  echo
  echo "[FAIL]  $ran smoke suite(s) ran, below the floor of $floor"
  echo "          a name left SUITES, or a family lost its meos/test/smoke/*.json"
  fail=1
fi

if [ "$fail" -ne 0 ]; then
  echo
  echo "One or more smoke suites failed. Inspect the .out / .err files"
  echo "in meos/test/build/ for the call site of the leak or crash."
  exit 1
fi

echo
echo "All $ran smoke suites passed valgrind."
