/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief MEOS smoke test for the tcbuffer     public API.
 *
 * Auto-generated by meos/test/gen_smoketest.py — do not edit by hand.
 *
 * Each public symbol exported by meos_cbuffer.h gets one smoke-test
 * call site here. Arguments come from a shared common-inputs block.
 * Pointer results are freed; a non-fatal MEOS error handler keeps the
 * run going past VALIDATE_* failures so a single bad input doesn't
 * mask the rest of the surface.
 *
 * Run under valgrind to catch leaks/OOB reads:
 *
 *     valgrind --leak-check=full --error-exitcode=1 ./tcbuffer_smoketest
 *
 * Build:
 *   gcc -Wall -g -I/usr/local/include -o tcbuffer_smoketest \
 *       tcbuffer_smoketest.c -L/usr/local/lib -lmeos -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <meos.h>
#include <meos_geo.h>
#include <meos_pose.h>
#include <meos_cbuffer.h>
#include <meos_internal.h>

#ifndef DatumDefined
typedef uintptr_t Datum;
#define DatumDefined 1
#endif

static void
test_error_handler(int level, int code, const char *msg)
{
  (void) level; (void) code;
  fprintf(stderr, "[meos warn] %s\n", msg);
}

int
main(void)
{
  meos_initialize();
  meos_initialize_timezone("UTC");
  meos_initialize_error_handler(test_error_handler);

  TimestampTz tstz1 = pg_timestamptz_in("2001-01-02", -1);
  Span *tstzspan1 = tstzspan_in("[2001-01-01, 2001-01-04]");
  SpanSet *tstzspanset1 = tstzspanset_in("{[2001-01-01, 2001-01-02], [2001-01-03, 2001-01-04]}");
  Interval *interv1 = NULL;
  GSERIALIZED *geom1 = geom_in("Point(0 0)", -1);
  GSERIALIZED *geom_out_param = NULL;
  Cbuffer *cbuffer1 = cbuffer_in("Cbuffer(Point(1 1), 0.5)");
  Cbuffer *cbuffer_out_param = NULL;
  Set *cbufferset1 = cbufferset_in("{\"Cbuffer(Point(1 1), 0.5)\"}");
  STBox *stbox1 = stbox_in("STBOX X((0, 0), (10, 10))");
  Datum cbuffer1_datum = (Datum) cbuffer1;
  size_t size_out = 0;

  Temporal *tcbuffer1 = tcbuffer_in(
    "[Cbuffer(Point(0 0), 0.5)@2001-01-02, Cbuffer(Point(1 0), 0.5)@2001-01-03]");
  TInstant *tcbuffer_inst1 = (TInstant *) temporal_start_inst(tcbuffer1);
  TSequence    *tcbuffer_tseq1    = (TSequence *) tcbuffer1;
  TSequenceSet *tcbuffer_tseqset1 = NULL;
  Temporal *tpoint1 = tcbuffer_to_tgeompoint(tcbuffer1);
  int n_out = 0;


  printf("****************************************************************\n");
  printf("* tcbuffer     MEOS smoke test%*s*\n", 32, "");
  printf("****************************************************************\n");

  { char *r = cbuffer_as_ewkt(cbuffer1, 1);
    printf("cbuffer_as_ewkt: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { char *r = cbuffer_as_hexwkb(cbuffer1, 1, &size_out);
    printf("cbuffer_as_hexwkb: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { char *r = cbuffer_as_text(cbuffer1, 1);
    printf("cbuffer_as_text: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { uint8_t * r = cbuffer_as_wkb(cbuffer1, 1, &size_out);
    printf("cbuffer_as_wkb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP cbuffer_from_hexwkb: unmapped arg type 'char *' */
  /* SKIP cbuffer_from_wkb: unmapped arg type 'uint8_t *' */
  /* SKIP cbuffer_in: unmapped arg type 'char *' */
  { char *r = cbuffer_out(cbuffer1, 1);
    printf("cbuffer_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { Cbuffer * r = cbuffer_copy(cbuffer1);
    printf("cbuffer_copy: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Cbuffer * r = cbuffer_make(geom1, 1.0);
    printf("cbuffer_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = cbuffer_to_geom(cbuffer1);
    printf("cbuffer_to_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = cbuffer_to_stbox(cbuffer1);
    printf("cbuffer_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP cbufferarr_to_geom: unmapped arg type 'Cbuffer * *' */
  { Cbuffer * r = geom_to_cbuffer(geom1);
    printf("geom_to_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP cbuffer_hash: unmapped return type 'uint32' */
  /* SKIP cbuffer_hash_extended: unmapped arg type 'uint64' */
  { GSERIALIZED * r = cbuffer_point(cbuffer1);
    printf("cbuffer_point: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = cbuffer_radius(cbuffer1);
    printf("cbuffer_radius: %.6f\n", r); }
  { Cbuffer * r = cbuffer_round(cbuffer1, 1);
    printf("cbuffer_round: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP cbufferarr_round: unmapped arg type 'Cbuffer * *' */
  /* SKIP cbuffer_set_srid: unmapped return type 'void' */
  /* SKIP cbuffer_srid: unmapped return type 'int32_t' */
  { Cbuffer * r = cbuffer_transform(cbuffer1, 0);
    printf("cbuffer_transform: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP cbuffer_transform_pipeline: unmapped arg type 'char *' */
  { int r = contains_cbuffer_cbuffer(cbuffer1, cbuffer1);
    printf("contains_cbuffer_cbuffer: %d\n", r); }
  { int r = covers_cbuffer_cbuffer(cbuffer1, cbuffer1);
    printf("covers_cbuffer_cbuffer: %d\n", r); }
  { int r = disjoint_cbuffer_cbuffer(cbuffer1, cbuffer1);
    printf("disjoint_cbuffer_cbuffer: %d\n", r); }
  { int r = dwithin_cbuffer_cbuffer(cbuffer1, cbuffer1, 1.0);
    printf("dwithin_cbuffer_cbuffer: %d\n", r); }
  { int r = intersects_cbuffer_cbuffer(cbuffer1, cbuffer1);
    printf("intersects_cbuffer_cbuffer: %d\n", r); }
  { int r = touches_cbuffer_cbuffer(cbuffer1, cbuffer1);
    printf("touches_cbuffer_cbuffer: %d\n", r); }
  { STBox * r = cbuffer_tstzspan_to_stbox(cbuffer1, tstzspan1);
    printf("cbuffer_tstzspan_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = cbuffer_timestamptz_to_stbox(cbuffer1, tstz1);
    printf("cbuffer_timestamptz_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = distance_cbuffer_cbuffer(cbuffer1, cbuffer1);
    printf("distance_cbuffer_cbuffer: %.6f\n", r); }
  { double r = distance_cbuffer_geo(cbuffer1, geom1);
    printf("distance_cbuffer_geo: %.6f\n", r); }
  { double r = distance_cbuffer_stbox(cbuffer1, stbox1);
    printf("distance_cbuffer_stbox: %.6f\n", r); }
  { double r = nad_cbuffer_stbox(cbuffer1, stbox1);
    printf("nad_cbuffer_stbox: %.6f\n", r); }
  { int r = cbuffer_cmp(cbuffer1, cbuffer1);
    printf("cbuffer_cmp: %d\n", r); }
  { bool r = cbuffer_eq(cbuffer1, cbuffer1);
    printf("cbuffer_eq: %d\n", (int) r); }
  { bool r = cbuffer_ge(cbuffer1, cbuffer1);
    printf("cbuffer_ge: %d\n", (int) r); }
  { bool r = cbuffer_gt(cbuffer1, cbuffer1);
    printf("cbuffer_gt: %d\n", (int) r); }
  { bool r = cbuffer_le(cbuffer1, cbuffer1);
    printf("cbuffer_le: %d\n", (int) r); }
  { bool r = cbuffer_lt(cbuffer1, cbuffer1);
    printf("cbuffer_lt: %d\n", (int) r); }
  { bool r = cbuffer_ne(cbuffer1, cbuffer1);
    printf("cbuffer_ne: %d\n", (int) r); }
  { bool r = cbuffer_nsame(cbuffer1, cbuffer1);
    printf("cbuffer_nsame: %d\n", (int) r); }
  { bool r = cbuffer_same(cbuffer1, cbuffer1);
    printf("cbuffer_same: %d\n", (int) r); }
  /* SKIP cbufferset_in: unmapped arg type 'char *' */
  { char *r = cbufferset_out(cbufferset1, 1);
    printf("cbufferset_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP cbufferset_make: unmapped arg type 'Cbuffer * *' */
  { Set * r = cbuffer_to_set(cbuffer1);
    printf("cbuffer_to_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Cbuffer * r = cbufferset_end_value(cbufferset1);
    printf("cbufferset_end_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Cbuffer * r = cbufferset_start_value(cbufferset1);
    printf("cbufferset_start_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP cbufferset_value_n: unmapped arg type 'Cbuffer * *' */
  { Cbuffer * * r = cbufferset_values(cbufferset1);
    printf("cbufferset_values: %s\n", r ? "OK" : "NULL");
    if (r) {
      int _n = set_num_values(cbufferset1);
      for (int _i = 0; _i < _n; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  /* SKIP cbuffer_union_transfn: aggregate state-handoff pattern incompatible with smoke-test ownership model */
  { bool r = contained_cbuffer_set(cbuffer1, cbufferset1);
    printf("contained_cbuffer_set: %d\n", (int) r); }
  { bool r = contains_set_cbuffer(cbufferset1, cbuffer1);
    printf("contains_set_cbuffer: %d\n", (int) r); }
  { Set * r = intersection_cbuffer_set(cbuffer1, cbufferset1);
    printf("intersection_cbuffer_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = intersection_set_cbuffer(cbufferset1, cbuffer1);
    printf("intersection_set_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = minus_cbuffer_set(cbuffer1, cbufferset1);
    printf("minus_cbuffer_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = minus_set_cbuffer(cbufferset1, cbuffer1);
    printf("minus_set_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = union_cbuffer_set(cbuffer1, cbufferset1);
    printf("union_cbuffer_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = union_set_cbuffer(cbufferset1, cbuffer1);
    printf("union_set_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tcbuffer_in: unmapped arg type 'char *' */
  { Temporal * r = tcbuffer_make(tcbuffer1, tcbuffer1);
    printf("tcbuffer_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = tcbuffer_points(tcbuffer1);
    printf("tcbuffer_points: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = tcbuffer_radius(tcbuffer1);
    printf("tcbuffer_radius: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = tcbuffer_trav_area(tcbuffer1, true);
    printf("tcbuffer_trav_area: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcbuffer_to_tfloat(tcbuffer1);
    printf("tcbuffer_to_tfloat: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcbuffer_to_tgeompoint(tcbuffer1);
    printf("tcbuffer_to_tgeompoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeometry_to_tcbuffer(tcbuffer1);
    printf("tgeometry_to_tcbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcbuffer_expand(tcbuffer1, 1.0);
    printf("tcbuffer_expand: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcbuffer_at_cbuffer(tcbuffer1, cbuffer1);
    printf("tcbuffer_at_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcbuffer_at_geom(tcbuffer1, geom1);
    printf("tcbuffer_at_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcbuffer_at_stbox(tcbuffer1, stbox1, true);
    printf("tcbuffer_at_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcbuffer_minus_cbuffer(tcbuffer1, cbuffer1);
    printf("tcbuffer_minus_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcbuffer_minus_geom(tcbuffer1, geom1);
    printf("tcbuffer_minus_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcbuffer_minus_stbox(tcbuffer1, stbox1, true);
    printf("tcbuffer_minus_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("tdistance_tcbuffer_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_tcbuffer_geo(tcbuffer1, geom1);
    printf("tdistance_tcbuffer_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("tdistance_tcbuffer_tcbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = nad_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("nad_tcbuffer_cbuffer: %.6f\n", r); }
  { double r = nad_tcbuffer_geo(tcbuffer1, geom1);
    printf("nad_tcbuffer_geo: %.6f\n", r); }
  { double r = nad_tcbuffer_stbox(tcbuffer1, stbox1);
    printf("nad_tcbuffer_stbox: %.6f\n", r); }
  { double r = nad_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("nad_tcbuffer_tcbuffer: %.6f\n", r); }
  { TInstant * r = nai_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("nai_tcbuffer_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = nai_tcbuffer_geo(tcbuffer1, geom1);
    printf("nai_tcbuffer_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = nai_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("nai_tcbuffer_tcbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("shortestline_tcbuffer_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_tcbuffer_geo(tcbuffer1, geom1);
    printf("shortestline_tcbuffer_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("shortestline_tcbuffer_tcbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { int r = always_eq_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("always_eq_cbuffer_tcbuffer: %d\n", r); }
  { int r = always_eq_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("always_eq_tcbuffer_cbuffer: %d\n", r); }
  { int r = always_eq_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("always_eq_tcbuffer_tcbuffer: %d\n", r); }
  { int r = always_ne_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("always_ne_cbuffer_tcbuffer: %d\n", r); }
  { int r = always_ne_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("always_ne_tcbuffer_cbuffer: %d\n", r); }
  { int r = always_ne_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("always_ne_tcbuffer_tcbuffer: %d\n", r); }
  { int r = ever_eq_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("ever_eq_cbuffer_tcbuffer: %d\n", r); }
  { int r = ever_eq_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("ever_eq_tcbuffer_cbuffer: %d\n", r); }
  { int r = ever_eq_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("ever_eq_tcbuffer_tcbuffer: %d\n", r); }
  { int r = ever_ne_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("ever_ne_cbuffer_tcbuffer: %d\n", r); }
  { int r = ever_ne_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("ever_ne_tcbuffer_cbuffer: %d\n", r); }
  { int r = ever_ne_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("ever_ne_tcbuffer_tcbuffer: %d\n", r); }
  { Temporal * r = teq_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("teq_cbuffer_tcbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = teq_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("teq_tcbuffer_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("tne_cbuffer_tcbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("tne_tcbuffer_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { int r = acontains_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("acontains_cbuffer_tcbuffer: %d\n", r); }
  { int r = acontains_geo_tcbuffer(geom1, tcbuffer1);
    printf("acontains_geo_tcbuffer: %d\n", r); }
  { int r = acontains_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("acontains_tcbuffer_cbuffer: %d\n", r); }
  { int r = acontains_tcbuffer_geo(tcbuffer1, geom1);
    printf("acontains_tcbuffer_geo: %d\n", r); }
  { int r = acovers_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("acovers_cbuffer_tcbuffer: %d\n", r); }
  { int r = acovers_geo_tcbuffer(geom1, tcbuffer1);
    printf("acovers_geo_tcbuffer: %d\n", r); }
  { int r = acovers_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("acovers_tcbuffer_cbuffer: %d\n", r); }
  { int r = acovers_tcbuffer_geo(tcbuffer1, geom1);
    printf("acovers_tcbuffer_geo: %d\n", r); }
  { int r = adisjoint_tcbuffer_geo(tcbuffer1, geom1);
    printf("adisjoint_tcbuffer_geo: %d\n", r); }
  { int r = adisjoint_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("adisjoint_tcbuffer_cbuffer: %d\n", r); }
  { int r = adisjoint_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("adisjoint_tcbuffer_tcbuffer: %d\n", r); }
  { int r = adwithin_tcbuffer_geo(tcbuffer1, geom1, 1.0);
    printf("adwithin_tcbuffer_geo: %d\n", r); }
  { int r = adwithin_tcbuffer_cbuffer(tcbuffer1, cbuffer1, 1.0);
    printf("adwithin_tcbuffer_cbuffer: %d\n", r); }
  { int r = adwithin_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1, 1.0);
    printf("adwithin_tcbuffer_tcbuffer: %d\n", r); }
  { int r = aintersects_tcbuffer_geo(tcbuffer1, geom1);
    printf("aintersects_tcbuffer_geo: %d\n", r); }
  { int r = aintersects_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("aintersects_tcbuffer_cbuffer: %d\n", r); }
  { int r = aintersects_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("aintersects_tcbuffer_tcbuffer: %d\n", r); }
  { int r = atouches_tcbuffer_geo(tcbuffer1, geom1);
    printf("atouches_tcbuffer_geo: %d\n", r); }
  { int r = atouches_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("atouches_tcbuffer_cbuffer: %d\n", r); }
  { int r = atouches_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("atouches_tcbuffer_tcbuffer: %d\n", r); }
  { int r = econtains_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("econtains_cbuffer_tcbuffer: %d\n", r); }
  { int r = econtains_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("econtains_tcbuffer_cbuffer: %d\n", r); }
  { int r = econtains_tcbuffer_geo(tcbuffer1, geom1);
    printf("econtains_tcbuffer_geo: %d\n", r); }
  { int r = ecovers_cbuffer_tcbuffer(cbuffer1, tcbuffer1);
    printf("ecovers_cbuffer_tcbuffer: %d\n", r); }
  { int r = ecovers_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("ecovers_tcbuffer_cbuffer: %d\n", r); }
  { int r = ecovers_tcbuffer_geo(tcbuffer1, geom1);
    printf("ecovers_tcbuffer_geo: %d\n", r); }
  { int r = ecovers_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("ecovers_tcbuffer_tcbuffer: %d\n", r); }
  { int r = edisjoint_tcbuffer_geo(tcbuffer1, geom1);
    printf("edisjoint_tcbuffer_geo: %d\n", r); }
  { int r = edisjoint_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("edisjoint_tcbuffer_cbuffer: %d\n", r); }
  { int r = edwithin_tcbuffer_geo(tcbuffer1, geom1, 1.0);
    printf("edwithin_tcbuffer_geo: %d\n", r); }
  { int r = edwithin_tcbuffer_cbuffer(tcbuffer1, cbuffer1, 1.0);
    printf("edwithin_tcbuffer_cbuffer: %d\n", r); }
  { int r = edwithin_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1, 1.0);
    printf("edwithin_tcbuffer_tcbuffer: %d\n", r); }
  { int r = eintersects_tcbuffer_geo(tcbuffer1, geom1);
    printf("eintersects_tcbuffer_geo: %d\n", r); }
  { int r = eintersects_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("eintersects_tcbuffer_cbuffer: %d\n", r); }
  { int r = eintersects_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("eintersects_tcbuffer_tcbuffer: %d\n", r); }
  { int r = etouches_tcbuffer_geo(tcbuffer1, geom1);
    printf("etouches_tcbuffer_geo: %d\n", r); }
  { int r = etouches_tcbuffer_cbuffer(tcbuffer1, cbuffer1);
    printf("etouches_tcbuffer_cbuffer: %d\n", r); }
  { int r = etouches_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1);
    printf("etouches_tcbuffer_tcbuffer: %d\n", r); }
  /* SKIP tcontains_cbuffer_tcbuffer: MEOS bug: spanset path issue */
  /* SKIP tcontains_geo_tcbuffer: MEOS bug: spanset path issue */
  /* SKIP tcontains_tcbuffer_geo: MEOS bug: spanset path issue */
  /* SKIP tcontains_tcbuffer_cbuffer: MEOS bug: spanset path issue */
  /* SKIP tcontains_tcbuffer_tcbuffer: MEOS bug: spanset path issue */
  /* SKIP tcovers_cbuffer_tcbuffer: MEOS bug: spanset path issue */
  /* SKIP tcovers_geo_tcbuffer: MEOS bug: spanset path issue */
  /* SKIP tcovers_tcbuffer_geo: MEOS bug: spanset path issue */
  /* SKIP tcovers_tcbuffer_cbuffer: MEOS bug: spanset path issue */
  /* SKIP tcovers_tcbuffer_tcbuffer: MEOS bug: spanset path issue */
  { Temporal * r = tdwithin_geo_tcbuffer(geom1, tcbuffer1, 1.0);
    printf("tdwithin_geo_tcbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdwithin_tcbuffer_geo(tcbuffer1, geom1, 1.0);
    printf("tdwithin_tcbuffer_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdwithin_tcbuffer_cbuffer(tcbuffer1, cbuffer1, 1.0);
    printf("tdwithin_tcbuffer_cbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdwithin_tcbuffer_tcbuffer(tcbuffer1, tcbuffer1, 1.0);
    printf("tdwithin_tcbuffer_tcbuffer: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tdisjoint_cbuffer_tcbuffer: MEOS bug: Unknown compare function for type */
  /* SKIP tdisjoint_geo_tcbuffer: MEOS bug: Unknown compare function for type */
  /* SKIP tdisjoint_tcbuffer_geo: MEOS bug: Unknown compare function for type */
  /* SKIP tdisjoint_tcbuffer_cbuffer: MEOS bug: Unknown compare function for type */
  /* SKIP tdisjoint_tcbuffer_tcbuffer: MEOS bug: Unknown compare function for type */
  /* SKIP tintersects_cbuffer_tcbuffer: MEOS bug: type is not a span type */
  /* SKIP tintersects_geo_tcbuffer: MEOS bug: type is not a span type */
  /* SKIP tintersects_tcbuffer_geo: MEOS bug: type is not a span type */
  /* SKIP tintersects_tcbuffer_cbuffer: MEOS bug: type is not a span type */
  /* SKIP tintersects_tcbuffer_tcbuffer: MEOS bug: type is not a span type */
  /* SKIP ttouches_geo_tcbuffer: MEOS bug: spanset path issue */
  /* SKIP ttouches_tcbuffer_geo: MEOS bug: spanset path issue */
  /* SKIP ttouches_cbuffer_tcbuffer: MEOS bug: spanset path issue */
  /* SKIP ttouches_tcbuffer_cbuffer: MEOS bug: spanset path issue */
  /* SKIP ttouches_tcbuffer_tcbuffer: MEOS bug: spanset path issue */

  /* tcbuffer_inst1 is a VIEW into tcbuffer1 (temporal_start_inst); do NOT free */
  if (tcbuffer1) free(tcbuffer1);
  if (tpoint1) free(tpoint1);
  free(stbox1);
  free(cbufferset1);
  free(cbuffer1);
  free(geom1);
  free(tstzspanset1);
  free(tstzspan1);

  meos_finalize();
  return 0;
}
