/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief MEOS smoke test for the tgeometry    public API.
 *
 * Auto-generated by meos/test/gen_smoketest.py — do not edit by hand.
 *
 * Each public symbol exported by meos_geo.h gets one smoke-test
 * call site here. Arguments come from a shared common-inputs block.
 * Pointer results are freed; a non-fatal MEOS error handler keeps the
 * run going past VALIDATE_* failures so a single bad input doesn't
 * mask the rest of the surface.
 *
 * Run under valgrind to catch leaks/OOB reads:
 *
 *     valgrind --leak-check=full --error-exitcode=1 ./tgeometry_smoketest
 *
 * Build:
 *   gcc -Wall -g -I/usr/local/include -o tgeometry_smoketest \
 *       tgeometry_smoketest.c -L/usr/local/lib -lmeos -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <meos.h>
#include <meos_geo.h>
#include <meos_pose.h>


#ifndef DatumDefined
typedef uintptr_t Datum;
#define DatumDefined 1
#endif

static void
test_error_handler(int level, int code, const char *msg)
{
  (void) level; (void) code;
  fprintf(stderr, "[meos warn] %s\n", msg);
}

int
main(void)
{
  meos_initialize();
  meos_initialize_timezone("UTC");
  meos_initialize_error_handler(test_error_handler);

  TimestampTz tstz1 = pg_timestamptz_in("2001-01-02", -1);
  Span *tstzspan1 = tstzspan_in("[2001-01-01, 2001-01-04]");
  SpanSet *tstzspanset1 = tstzspanset_in("{[2001-01-01, 2001-01-02], [2001-01-03, 2001-01-04]}");
  Interval *interv1 = NULL;
  GSERIALIZED *geom1 = geom_in("Polygon((0 0,1 0,1 1,0 1,0 0))", -1);
  GSERIALIZED *geom_out_param = NULL;
  Set *geomset1 = geomset_in("{\"Point(0 0)\", \"Point(1 1)\"}");
  STBox *stbox1 = stbox_in("STBOX X((0, 0), (10, 10))");
  Datum geom1_datum = (Datum) geom1;
  size_t size_out = 0;
  bool bool_out = false;

  Temporal *tgeo1 = tgeometry_in(
    "[Polygon((0 0,1 0,1 1,0 1,0 0))@2001-01-02, Polygon((0 0,1 0,1 1,0 1,0 0))@2001-01-03]");
  TInstant *tgeo_inst1 = (TInstant *) temporal_start_instant(tgeo1);
  TSequence    *tgeo_tseq1    = (TSequence *) tgeo1;
  TSequenceSet *tgeo_tseqset1 = NULL;
  int n_out = 0;


  printf("****************************************************************\n");
  printf("* tgeometry    MEOS smoke test%*s*\n", 32, "");
  printf("****************************************************************\n");

  /* SKIP geo_get_srid: unmapped return type 'int32' */
  /* SKIP geo_as_ewkb: unmapped arg type 'char *' */
  { char *r = geo_as_ewkt(geom1, 1);
    printf("geo_as_ewkt: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP geo_as_geojson: unmapped arg type 'char *' */
  /* SKIP geo_as_hexewkb: unmapped arg type 'char *' */
  { char *r = geo_as_text(geom1, 1);
    printf("geo_as_text: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP geo_from_ewkb: unmapped arg type 'uint8_t *' */
  /* SKIP geo_from_geojson: unmapped arg type 'char *' */
  /* SKIP geo_from_text: unmapped arg type 'char *' */
  { char *r = geo_out(geom1);
    printf("geo_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP geog_from_binary: needs spatial_ref_sys CSV */
  /* SKIP geog_from_hexewkb: needs spatial_ref_sys CSV */
  /* SKIP geog_in: needs spatial_ref_sys CSV */
  /* SKIP geom_from_hexewkb: unmapped arg type 'char *' */
  /* SKIP geom_in: unmapped arg type 'char *' */
  { BOX3D * r = box3d_make(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0);
    printf("box3d_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP box3d_out: unmapped arg type 'BOX3D *' */
  { GBOX * r = gbox_make(true, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0);
    printf("gbox_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP gbox_out: unmapped arg type 'GBOX *' */
  { GSERIALIZED * r = geo_copy(geom1);
    printf("geo_copy: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geogpoint_make2d: needs spatial_ref_sys CSV */
  /* SKIP geogpoint_make3dz: needs spatial_ref_sys CSV */
  { GSERIALIZED * r = geompoint_make2d(0, 1.0, 1.0);
    printf("geompoint_make2d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geompoint_make3dz(0, 1.0, 1.0, 1.0);
    printf("geompoint_make3dz: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geom_to_geog: needs spatial_ref_sys CSV */
  /* SKIP geog_to_geom: needs spatial_ref_sys CSV */
  { bool r = geo_is_empty(geom1);
    printf("geo_is_empty: %d\n", (int) r); }
  { bool r = geo_is_unitary(geom1);
    printf("geo_is_unitary: %d\n", (int) r); }
  /* SKIP geo_typename: returns static string; free() is invalid */
  /* SKIP geog_area: needs spatial_ref_sys CSV */
  /* SKIP geog_centroid: needs spatial_ref_sys CSV */
  /* SKIP geog_length: needs spatial_ref_sys CSV */
  /* SKIP geog_perimeter: needs spatial_ref_sys CSV */
  /* SKIP geom_azimuth: unmapped arg type 'double *' */
  { double r = geom_length(geom1);
    printf("geom_length: %.6f\n", r); }
  { double r = geom_perimeter(geom1);
    printf("geom_perimeter: %.6f\n", r); }
  { int r = line_numpoints(geom1);
    printf("line_numpoints: %d\n", r); }
  { GSERIALIZED * r = line_point_n(geom1, 1);
    printf("line_point_n: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geo_reverse(geom1);
    printf("geo_reverse: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geo_round(geom1, 1);
    printf("geo_round: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geo_set_srid(geom1, 0);
    printf("geo_set_srid: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geo_srid: unmapped return type 'int32_t' */
  { GSERIALIZED * r = geo_transform(geom1, 0);
    printf("geo_transform: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geo_transform_pipeline: unmapped arg type 'char *' */
  /* SKIP geo_collect_garray: unmapped arg type 'GSERIALIZED * *' */
  /* SKIP geo_makeline_garray: unmapped arg type 'GSERIALIZED * *' */
  { int r = geo_num_points(geom1);
    printf("geo_num_points: %d\n", r); }
  { int r = geo_num_geos(geom1);
    printf("geo_num_geos: %d\n", r); }
  { GSERIALIZED * r = geo_geo_n(geom1, 1);
    printf("geo_geo_n: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * * r = geo_pointarr(geom1, &n_out);
    printf("geo_pointarr: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { GSERIALIZED * r = geo_points(geom1);
    printf("geo_points: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geom_array_union: unmapped arg type 'GSERIALIZED * *' */
  { GSERIALIZED * r = geom_boundary(geom1);
    printf("geom_boundary: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geom_buffer: unmapped arg type 'char *' */
  { GSERIALIZED * r = geom_centroid(geom1);
    printf("geom_centroid: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geom_convex_hull(geom1);
    printf("geom_convex_hull: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geom_difference2d(geom1, geom1);
    printf("geom_difference2d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geom_intersection2d(geom1, geom1);
    printf("geom_intersection2d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geom_intersection2d_coll(geom1, geom1);
    printf("geom_intersection2d_coll: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geom_min_bounding_radius: unmapped arg type 'double *' */
  { GSERIALIZED * r = geom_shortestline2d(geom1, geom1);
    printf("geom_shortestline2d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geom_shortestline3d(geom1, geom1);
    printf("geom_shortestline3d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geom_unary_union(geom1, 1.0);
    printf("geom_unary_union: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = line_interpolate_point(geom1, 1.0, true);
    printf("line_interpolate_point: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = line_locate_point(geom1, geom1);
    printf("line_locate_point: %.6f\n", r); }
  { GSERIALIZED * r = line_substring(geom1, 1.0, 1.0);
    printf("line_substring: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geog_dwithin: needs spatial_ref_sys CSV */
  /* SKIP geog_intersects: needs spatial_ref_sys CSV */
  { bool r = geom_contains(geom1, geom1);
    printf("geom_contains: %d\n", (int) r); }
  { bool r = geom_covers(geom1, geom1);
    printf("geom_covers: %d\n", (int) r); }
  { bool r = geom_disjoint2d(geom1, geom1);
    printf("geom_disjoint2d: %d\n", (int) r); }
  { bool r = geom_dwithin2d(geom1, geom1, 1.0);
    printf("geom_dwithin2d: %d\n", (int) r); }
  { bool r = geom_dwithin3d(geom1, geom1, 1.0);
    printf("geom_dwithin3d: %d\n", (int) r); }
  { bool r = geom_intersects2d(geom1, geom1);
    printf("geom_intersects2d: %d\n", (int) r); }
  { bool r = geom_intersects3d(geom1, geom1);
    printf("geom_intersects3d: %d\n", (int) r); }
  /* SKIP geom_relate_pattern: unmapped arg type 'char *' */
  { bool r = geom_touches(geom1, geom1);
    printf("geom_touches: %d\n", (int) r); }
  { STBox * r = geo_stboxes(geom1, &n_out);
    printf("geo_stboxes: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = geo_split_each_n_stboxes(geom1, 1, &n_out);
    printf("geo_split_each_n_stboxes: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = geo_split_n_stboxes(geom1, 1, &n_out);
    printf("geo_split_n_stboxes: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geog_distance: needs spatial_ref_sys CSV */
  { double r = geom_distance2d(geom1, geom1);
    printf("geom_distance2d: %.6f\n", r); }
  { double r = geom_distance3d(geom1, geom1);
    printf("geom_distance3d: %.6f\n", r); }
  { int r = geo_equals(geom1, geom1);
    printf("geo_equals: %d\n", r); }
  { bool r = geo_same(geom1, geom1);
    printf("geo_same: %d\n", (int) r); }
  /* SKIP geogset_in: needs spatial_ref_sys CSV */
  /* SKIP geomset_in: unmapped arg type 'char *' */
  { char *r = spatialset_as_text(geomset1, 1);
    printf("spatialset_as_text: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { char *r = spatialset_as_ewkt(geomset1, 1);
    printf("spatialset_as_ewkt: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP geoset_make: unmapped arg type 'GSERIALIZED * *' */
  { Set * r = geo_to_set(geom1);
    printf("geo_to_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geoset_end_value(geomset1);
    printf("geoset_end_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = geoset_start_value(geomset1);
    printf("geoset_start_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP geoset_value_n: unmapped arg type 'GSERIALIZED * *' */
  { GSERIALIZED * * r = geoset_values(geomset1);
    printf("geoset_values: %s\n", r ? "OK" : "NULL");
    if (r) {
      int _n = set_num_values(geomset1);
      for (int _i = 0; _i < _n; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { bool r = contained_geo_set(geom1, geomset1);
    printf("contained_geo_set: %d\n", (int) r); }
  { bool r = contains_set_geo(geomset1, geom1);
    printf("contains_set_geo: %d\n", (int) r); }
  /* SKIP geo_union_transfn: aggregate state-handoff pattern incompatible with smoke-test ownership model */
  { Set * r = intersection_geo_set(geom1, geomset1);
    printf("intersection_geo_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = intersection_set_geo(geomset1, geom1);
    printf("intersection_set_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = minus_geo_set(geom1, geomset1);
    printf("minus_geo_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = minus_set_geo(geomset1, geom1);
    printf("minus_set_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = union_geo_set(geom1, geomset1);
    printf("union_geo_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = union_set_geo(geomset1, geom1);
    printf("union_set_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = spatialset_set_srid(geomset1, 0);
    printf("spatialset_set_srid: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP spatialset_srid: unmapped return type 'int32_t' */
  { Set * r = spatialset_transform(geomset1, 0);
    printf("spatialset_transform: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP spatialset_transform_pipeline: unmapped arg type 'char *' */
  { char *r = stbox_as_hexwkb(stbox1, 1, &size_out);
    printf("stbox_as_hexwkb: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { uint8_t * r = stbox_as_wkb(stbox1, 1, &size_out);
    printf("stbox_as_wkb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP stbox_from_hexwkb: unmapped arg type 'char *' */
  /* SKIP stbox_from_wkb: unmapped arg type 'uint8_t *' */
  /* SKIP stbox_in: unmapped arg type 'char *' */
  { char *r = stbox_out(stbox1, 1);
    printf("stbox_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { STBox * r = geo_timestamptz_to_stbox(geom1, tstz1);
    printf("geo_timestamptz_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = geo_tstzspan_to_stbox(geom1, tstzspan1);
    printf("geo_tstzspan_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = stbox_copy(stbox1);
    printf("stbox_copy: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = stbox_make(true, true, true, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, tstzspan1);
    printf("stbox_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = geo_to_stbox(geom1);
    printf("geo_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = spatialset_to_stbox(geomset1);
    printf("spatialset_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { BOX3D * r = stbox_to_box3d(stbox1);
    printf("stbox_to_box3d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GBOX * r = stbox_to_gbox(stbox1);
    printf("stbox_to_gbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = stbox_to_geo(stbox1);
    printf("stbox_to_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Span * r = stbox_to_tstzspan(stbox1);
    printf("stbox_to_tstzspan: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = timestamptz_to_stbox(tstz1);
    printf("timestamptz_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = tstzset_to_stbox(geomset1);
    printf("tstzset_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = tstzspan_to_stbox(tstzspan1);
    printf("tstzspan_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = tstzspanset_to_stbox(tstzspanset1);
    printf("tstzspanset_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = stbox_area(stbox1, true);
    printf("stbox_area: %.6f\n", r); }
  /* SKIP stbox_hash: unmapped return type 'uint32' */
  /* SKIP stbox_hash_extended: unmapped arg type 'uint64' */
  { bool r = stbox_hast(stbox1);
    printf("stbox_hast: %d\n", (int) r); }
  { bool r = stbox_hasx(stbox1);
    printf("stbox_hasx: %d\n", (int) r); }
  { bool r = stbox_hasz(stbox1);
    printf("stbox_hasz: %d\n", (int) r); }
  { bool r = stbox_isgeodetic(stbox1);
    printf("stbox_isgeodetic: %d\n", (int) r); }
  { double r = stbox_perimeter(stbox1, true);
    printf("stbox_perimeter: %.6f\n", r); }
  { bool r = stbox_tmax(stbox1, &tstz1);
    printf("stbox_tmax: %d\n", (int) r); }
  { bool r = stbox_tmax_inc(stbox1, &bool_out);
    printf("stbox_tmax_inc: %d\n", (int) r); }
  { bool r = stbox_tmin(stbox1, &tstz1);
    printf("stbox_tmin: %d\n", (int) r); }
  { bool r = stbox_tmin_inc(stbox1, &bool_out);
    printf("stbox_tmin_inc: %d\n", (int) r); }
  { double r = stbox_volume(stbox1);
    printf("stbox_volume: %.6f\n", r); }
  /* SKIP stbox_xmax: unmapped arg type 'double *' */
  /* SKIP stbox_xmin: unmapped arg type 'double *' */
  /* SKIP stbox_ymax: unmapped arg type 'double *' */
  /* SKIP stbox_ymin: unmapped arg type 'double *' */
  /* SKIP stbox_zmax: unmapped arg type 'double *' */
  /* SKIP stbox_zmin: unmapped arg type 'double *' */
  { STBox * r = stbox_expand_space(stbox1, 1.0);
    printf("stbox_expand_space: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = stbox_expand_time(stbox1, interv1);
    printf("stbox_expand_time: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = stbox_get_space(stbox1);
    printf("stbox_get_space: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = stbox_quad_split(stbox1, &n_out);
    printf("stbox_quad_split: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = stbox_round(stbox1, 1);
    printf("stbox_round: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = stbox_shift_scale_time(stbox1, interv1, interv1);
    printf("stbox_shift_scale_time: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = stboxarr_round(stbox1, 1, 1);
    printf("stboxarr_round: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = stbox_set_srid(stbox1, 0);
    printf("stbox_set_srid: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP stbox_srid: unmapped return type 'int32_t' */
  { STBox * r = stbox_transform(stbox1, 0);
    printf("stbox_transform: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP stbox_transform_pipeline: unmapped arg type 'char *' */
  { bool r = adjacent_stbox_stbox(stbox1, stbox1);
    printf("adjacent_stbox_stbox: %d\n", (int) r); }
  { bool r = contained_stbox_stbox(stbox1, stbox1);
    printf("contained_stbox_stbox: %d\n", (int) r); }
  { bool r = contains_stbox_stbox(stbox1, stbox1);
    printf("contains_stbox_stbox: %d\n", (int) r); }
  { bool r = overlaps_stbox_stbox(stbox1, stbox1);
    printf("overlaps_stbox_stbox: %d\n", (int) r); }
  { bool r = same_stbox_stbox(stbox1, stbox1);
    printf("same_stbox_stbox: %d\n", (int) r); }
  { bool r = above_stbox_stbox(stbox1, stbox1);
    printf("above_stbox_stbox: %d\n", (int) r); }
  { bool r = after_stbox_stbox(stbox1, stbox1);
    printf("after_stbox_stbox: %d\n", (int) r); }
  { bool r = back_stbox_stbox(stbox1, stbox1);
    printf("back_stbox_stbox: %d\n", (int) r); }
  { bool r = before_stbox_stbox(stbox1, stbox1);
    printf("before_stbox_stbox: %d\n", (int) r); }
  { bool r = below_stbox_stbox(stbox1, stbox1);
    printf("below_stbox_stbox: %d\n", (int) r); }
  { bool r = front_stbox_stbox(stbox1, stbox1);
    printf("front_stbox_stbox: %d\n", (int) r); }
  { bool r = left_stbox_stbox(stbox1, stbox1);
    printf("left_stbox_stbox: %d\n", (int) r); }
  { bool r = overabove_stbox_stbox(stbox1, stbox1);
    printf("overabove_stbox_stbox: %d\n", (int) r); }
  { bool r = overafter_stbox_stbox(stbox1, stbox1);
    printf("overafter_stbox_stbox: %d\n", (int) r); }
  { bool r = overback_stbox_stbox(stbox1, stbox1);
    printf("overback_stbox_stbox: %d\n", (int) r); }
  { bool r = overbefore_stbox_stbox(stbox1, stbox1);
    printf("overbefore_stbox_stbox: %d\n", (int) r); }
  { bool r = overbelow_stbox_stbox(stbox1, stbox1);
    printf("overbelow_stbox_stbox: %d\n", (int) r); }
  { bool r = overfront_stbox_stbox(stbox1, stbox1);
    printf("overfront_stbox_stbox: %d\n", (int) r); }
  { bool r = overleft_stbox_stbox(stbox1, stbox1);
    printf("overleft_stbox_stbox: %d\n", (int) r); }
  { bool r = overright_stbox_stbox(stbox1, stbox1);
    printf("overright_stbox_stbox: %d\n", (int) r); }
  { bool r = right_stbox_stbox(stbox1, stbox1);
    printf("right_stbox_stbox: %d\n", (int) r); }
  { STBox * r = union_stbox_stbox(stbox1, stbox1, true);
    printf("union_stbox_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = intersection_stbox_stbox(stbox1, stbox1);
    printf("intersection_stbox_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { int r = stbox_cmp(stbox1, stbox1);
    printf("stbox_cmp: %d\n", r); }
  { bool r = stbox_eq(stbox1, stbox1);
    printf("stbox_eq: %d\n", (int) r); }
  { bool r = stbox_ge(stbox1, stbox1);
    printf("stbox_ge: %d\n", (int) r); }
  { bool r = stbox_gt(stbox1, stbox1);
    printf("stbox_gt: %d\n", (int) r); }
  { bool r = stbox_le(stbox1, stbox1);
    printf("stbox_le: %d\n", (int) r); }
  { bool r = stbox_lt(stbox1, stbox1);
    printf("stbox_lt: %d\n", (int) r); }
  { bool r = stbox_ne(stbox1, stbox1);
    printf("stbox_ne: %d\n", (int) r); }
  /* SKIP tgeogpoint_from_mfjson: unmapped arg type 'char *' */
  /* SKIP tgeogpoint_in: unmapped arg type 'char *' */
  /* SKIP tgeography_from_mfjson: unmapped arg type 'char *' */
  /* SKIP tgeography_in: unmapped arg type 'char *' */
  /* SKIP tgeometry_from_mfjson: unmapped arg type 'char *' */
  /* SKIP tgeometry_in: unmapped arg type 'char *' */
  /* SKIP tgeompoint_from_mfjson: unmapped arg type 'char *' */
  /* SKIP tgeompoint_in: unmapped arg type 'char *' */
  { char *r = tspatial_as_ewkt(tgeo1, 1);
    printf("tspatial_as_ewkt: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { char *r = tspatial_as_text(tgeo1, 1);
    printf("tspatial_as_text: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { char *r = tspatial_out(tgeo1, 1);
    printf("tspatial_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeo_from_base_temp(geom1, tgeo1);
    printf("tgeo_from_base_temp: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = tgeoinst_make(geom1, tstz1);
    printf("tgeoinst_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tgeoseq_from_base_tstzset: needs STEP interp on multi-span input */
  /* SKIP tgeoseq_from_base_tstzspan: needs STEP interp on multi-span input */
  /* SKIP tgeoseqset_from_base_tstzspanset: needs STEP interp on multi-span input */
  /* SKIP tpoint_from_base_temp: needs hand-constructed Temporal input */
  { TInstant * r = tpointinst_make(geom1, tstz1);
    printf("tpointinst_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * r = tpointseq_from_base_tstzset(geom1, geomset1);
    printf("tpointseq_from_base_tstzset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * r = tpointseq_from_base_tstzspan(geom1, tstzspan1, LINEAR);
    printf("tpointseq_from_base_tstzspan: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tpointseq_make_coords: unmapped arg type 'double *' */
  { TSequenceSet * r = tpointseqset_from_base_tstzspanset(geom1, tstzspanset1, LINEAR);
    printf("tpointseqset_from_base_tstzspanset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP box3d_to_stbox: unmapped arg type 'BOX3D *' */
  /* SKIP gbox_to_stbox: unmapped arg type 'GBOX *' */
  { Temporal * r = geomeas_to_tpoint(geom1);
    printf("geomeas_to_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeogpoint_to_tgeography(tgeo1);
    printf("tgeogpoint_to_tgeography: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeography_to_tgeogpoint(tgeo1);
    printf("tgeography_to_tgeogpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeography_to_tgeometry(tgeo1);
    printf("tgeography_to_tgeometry: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeometry_to_tgeography(tgeo1);
    printf("tgeometry_to_tgeography: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeometry_to_tgeompoint(tgeo1);
    printf("tgeometry_to_tgeompoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeompoint_to_tgeometry(tgeo1);
    printf("tgeompoint_to_tgeometry: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tpoint_as_mvtgeom: unmapped arg type 'GSERIALIZED * *' */
  /* SKIP tpoint_tfloat_to_geomeas: unmapped arg type 'GSERIALIZED * *' */
  { STBox * r = tspatial_to_stbox(tgeo1);
    printf("tspatial_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP bearing_point_point: unmapped arg type 'double *' */
  { Temporal * r = bearing_tpoint_point(tgeo1, geom1, true);
    printf("bearing_tpoint_point: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = bearing_tpoint_tpoint(tgeo1, tgeo1);
    printf("bearing_tpoint_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeo_centroid(tgeo1);
    printf("tgeo_centroid: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = tgeo_convex_hull(tgeo1);
    printf("tgeo_convex_hull: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = tgeo_end_value(tgeo1);
    printf("tgeo_end_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = tgeo_start_value(tgeo1);
    printf("tgeo_start_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = tgeo_traversed_area(tgeo1, true);
    printf("tgeo_traversed_area: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tgeo_value_at_timestamptz: unmapped arg type 'GSERIALIZED * *' */
  /* SKIP tgeo_value_n: unmapped arg type 'GSERIALIZED * *' */
  { GSERIALIZED * * r = tgeo_values(tgeo1, &n_out);
    printf("tgeo_values: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { Temporal * r = tpoint_angular_difference(tgeo1);
    printf("tpoint_angular_difference: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_azimuth(tgeo1);
    printf("tpoint_azimuth: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_cumulative_length(tgeo1);
    printf("tpoint_cumulative_length: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tpoint_direction: unmapped arg type 'double *' */
  { Temporal * r = tpoint_get_x(tgeo1);
    printf("tpoint_get_x: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_get_y(tgeo1);
    printf("tpoint_get_y: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_get_z(tgeo1);
    printf("tpoint_get_z: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { bool r = tpoint_is_simple(tgeo1);
    printf("tpoint_is_simple: %d\n", (int) r); }
  { double r = tpoint_length(tgeo1);
    printf("tpoint_length: %.6f\n", r); }
  { Temporal * r = tpoint_speed(tgeo1);
    printf("tpoint_speed: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = tpoint_trajectory(tgeo1, true);
    printf("tpoint_trajectory: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = tpoint_twcentroid(tgeo1);
    printf("tpoint_twcentroid: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tgeo_affine: unmapped arg type 'AFFINE *' */
  { Temporal * r = tgeo_scale(tgeo1, geom1, geom1);
    printf("tgeo_scale: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * * r = tpoint_make_simple(tgeo1, &n_out);
    printf("tpoint_make_simple: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { Temporal * r = tspatial_set_srid(tgeo1, 0);
    printf("tspatial_set_srid: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tspatial_transform(tgeo1, 0);
    printf("tspatial_transform: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tspatial_transform_pipeline: unmapped arg type 'char *' */
  { Temporal * r = tgeo_at_geom(tgeo1, geom1);
    printf("tgeo_at_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeo_at_stbox(tgeo1, stbox1, true);
    printf("tgeo_at_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeo_at_value(tgeo1, geom1);
    printf("tgeo_at_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeo_minus_geom(tgeo1, geom1);
    printf("tgeo_minus_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeo_minus_stbox(tgeo1, stbox1, true);
    printf("tgeo_minus_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeo_minus_value(tgeo1, geom1);
    printf("tgeo_minus_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_at_elevation(tgeo1, tstzspan1);
    printf("tpoint_at_elevation: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_at_geom(tgeo1, geom1);
    printf("tpoint_at_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_at_value(tgeo1, geom1);
    printf("tpoint_at_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_minus_elevation(tgeo1, tstzspan1);
    printf("tpoint_minus_elevation: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_minus_geom(tgeo1, geom1);
    printf("tpoint_minus_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpoint_minus_value(tgeo1, geom1);
    printf("tpoint_minus_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { int r = always_eq_geo_tgeo(geom1, tgeo1);
    printf("always_eq_geo_tgeo: %d\n", r); }
  { int r = always_eq_tgeo_geo(tgeo1, geom1);
    printf("always_eq_tgeo_geo: %d\n", r); }
  { int r = always_eq_tgeo_tgeo(tgeo1, tgeo1);
    printf("always_eq_tgeo_tgeo: %d\n", r); }
  { int r = always_ne_geo_tgeo(geom1, tgeo1);
    printf("always_ne_geo_tgeo: %d\n", r); }
  { int r = always_ne_tgeo_geo(tgeo1, geom1);
    printf("always_ne_tgeo_geo: %d\n", r); }
  { int r = always_ne_tgeo_tgeo(tgeo1, tgeo1);
    printf("always_ne_tgeo_tgeo: %d\n", r); }
  { int r = ever_eq_geo_tgeo(geom1, tgeo1);
    printf("ever_eq_geo_tgeo: %d\n", r); }
  { int r = ever_eq_tgeo_geo(tgeo1, geom1);
    printf("ever_eq_tgeo_geo: %d\n", r); }
  { int r = ever_eq_tgeo_tgeo(tgeo1, tgeo1);
    printf("ever_eq_tgeo_tgeo: %d\n", r); }
  { int r = ever_ne_geo_tgeo(geom1, tgeo1);
    printf("ever_ne_geo_tgeo: %d\n", r); }
  { int r = ever_ne_tgeo_geo(tgeo1, geom1);
    printf("ever_ne_tgeo_geo: %d\n", r); }
  { int r = ever_ne_tgeo_tgeo(tgeo1, tgeo1);
    printf("ever_ne_tgeo_tgeo: %d\n", r); }
  { Temporal * r = teq_geo_tgeo(geom1, tgeo1);
    printf("teq_geo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = teq_tgeo_geo(tgeo1, geom1);
    printf("teq_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_geo_tgeo(geom1, tgeo1);
    printf("tne_geo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_tgeo_geo(tgeo1, geom1);
    printf("tne_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = tgeo_stboxes(tgeo1, &n_out);
    printf("tgeo_stboxes: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = tgeo_space_boxes(tgeo1, 1.0, 1.0, 1.0, geom1, true, true, &n_out);
    printf("tgeo_space_boxes: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = tgeo_space_time_boxes(tgeo1, 1.0, 1.0, 1.0, interv1, geom1, tstz1, true, true, &n_out);
    printf("tgeo_space_time_boxes: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = tgeo_split_each_n_stboxes(tgeo1, 1, &n_out);
    printf("tgeo_split_each_n_stboxes: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = tgeo_split_n_stboxes(tgeo1, 1, &n_out);
    printf("tgeo_split_n_stboxes: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { bool r = adjacent_stbox_tspatial(stbox1, tgeo1);
    printf("adjacent_stbox_tspatial: %d\n", (int) r); }
  { bool r = adjacent_tspatial_stbox(tgeo1, stbox1);
    printf("adjacent_tspatial_stbox: %d\n", (int) r); }
  { bool r = adjacent_tspatial_tspatial(tgeo1, tgeo1);
    printf("adjacent_tspatial_tspatial: %d\n", (int) r); }
  { bool r = contained_stbox_tspatial(stbox1, tgeo1);
    printf("contained_stbox_tspatial: %d\n", (int) r); }
  { bool r = contained_tspatial_stbox(tgeo1, stbox1);
    printf("contained_tspatial_stbox: %d\n", (int) r); }
  { bool r = contained_tspatial_tspatial(tgeo1, tgeo1);
    printf("contained_tspatial_tspatial: %d\n", (int) r); }
  { bool r = contains_stbox_tspatial(stbox1, tgeo1);
    printf("contains_stbox_tspatial: %d\n", (int) r); }
  { bool r = contains_tspatial_stbox(tgeo1, stbox1);
    printf("contains_tspatial_stbox: %d\n", (int) r); }
  { bool r = contains_tspatial_tspatial(tgeo1, tgeo1);
    printf("contains_tspatial_tspatial: %d\n", (int) r); }
  { bool r = overlaps_stbox_tspatial(stbox1, tgeo1);
    printf("overlaps_stbox_tspatial: %d\n", (int) r); }
  { bool r = overlaps_tspatial_stbox(tgeo1, stbox1);
    printf("overlaps_tspatial_stbox: %d\n", (int) r); }
  { bool r = overlaps_tspatial_tspatial(tgeo1, tgeo1);
    printf("overlaps_tspatial_tspatial: %d\n", (int) r); }
  { bool r = same_stbox_tspatial(stbox1, tgeo1);
    printf("same_stbox_tspatial: %d\n", (int) r); }
  { bool r = same_tspatial_stbox(tgeo1, stbox1);
    printf("same_tspatial_stbox: %d\n", (int) r); }
  { bool r = same_tspatial_tspatial(tgeo1, tgeo1);
    printf("same_tspatial_tspatial: %d\n", (int) r); }
  { bool r = above_stbox_tspatial(stbox1, tgeo1);
    printf("above_stbox_tspatial: %d\n", (int) r); }
  { bool r = above_tspatial_stbox(tgeo1, stbox1);
    printf("above_tspatial_stbox: %d\n", (int) r); }
  { bool r = above_tspatial_tspatial(tgeo1, tgeo1);
    printf("above_tspatial_tspatial: %d\n", (int) r); }
  { bool r = after_stbox_tspatial(stbox1, tgeo1);
    printf("after_stbox_tspatial: %d\n", (int) r); }
  { bool r = after_tspatial_stbox(tgeo1, stbox1);
    printf("after_tspatial_stbox: %d\n", (int) r); }
  { bool r = after_tspatial_tspatial(tgeo1, tgeo1);
    printf("after_tspatial_tspatial: %d\n", (int) r); }
  { bool r = back_stbox_tspatial(stbox1, tgeo1);
    printf("back_stbox_tspatial: %d\n", (int) r); }
  { bool r = back_tspatial_stbox(tgeo1, stbox1);
    printf("back_tspatial_stbox: %d\n", (int) r); }
  { bool r = back_tspatial_tspatial(tgeo1, tgeo1);
    printf("back_tspatial_tspatial: %d\n", (int) r); }
  { bool r = before_stbox_tspatial(stbox1, tgeo1);
    printf("before_stbox_tspatial: %d\n", (int) r); }
  { bool r = before_tspatial_stbox(tgeo1, stbox1);
    printf("before_tspatial_stbox: %d\n", (int) r); }
  { bool r = before_tspatial_tspatial(tgeo1, tgeo1);
    printf("before_tspatial_tspatial: %d\n", (int) r); }
  { bool r = below_stbox_tspatial(stbox1, tgeo1);
    printf("below_stbox_tspatial: %d\n", (int) r); }
  { bool r = below_tspatial_stbox(tgeo1, stbox1);
    printf("below_tspatial_stbox: %d\n", (int) r); }
  { bool r = below_tspatial_tspatial(tgeo1, tgeo1);
    printf("below_tspatial_tspatial: %d\n", (int) r); }
  { bool r = front_stbox_tspatial(stbox1, tgeo1);
    printf("front_stbox_tspatial: %d\n", (int) r); }
  { bool r = front_tspatial_stbox(tgeo1, stbox1);
    printf("front_tspatial_stbox: %d\n", (int) r); }
  { bool r = front_tspatial_tspatial(tgeo1, tgeo1);
    printf("front_tspatial_tspatial: %d\n", (int) r); }
  { bool r = left_stbox_tspatial(stbox1, tgeo1);
    printf("left_stbox_tspatial: %d\n", (int) r); }
  { bool r = left_tspatial_stbox(tgeo1, stbox1);
    printf("left_tspatial_stbox: %d\n", (int) r); }
  { bool r = left_tspatial_tspatial(tgeo1, tgeo1);
    printf("left_tspatial_tspatial: %d\n", (int) r); }
  { bool r = overabove_stbox_tspatial(stbox1, tgeo1);
    printf("overabove_stbox_tspatial: %d\n", (int) r); }
  { bool r = overabove_tspatial_stbox(tgeo1, stbox1);
    printf("overabove_tspatial_stbox: %d\n", (int) r); }
  { bool r = overabove_tspatial_tspatial(tgeo1, tgeo1);
    printf("overabove_tspatial_tspatial: %d\n", (int) r); }
  { bool r = overafter_stbox_tspatial(stbox1, tgeo1);
    printf("overafter_stbox_tspatial: %d\n", (int) r); }
  { bool r = overafter_tspatial_stbox(tgeo1, stbox1);
    printf("overafter_tspatial_stbox: %d\n", (int) r); }
  { bool r = overafter_tspatial_tspatial(tgeo1, tgeo1);
    printf("overafter_tspatial_tspatial: %d\n", (int) r); }
  { bool r = overback_stbox_tspatial(stbox1, tgeo1);
    printf("overback_stbox_tspatial: %d\n", (int) r); }
  { bool r = overback_tspatial_stbox(tgeo1, stbox1);
    printf("overback_tspatial_stbox: %d\n", (int) r); }
  { bool r = overback_tspatial_tspatial(tgeo1, tgeo1);
    printf("overback_tspatial_tspatial: %d\n", (int) r); }
  { bool r = overbefore_stbox_tspatial(stbox1, tgeo1);
    printf("overbefore_stbox_tspatial: %d\n", (int) r); }
  { bool r = overbefore_tspatial_stbox(tgeo1, stbox1);
    printf("overbefore_tspatial_stbox: %d\n", (int) r); }
  { bool r = overbefore_tspatial_tspatial(tgeo1, tgeo1);
    printf("overbefore_tspatial_tspatial: %d\n", (int) r); }
  { bool r = overbelow_stbox_tspatial(stbox1, tgeo1);
    printf("overbelow_stbox_tspatial: %d\n", (int) r); }
  { bool r = overbelow_tspatial_stbox(tgeo1, stbox1);
    printf("overbelow_tspatial_stbox: %d\n", (int) r); }
  { bool r = overbelow_tspatial_tspatial(tgeo1, tgeo1);
    printf("overbelow_tspatial_tspatial: %d\n", (int) r); }
  { bool r = overfront_stbox_tspatial(stbox1, tgeo1);
    printf("overfront_stbox_tspatial: %d\n", (int) r); }
  { bool r = overfront_tspatial_stbox(tgeo1, stbox1);
    printf("overfront_tspatial_stbox: %d\n", (int) r); }
  { bool r = overfront_tspatial_tspatial(tgeo1, tgeo1);
    printf("overfront_tspatial_tspatial: %d\n", (int) r); }
  { bool r = overleft_stbox_tspatial(stbox1, tgeo1);
    printf("overleft_stbox_tspatial: %d\n", (int) r); }
  { bool r = overleft_tspatial_stbox(tgeo1, stbox1);
    printf("overleft_tspatial_stbox: %d\n", (int) r); }
  { bool r = overleft_tspatial_tspatial(tgeo1, tgeo1);
    printf("overleft_tspatial_tspatial: %d\n", (int) r); }
  { bool r = overright_stbox_tspatial(stbox1, tgeo1);
    printf("overright_stbox_tspatial: %d\n", (int) r); }
  { bool r = overright_tspatial_stbox(tgeo1, stbox1);
    printf("overright_tspatial_stbox: %d\n", (int) r); }
  { bool r = overright_tspatial_tspatial(tgeo1, tgeo1);
    printf("overright_tspatial_tspatial: %d\n", (int) r); }
  { bool r = right_stbox_tspatial(stbox1, tgeo1);
    printf("right_stbox_tspatial: %d\n", (int) r); }
  { bool r = right_tspatial_stbox(tgeo1, stbox1);
    printf("right_tspatial_stbox: %d\n", (int) r); }
  { bool r = right_tspatial_tspatial(tgeo1, tgeo1);
    printf("right_tspatial_tspatial: %d\n", (int) r); }
  { int r = acontains_geo_tgeo(geom1, tgeo1);
    printf("acontains_geo_tgeo: %d\n", r); }
  { int r = acontains_tgeo_geo(tgeo1, geom1);
    printf("acontains_tgeo_geo: %d\n", r); }
  { int r = acontains_tgeo_tgeo(tgeo1, tgeo1);
    printf("acontains_tgeo_tgeo: %d\n", r); }
  { int r = adisjoint_tgeo_geo(tgeo1, geom1);
    printf("adisjoint_tgeo_geo: %d\n", r); }
  { int r = adisjoint_tgeo_tgeo(tgeo1, tgeo1);
    printf("adisjoint_tgeo_tgeo: %d\n", r); }
  { int r = adwithin_tgeo_geo(tgeo1, geom1, 1.0);
    printf("adwithin_tgeo_geo: %d\n", r); }
  { int r = adwithin_tgeo_tgeo(tgeo1, tgeo1, 1.0);
    printf("adwithin_tgeo_tgeo: %d\n", r); }
  { int r = aintersects_tgeo_geo(tgeo1, geom1);
    printf("aintersects_tgeo_geo: %d\n", r); }
  { int r = aintersects_tgeo_tgeo(tgeo1, tgeo1);
    printf("aintersects_tgeo_tgeo: %d\n", r); }
  { int r = atouches_tgeo_geo(tgeo1, geom1);
    printf("atouches_tgeo_geo: %d\n", r); }
  { int r = atouches_tgeo_tgeo(tgeo1, tgeo1);
    printf("atouches_tgeo_tgeo: %d\n", r); }
  { int r = atouches_tpoint_geo(tgeo1, geom1);
    printf("atouches_tpoint_geo: %d\n", r); }
  { int r = econtains_geo_tgeo(geom1, tgeo1);
    printf("econtains_geo_tgeo: %d\n", r); }
  { int r = econtains_tgeo_geo(tgeo1, geom1);
    printf("econtains_tgeo_geo: %d\n", r); }
  { int r = econtains_tgeo_tgeo(tgeo1, tgeo1);
    printf("econtains_tgeo_tgeo: %d\n", r); }
  { int r = ecovers_geo_tgeo(geom1, tgeo1);
    printf("ecovers_geo_tgeo: %d\n", r); }
  { int r = ecovers_tgeo_geo(tgeo1, geom1);
    printf("ecovers_tgeo_geo: %d\n", r); }
  { int r = ecovers_tgeo_tgeo(tgeo1, tgeo1);
    printf("ecovers_tgeo_tgeo: %d\n", r); }
  { int r = edisjoint_tgeo_geo(tgeo1, geom1);
    printf("edisjoint_tgeo_geo: %d\n", r); }
  { int r = edisjoint_tgeo_tgeo(tgeo1, tgeo1);
    printf("edisjoint_tgeo_tgeo: %d\n", r); }
  { int r = edwithin_tgeo_geo(tgeo1, geom1, 1.0);
    printf("edwithin_tgeo_geo: %d\n", r); }
  { int r = edwithin_tgeo_tgeo(tgeo1, tgeo1, 1.0);
    printf("edwithin_tgeo_tgeo: %d\n", r); }
  { int r = eintersects_tgeo_geo(tgeo1, geom1);
    printf("eintersects_tgeo_geo: %d\n", r); }
  { int r = eintersects_tgeo_tgeo(tgeo1, tgeo1);
    printf("eintersects_tgeo_tgeo: %d\n", r); }
  { int r = etouches_tgeo_geo(tgeo1, geom1);
    printf("etouches_tgeo_geo: %d\n", r); }
  { int r = etouches_tgeo_tgeo(tgeo1, tgeo1);
    printf("etouches_tgeo_tgeo: %d\n", r); }
  { int r = etouches_tpoint_geo(tgeo1, geom1);
    printf("etouches_tpoint_geo: %d\n", r); }
  { Temporal * r = tcontains_geo_tgeo(geom1, tgeo1);
    printf("tcontains_geo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcontains_tgeo_geo(tgeo1, geom1);
    printf("tcontains_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcontains_tgeo_tgeo(tgeo1, tgeo1);
    printf("tcontains_tgeo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcovers_geo_tgeo(geom1, tgeo1);
    printf("tcovers_geo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcovers_tgeo_geo(tgeo1, geom1);
    printf("tcovers_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tcovers_tgeo_tgeo(tgeo1, tgeo1);
    printf("tcovers_tgeo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdisjoint_geo_tgeo(geom1, tgeo1);
    printf("tdisjoint_geo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdisjoint_tgeo_geo(tgeo1, geom1);
    printf("tdisjoint_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdisjoint_tgeo_tgeo(tgeo1, tgeo1);
    printf("tdisjoint_tgeo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdwithin_geo_tgeo(geom1, tgeo1, 1.0);
    printf("tdwithin_geo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdwithin_tgeo_geo(tgeo1, geom1, 1.0);
    printf("tdwithin_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdwithin_tgeo_tgeo(tgeo1, tgeo1, 1.0);
    printf("tdwithin_tgeo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tintersects_geo_tgeo(geom1, tgeo1);
    printf("tintersects_geo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tintersects_tgeo_geo(tgeo1, geom1);
    printf("tintersects_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tintersects_tgeo_tgeo(tgeo1, tgeo1);
    printf("tintersects_tgeo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = ttouches_geo_tgeo(geom1, tgeo1);
    printf("ttouches_geo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = ttouches_tgeo_geo(tgeo1, geom1);
    printf("ttouches_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = ttouches_tgeo_tgeo(tgeo1, tgeo1);
    printf("ttouches_tgeo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_tgeo_geo(tgeo1, geom1);
    printf("tdistance_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_tgeo_tgeo(tgeo1, tgeo1);
    printf("tdistance_tgeo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = nad_stbox_geo(stbox1, geom1);
    printf("nad_stbox_geo: %.6f\n", r); }
  { double r = nad_stbox_stbox(stbox1, stbox1);
    printf("nad_stbox_stbox: %.6f\n", r); }
  { double r = nad_tgeo_geo(tgeo1, geom1);
    printf("nad_tgeo_geo: %.6f\n", r); }
  { double r = nad_tgeo_stbox(tgeo1, stbox1);
    printf("nad_tgeo_stbox: %.6f\n", r); }
  { double r = nad_tgeo_tgeo(tgeo1, tgeo1);
    printf("nad_tgeo_tgeo: %.6f\n", r); }
  { TInstant * r = nai_tgeo_geo(tgeo1, geom1);
    printf("nai_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = nai_tgeo_tgeo(tgeo1, tgeo1);
    printf("nai_tgeo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_tgeo_geo(tgeo1, geom1);
    printf("shortestline_tgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_tgeo_tgeo(tgeo1, tgeo1);
    printf("shortestline_tgeo_tgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tpoint_tcentroid_finalfn: aggregate state-handoff pattern incompatible with smoke-test ownership model */
  /* SKIP tpoint_tcentroid_transfn: aggregate state-handoff pattern incompatible with smoke-test ownership model */
  /* SKIP tspatial_extent_transfn: aggregate state-handoff pattern incompatible with smoke-test ownership model */
  { STBox * r = stbox_get_space_tile(geom1, 1.0, 1.0, 1.0, geom1);
    printf("stbox_get_space_tile: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP stbox_get_space_time_tile: interv1=NULL triggers assert(xsize>0||duration) */
  /* SKIP stbox_get_time_tile: interv1=NULL triggers assert(xsize>0||duration) */
  { STBox * r = stbox_space_tiles(stbox1, 1.0, 1.0, 1.0, geom1, true, &n_out);
    printf("stbox_space_tiles: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP stbox_space_time_tiles: interv1=NULL triggers assert(xsize>0||duration) */
  /* SKIP stbox_time_tiles: interv1=NULL triggers assert(xsize>0||duration) */
  /* SKIP tgeo_space_split: unmapped arg type 'GSERIALIZED * **' */
  /* SKIP tgeo_space_time_split: unmapped arg type 'GSERIALIZED * **' */
  /* SKIP geo_cluster_kmeans: unmapped arg type 'GSERIALIZED * *' */
  /* SKIP geo_cluster_dbscan: unmapped arg type 'GSERIALIZED * *' */
  /* SKIP geo_cluster_intersecting: unmapped arg type 'GSERIALIZED * *' */
  /* SKIP geo_cluster_within: unmapped arg type 'GSERIALIZED * *' */

  if (tgeo_inst1) free(tgeo_inst1);
  if (tgeo1) free(tgeo1);
  free(stbox1);
  free(geomset1);
  free(geom1);
  free(tstzspanset1);
  free(tstzspan1);

  meos_finalize();
  return 0;
}
