/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief MEOS smoke test for the tjsonb       public API.
 *
 * Auto-generated by meos/test/gen_smoketest.py — do not edit by hand.
 *
 * Each public symbol exported by meos_json.h gets one smoke-test
 * call site here. Arguments come from a shared common-inputs block.
 * Pointer results are freed; a non-fatal MEOS error handler keeps the
 * run going past VALIDATE_* failures so a single bad input doesn't
 * mask the rest of the surface.
 *
 * Run under valgrind to catch leaks/OOB reads:
 *
 *     valgrind --leak-check=full --error-exitcode=1 ./tjsonb_smoketest
 *
 * Build:
 *   gcc -Wall -g -I/usr/local/include -o tjsonb_smoketest \
 *       tjsonb_smoketest.c -L/usr/local/lib -lmeos -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <meos.h>
#include <meos_internal.h>
#include <meos_geo.h>
#include <meos_json.h>
#include <pg_json.h>
#include <pg_text.h>

#ifndef DatumDefined
typedef uintptr_t Datum;
#define DatumDefined 1
#endif

static void
test_error_handler(int level, int code, const char *msg)
{
  (void) level; (void) code;
  fprintf(stderr, "[meos warn] %s\n", msg);
}

int
main(void)
{
  meos_initialize();
  meos_initialize_timezone("UTC");
  meos_initialize_error_handler(test_error_handler);

  TimestampTz tstz1 = timestamptz_in("2001-01-02", -1);
  Span *tstzspan1 = tstzspan_in("[2001-01-01, 2001-01-04]");
  SpanSet *tstzspanset1 = tstzspanset_in("{[2001-01-01, 2001-01-02], [2001-01-03, 2001-01-04]}");
  Interval *interv1 = NULL;
  char *jb1_str = "{\"a\": 1, \"b\": [1, 2, 3]}";
  Jsonb *jb1 = jsonb_in(jb1_str);
  Jsonb *jb_out_param = NULL;
  char *jp_str = "$.a";
  JsonPath *jp1 = jsonpath_in(jp_str);
  char *tjs_seq_str = "[{\"a\": 1}@2001-01-02, {\"a\": 2}@2001-01-03]";
  char *tjs_seqset_str = "{[{\"a\": 1}@2001-01-02], [{\"a\": 2}@2001-01-03]}";
  text *txt1 = text_in("a");
  text *txtarr1[] = { txt1 };
  Numeric num1 = NULL;
  Set *jsonbset1 = jsonbset_in("{1, 2, 3}");
  int n_out = 0;

  Temporal *tjsonb1 = tjsonb_in(
    "[{\"a\": 1}@2001-01-02, {\"a\": 2}@2001-01-03]");
  /* borrowed accessor: points into tjsonb1, no allocation and nothing to free */
  const TInstant *tjsonb_inst1 = temporal_start_inst(tjsonb1);
  TSequence    *tjsonb_tseq1    = (TSequence *) tjsonb1;
  TSequenceSet *tjsonb_tseqset1 = NULL;
  Temporal *ttext1 = ttext_in("[\"1\"@2001-01-02, \"2\"@2001-01-03]");


  printf("****************************************************************\n");
  printf("* tjsonb       MEOS smoke test%*s*\n", 32, "");
  printf("****************************************************************\n");

  { text * r = json_in(jb1_str);
    printf("json_in: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { char *r = json_out(txt1);
    printf("json_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { Jsonb * r = jsonb_from_text(txt1, true);
    printf("jsonb_from_text: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * r = jsonb_in(jb1_str);
    printf("jsonb_in: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { char *r = jsonb_out(jb1);
    printf("jsonb_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP json_make: unmapped arg type 'text * *' */
  /* SKIP json_make_two_arg: unmapped arg type 'text * *' */
  { Jsonb * r = jsonb_copy(jb1);
    printf("jsonb_copy: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP jsonb_make: unmapped arg type 'text * *' */
  /* SKIP jsonb_make_two_arg: unmapped arg type 'text * *' */
  { bool r = jsonb_to_bool(jb1);
    printf("jsonb_to_bool: %d\n", (int) r); }
  { char *r = jsonb_to_cstring(jb1);
    printf("jsonb_to_cstring: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP jsonb_to_float4: unmapped return type 'float4' */
  /* SKIP jsonb_to_float8: unmapped return type 'float8' */
  /* SKIP jsonb_to_int16: unmapped return type 'int16' */
  /* SKIP jsonb_to_int32: unmapped return type 'int32' */
  /* SKIP jsonb_to_int64: unmapped return type 'int64' */
  /* SKIP jsonb_to_numeric: unmapped return type 'Numeric' */
  { text * r = jsonb_to_text(jb1);
    printf("jsonb_to_text: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { text * r = json_array_element(txt1, 1);
    printf("json_array_element: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { text * r = json_array_element_text(txt1, 1);
    printf("json_array_element_text: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { text * * r = json_array_elements(txt1, &n_out);
    printf("json_array_elements: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { text * * r = json_array_elements_text(txt1, &n_out);
    printf("json_array_elements_text: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { int r = json_array_length(txt1);
    printf("json_array_length: %d\n", r); }
  /* SKIP json_each: unmapped arg type 'text * *' */
  /* SKIP json_each_text: unmapped arg type 'text * *' */
  /* SKIP json_extract_path: unmapped arg type 'text * *' */
  /* SKIP json_extract_path_text: unmapped arg type 'text * *' */
  { text * r = json_object_field(txt1, txt1);
    printf("json_object_field: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { text * r = json_object_field_text(txt1, txt1);
    printf("json_object_field_text: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { text * * r = json_object_keys(txt1, &n_out);
    printf("json_object_keys: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { text * r = json_typeof(txt1);
    printf("json_typeof: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * r = jsonb_array_element(jb1, 1);
    printf("jsonb_array_element: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { text * r = jsonb_array_element_text(jb1, 1);
    printf("jsonb_array_element_text: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * * r = jsonb_array_elements(jb1, &n_out);
    printf("jsonb_array_elements: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { text * * r = jsonb_array_elements_text(jb1, &n_out);
    printf("jsonb_array_elements_text: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { int r = jsonb_array_length(jb1);
    printf("jsonb_array_length: %d\n", r); }
  { bool r = jsonb_contained(jb1, jb1);
    printf("jsonb_contained: %d\n", (int) r); }
  { bool r = jsonb_contains(jb1, jb1);
    printf("jsonb_contains: %d\n", (int) r); }
  /* SKIP jsonb_each: unmapped arg type 'Jsonb * *' */
  /* SKIP jsonb_each_text: unmapped arg type 'text * *' */
  { bool r = jsonb_exists(jb1, txt1);
    printf("jsonb_exists: %d\n", (int) r); }
  /* SKIP jsonb_exists_array: unmapped arg type 'text * *' */
  /* SKIP jsonb_extract_path: unmapped arg type 'text * *' */
  /* SKIP jsonb_extract_path_text: unmapped arg type 'text * *' */
  /* SKIP jsonb_hash: unmapped return type 'uint32' */
  /* SKIP jsonb_hash_extended: unmapped return type 'uint64' */
  { Jsonb * r = jsonb_object_field(jb1, txt1);
    printf("jsonb_object_field: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { text * r = jsonb_object_field_text(jb1, txt1);
    printf("jsonb_object_field_text: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { text * * r = jsonb_object_keys(jb1, &n_out);
    printf("jsonb_object_keys: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { text * r = json_strip_nulls(txt1, true);
    printf("json_strip_nulls: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * r = jsonb_concat(jb1, jb1);
    printf("jsonb_concat: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * r = jsonb_delete(jb1, txt1);
    printf("jsonb_delete: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP jsonb_delete_array: unmapped arg type 'text * *' */
  { Jsonb * r = jsonb_delete_index(jb1, 1);
    printf("jsonb_delete_index: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP jsonb_delete_path: unmapped arg type 'text * *' */
  /* SKIP jsonb_insert: unmapped arg type 'text * *' */
  { text * r = jsonb_pretty(jb1);
    printf("jsonb_pretty: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP jsonb_set: unmapped arg type 'text * *' */
  /* SKIP jsonb_set_lax: unmapped arg type 'text * *' */
  { Jsonb * r = jsonb_strip_nulls(jb1, true);
    printf("jsonb_strip_nulls: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { int r = jsonb_cmp(jb1, jb1);
    printf("jsonb_cmp: %d\n", r); }
  { bool r = jsonb_eq(jb1, jb1);
    printf("jsonb_eq: %d\n", (int) r); }
  { bool r = jsonb_ge(jb1, jb1);
    printf("jsonb_ge: %d\n", (int) r); }
  { bool r = jsonb_gt(jb1, jb1);
    printf("jsonb_gt: %d\n", (int) r); }
  { bool r = jsonb_le(jb1, jb1);
    printf("jsonb_le: %d\n", (int) r); }
  { bool r = jsonb_lt(jb1, jb1);
    printf("jsonb_lt: %d\n", (int) r); }
  { bool r = jsonb_ne(jb1, jb1);
    printf("jsonb_ne: %d\n", (int) r); }
  { int r = jsonb_path_exists(jb1, jp1, jb1, true, true);
    printf("jsonb_path_exists: %d\n", r); }
  { bool r = jsonb_path_match(jb1, jp1, jb1, true, true);
    printf("jsonb_path_match: %d\n", (int) r); }
  { Jsonb * * r = jsonb_path_query_all(jb1, jp1, jb1, true, true, &n_out);
    printf("jsonb_path_query_all: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { Jsonb * r = jsonb_path_query_array(jb1, jp1, jb1, true, true);
    printf("jsonb_path_query_array: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * r = jsonb_path_query_first(jb1, jp1, jb1, true, true);
    printf("jsonb_path_query_first: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { JsonPath * r = jsonpath_in(jp_str);
    printf("jsonpath_in: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { JsonPath * r = jsonpath_copy(jp1);
    printf("jsonpath_copy: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { char *r = jsonpath_out(jp1);
    printf("jsonpath_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_in(jb1_str);
    printf("jsonbset_in: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { char *r = jsonbset_out(jsonbset1, 1);
    printf("jsonbset_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP jsonbset_make: unmapped arg type 'Jsonb * *' */
  { Set * r = jsonb_to_set(jb1);
    printf("jsonb_to_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * r = jsonbset_end_value(jsonbset1);
    printf("jsonbset_end_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * r = jsonbset_start_value(jsonbset1);
    printf("jsonbset_start_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP jsonbset_value_n: unmapped arg type 'Jsonb * *' */
  { Jsonb * * r = jsonbset_values(jsonbset1);
    printf("jsonbset_values: %s\n", r ? "OK" : "NULL");
    if (r) {
      int _n = set_num_values(jsonbset1);
      for (int _i = 0; _i < _n; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { Set * r = concat_jsonbset_jsonb(jsonbset1, jb1, true);
    printf("concat_jsonbset_jsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_array_length(jsonbset1);
    printf("jsonbset_array_length: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_object_field(jsonbset1, txt1, true, NULL_RETURN);
    printf("jsonbset_object_field: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_array_element(jsonbset1, 1, true, NULL_RETURN);
    printf("jsonbset_array_element: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_delete_index(jsonbset1, 1);
    printf("jsonbset_delete_index: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_delete(jsonbset1, txt1);
    printf("jsonbset_delete: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP jsonbset_delete_array: unmapped arg type 'text * *' */
  { Set * r = jsonbset_exists(jsonbset1, txt1);
    printf("jsonbset_exists: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP jsonbset_exists_array: unmapped arg type 'text * *' */
  /* SKIP jsonbset_set: unmapped arg type 'text * *' */
  /* SKIP jsonbset_to_alphanumset: unmapped arg type 'MeosType' */
  { Set * r = jsonbset_to_intset(jsonbset1, jb1_str, NULL_RETURN);
    printf("jsonbset_to_intset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_to_floatset(jsonbset1, jb1_str, NULL_RETURN);
    printf("jsonbset_to_floatset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_to_textset_key(jsonbset1, jb1_str, NULL_RETURN);
    printf("jsonbset_to_textset_key: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_strip_nulls(jsonbset1, true);
    printf("jsonbset_strip_nulls: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_pretty(jsonbset1);
    printf("jsonbset_pretty: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP jsonbset_delete_path: unmapped arg type 'text * *' */
  /* SKIP jsonbset_extract_path: unmapped arg type 'text * *' */
  /* SKIP jsonbset_insert: unmapped arg type 'text * *' */
  { Set * r = jsonbset_path_exists(jsonbset1, jp1, jb1, true, true);
    printf("jsonbset_path_exists: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_path_match(jsonbset1, jp1, jb1, true, true);
    printf("jsonbset_path_match: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_path_query_array(jsonbset1, jp1, jb1, true, true);
    printf("jsonbset_path_query_array: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = jsonbset_path_query_first(jsonbset1, jp1, jb1, true, true);
    printf("jsonbset_path_query_first: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { bool r = contained_jsonb_set(jb1, jsonbset1);
    printf("contained_jsonb_set: %d\n", (int) r); }
  { bool r = contains_set_jsonb(jsonbset1, jb1);
    printf("contains_set_jsonb: %d\n", (int) r); }
  { Set * r = intersection_jsonb_set(jb1, jsonbset1);
    printf("intersection_jsonb_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = intersection_set_jsonb(jsonbset1, jb1);
    printf("intersection_set_jsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP jsonb_union_transfn: aggregate state-handoff pattern incompatible with smoke-test ownership model */
  { Set * r = minus_jsonb_set(jb1, jsonbset1);
    printf("minus_jsonb_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = minus_set_jsonb(jsonbset1, jb1);
    printf("minus_set_jsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = union_jsonb_set(jb1, jsonbset1);
    printf("union_jsonb_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = union_set_jsonb(jsonbset1, jb1);
    printf("union_set_jsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_from_mfjson(jb1_str);
    printf("tjsonb_from_mfjson: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_in(jb1_str);
    printf("tjsonb_in: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { char *r = tjsonb_out(tjsonb1);
    printf("tjsonb_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP tjsonbinst_from_mfjson: unmapped arg type 'json_object *' */
  { TInstant * r = tjsonbinst_in(jb1_str);
    printf("tjsonbinst_in: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tjsonbseq_from_mfjson: unmapped arg type 'json_object *' */
  { TSequence * r = tjsonbseq_in(tjs_seq_str, LINEAR);
    printf("tjsonbseq_in: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tjsonbseqset_from_mfjson: unmapped arg type 'json_object *' */
  { TSequenceSet * r = tjsonbseqset_in(tjs_seqset_str);
    printf("tjsonbseqset_in: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_from_base_temp(jb1, tjsonb1);
    printf("tjsonb_from_base_temp: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = tjsonbinst_make(jb1, tstz1);
    printf("tjsonbinst_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * r = tjsonbseq_from_base_tstzset(jb1, jsonbset1);
    printf("tjsonbseq_from_base_tstzset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * r = tjsonbseq_from_base_tstzspan(jb1, tstzspan1);
    printf("tjsonbseq_from_base_tstzspan: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequenceSet * r = tjsonbseqset_from_base_tstzspanset(jb1, tstzspanset1);
    printf("tjsonbseqset_from_base_tstzspanset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_to_ttext(tjsonb1);
    printf("tjsonb_to_ttext: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = ttext_to_tjsonb(ttext1);
    printf("ttext_to_tjsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * r = tjsonb_end_value(tjsonb1);
    printf("tjsonb_end_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Jsonb * r = tjsonb_start_value(tjsonb1);
    printf("tjsonb_start_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tjsonb_value_at_timestamptz: unmapped arg type 'Jsonb * *' */
  /* SKIP tjsonb_value_n: unmapped arg type 'Jsonb * *' */
  { Jsonb * * r = tjsonb_values(tjsonb1, &n_out);
    printf("tjsonb_values: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { Temporal * r = concat_tjsonb_jsonb(tjsonb1, jb1, true);
    printf("concat_tjsonb_jsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = concat_tjsonb_tjsonb(tjsonb1, tjsonb1);
    printf("concat_tjsonb_tjsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = contains_tjsonb_jsonb(tjsonb1, jb1, true);
    printf("contains_tjsonb_jsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = contains_tjsonb_tjsonb(tjsonb1, tjsonb1);
    printf("contains_tjsonb_tjsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP null_handle_type_from_string: unmapped return type 'nullHandleType' */
  { Temporal * r = tjson_array_element(ttext1, 1, NULL_RETURN);
    printf("tjson_array_element: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjson_array_length(ttext1);
    printf("tjson_array_length: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tjson_extract_path: unmapped arg type 'text * *' */
  { Temporal * r = tjson_object_field(ttext1, txt1, true, NULL_RETURN);
    printf("tjson_object_field: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjson_strip_nulls(ttext1, true);
    printf("tjson_strip_nulls: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_array_element(tjsonb1, 1, true, NULL_RETURN);
    printf("tjsonb_array_element: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_array_length(tjsonb1);
    printf("tjsonb_array_length: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_delete(tjsonb1, txt1);
    printf("tjsonb_delete: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tjsonb_delete_array: unmapped arg type 'text * *' */
  { Temporal * r = tjsonb_delete_index(tjsonb1, 1);
    printf("tjsonb_delete_index: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tjsonb_delete_path: unmapped arg type 'text * *' */
  { Temporal * r = tjsonb_exists(tjsonb1, txt1);
    printf("tjsonb_exists: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tjsonb_exists_array: unmapped arg type 'text * *' */
  /* SKIP tjsonb_extract_path: unmapped arg type 'text * *' */
  /* SKIP tjsonb_insert: unmapped arg type 'text * *' */
  { Temporal * r = tjsonb_object_field(tjsonb1, txt1, true, NULL_RETURN);
    printf("tjsonb_object_field: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_path_exists(tjsonb1, jp1, jb1, true, true);
    printf("tjsonb_path_exists: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_path_match(tjsonb1, jp1, jb1, true, true);
    printf("tjsonb_path_match: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_path_query_array(tjsonb1, jp1, jb1, true, true);
    printf("tjsonb_path_query_array: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_path_query_first(tjsonb1, jp1, jb1, true, true);
    printf("tjsonb_path_query_first: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_pretty(tjsonb1);
    printf("tjsonb_pretty: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tjsonb_set: unmapped arg type 'text * *' */
  { Temporal * r = tjsonb_strip_nulls(tjsonb1, true);
    printf("tjsonb_strip_nulls: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_to_tbool(tjsonb1, jb1_str, NULL_RETURN);
    printf("tjsonb_to_tbool: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_to_tfloat(tjsonb1, jb1_str, LINEAR, NULL_RETURN);
    printf("tjsonb_to_tfloat: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_to_tint(tjsonb1, jb1_str, NULL_RETURN);
    printf("tjsonb_to_tint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_to_ttext_key(tjsonb1, jb1_str, NULL_RETURN);
    printf("tjsonb_to_ttext_key: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_at_value(tjsonb1, jb1);
    printf("tjsonb_at_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tjsonb_minus_value(tjsonb1, jb1);
    printf("tjsonb_minus_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { int r = always_eq_jsonb_tjsonb(jb1, tjsonb1);
    printf("always_eq_jsonb_tjsonb: %d\n", r); }
  { int r = always_eq_tjsonb_jsonb(tjsonb1, jb1);
    printf("always_eq_tjsonb_jsonb: %d\n", r); }
  { int r = always_eq_tjsonb_tjsonb(tjsonb1, tjsonb1);
    printf("always_eq_tjsonb_tjsonb: %d\n", r); }
  { int r = always_ne_jsonb_tjsonb(jb1, tjsonb1);
    printf("always_ne_jsonb_tjsonb: %d\n", r); }
  { int r = always_ne_tjsonb_jsonb(tjsonb1, jb1);
    printf("always_ne_tjsonb_jsonb: %d\n", r); }
  { int r = always_ne_tjsonb_tjsonb(tjsonb1, tjsonb1);
    printf("always_ne_tjsonb_tjsonb: %d\n", r); }
  { int r = ever_eq_jsonb_tjsonb(jb1, tjsonb1);
    printf("ever_eq_jsonb_tjsonb: %d\n", r); }
  { int r = ever_eq_tjsonb_jsonb(tjsonb1, jb1);
    printf("ever_eq_tjsonb_jsonb: %d\n", r); }
  { int r = ever_eq_tjsonb_tjsonb(tjsonb1, tjsonb1);
    printf("ever_eq_tjsonb_tjsonb: %d\n", r); }
  { int r = ever_ne_jsonb_tjsonb(jb1, tjsonb1);
    printf("ever_ne_jsonb_tjsonb: %d\n", r); }
  { int r = ever_ne_tjsonb_jsonb(tjsonb1, jb1);
    printf("ever_ne_tjsonb_jsonb: %d\n", r); }
  { int r = ever_ne_tjsonb_tjsonb(tjsonb1, tjsonb1);
    printf("ever_ne_tjsonb_tjsonb: %d\n", r); }
  { Temporal * r = teq_jsonb_tjsonb(jb1, tjsonb1);
    printf("teq_jsonb_tjsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = teq_tjsonb_jsonb(tjsonb1, jb1);
    printf("teq_tjsonb_jsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_jsonb_tjsonb(jb1, tjsonb1);
    printf("tne_jsonb_tjsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_tjsonb_jsonb(tjsonb1, jb1);
    printf("tne_tjsonb_jsonb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }

  if (tjsonb1) free(tjsonb1);
  free(ttext1);
  free(jp1);
  free(jb1);
  free(txt1);
  free(jsonbset1);
  free(tstzspanset1);
  free(tstzspan1);

  meos_finalize();
  return 0;
}
