/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief MEOS smoke test for the tnpoint      public API.
 *
 * Auto-generated by meos/test/gen_smoketest.py — do not edit by hand.
 *
 * Each public symbol exported by meos_npoint.h gets one smoke-test
 * call site here. Arguments come from a shared common-inputs block.
 * Pointer results are freed; a non-fatal MEOS error handler keeps the
 * run going past VALIDATE_* failures so a single bad input doesn't
 * mask the rest of the surface.
 *
 * Run under valgrind to catch leaks/OOB reads:
 *
 *     valgrind --leak-check=full --error-exitcode=1 ./tnpoint_smoketest
 *
 * Build:
 *   gcc -Wall -g -I/usr/local/include -o tnpoint_smoketest \
 *       tnpoint_smoketest.c -L/usr/local/lib -lmeos -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <meos.h>
#include <meos_geo.h>
#include <meos_pose.h>
#include <meos_npoint.h>

#ifndef DatumDefined
typedef uintptr_t Datum;
#define DatumDefined 1
#endif

static void
test_error_handler(int level, int code, const char *msg)
{
  (void) level; (void) code;
  fprintf(stderr, "[meos warn] %s\n", msg);
}

int
main(void)
{
  meos_initialize();
  meos_initialize_timezone("UTC");
  meos_initialize_error_handler(test_error_handler);

  TimestampTz tstz1 = pg_timestamptz_in("2001-01-02", -1);
  Span *tstzspan1 = tstzspan_in("[2001-01-01, 2001-01-04]");
  SpanSet *tstzspanset1 = tstzspanset_in("{[2001-01-01, 2001-01-02], [2001-01-03, 2001-01-04]}");
  Interval *interv1 = NULL;
  GSERIALIZED *geom1 = geom_in("Point(0 0)", -1);
  Npoint *npoint1 = npoint_in("NPoint(1, 0.5)");
  Npoint *npoint_out_param = NULL;
  Nsegment *nsegment1 = nsegment_in("NSegment(1, 0.0, 1.0)");
  Set *npointset1 = npointset_in("{\"NPoint(1, 0.5)\"}");
  STBox *stbox1 = stbox_in("STBOX X((0, 0), (10, 10))");
  Datum npoint1_datum = (Datum) npoint1;
  size_t size_out = 0;

  Temporal *tnpoint1 = tnpoint_in(
    "[NPoint(1, 0.0)@2001-01-02, NPoint(1, 0.5)@2001-01-03]");
  TInstant *tnpoint_inst1 = (TInstant *) temporal_start_instant(tnpoint1);
  TSequence    *tnpoint_tseq1    = (TSequence *) tnpoint1;
  TSequenceSet *tnpoint_tseqset1 = NULL;
  /* tpoint1 stays a parsed tgeompoint literal (NOT tnpoint_to_tgeompoint),
   * because the latter requires the MEOS ways cache that the standalone
   * test environment does not populate. */
  Temporal *tpoint1 = tgeompoint_in(
    "[Point(0 0)@2001-01-02, Point(1 1)@2001-01-03]");
  int n_out = 0;


  printf("****************************************************************\n");
  printf("* tnpoint      MEOS smoke test%*s*\n", 32, "");
  printf("****************************************************************\n");

  { char *r = npoint_as_ewkt(npoint1, 1);
    printf("npoint_as_ewkt: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { char *r = npoint_as_hexwkb(npoint1, 1, &size_out);
    printf("npoint_as_hexwkb: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { char *r = npoint_as_text(npoint1, 1);
    printf("npoint_as_text: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { uint8_t * r = npoint_as_wkb(npoint1, 1, &size_out);
    printf("npoint_as_wkb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP npoint_from_hexwkb: unmapped arg type 'char *' */
  /* SKIP npoint_from_wkb: unmapped arg type 'uint8_t *' */
  /* SKIP npoint_in: unmapped arg type 'char *' */
  { char *r = npoint_out(npoint1, 1);
    printf("npoint_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP nsegment_in: unmapped arg type 'char *' */
  { char *r = nsegment_out(nsegment1, 1);
    printf("nsegment_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { Npoint * r = npoint_make(1, 1.0);
    printf("npoint_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Nsegment * r = nsegment_make(1, 1.0, 1.0);
    printf("nsegment_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Npoint * r = geompoint_to_npoint(geom1);
    printf("geompoint_to_npoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Nsegment * r = geom_to_nsegment(geom1);
    printf("geom_to_nsegment: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP npoint_to_geompoint: needs ways cache */
  { Nsegment * r = npoint_to_nsegment(npoint1);
    printf("npoint_to_nsegment: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP npoint_to_stbox: needs ways cache */
  /* SKIP nsegment_to_geom: needs ways cache */
  /* SKIP nsegment_to_stbox: needs ways cache */
  /* SKIP npoint_hash: unmapped return type 'uint32' */
  /* SKIP npoint_hash_extended: unmapped arg type 'uint64' */
  { double r = npoint_position(npoint1);
    printf("npoint_position: %.6f\n", r); }
  /* SKIP npoint_route: unmapped return type 'int64' */
  { double r = nsegment_end_position(nsegment1);
    printf("nsegment_end_position: %.6f\n", r); }
  /* SKIP nsegment_route: unmapped return type 'int64' */
  { double r = nsegment_start_position(nsegment1);
    printf("nsegment_start_position: %.6f\n", r); }
  { bool r = route_exists(1);
    printf("route_exists: %d\n", (int) r); }
  /* SKIP route_geom: returns a non-owned pointer into the ways cache */
  { double r = route_length(1);
    printf("route_length: %.6f\n", r); }
  { Npoint * r = npoint_round(npoint1, 1);
    printf("npoint_round: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Nsegment * r = nsegment_round(nsegment1, 1);
    printf("nsegment_round: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP get_srid_ways: unmapped return type 'int32_t' */
  /* SKIP npoint_srid: unmapped return type 'int32_t' */
  /* SKIP nsegment_srid: unmapped return type 'int32_t' */
  /* SKIP npoint_timestamptz_to_stbox: needs ways cache */
  /* SKIP npoint_tstzspan_to_stbox: needs ways cache */
  { int r = npoint_cmp(npoint1, npoint1);
    printf("npoint_cmp: %d\n", r); }
  { bool r = npoint_eq(npoint1, npoint1);
    printf("npoint_eq: %d\n", (int) r); }
  { bool r = npoint_ge(npoint1, npoint1);
    printf("npoint_ge: %d\n", (int) r); }
  { bool r = npoint_gt(npoint1, npoint1);
    printf("npoint_gt: %d\n", (int) r); }
  { bool r = npoint_le(npoint1, npoint1);
    printf("npoint_le: %d\n", (int) r); }
  { bool r = npoint_lt(npoint1, npoint1);
    printf("npoint_lt: %d\n", (int) r); }
  { bool r = npoint_ne(npoint1, npoint1);
    printf("npoint_ne: %d\n", (int) r); }
  /* SKIP npoint_same: needs ways cache */
  { int r = nsegment_cmp(nsegment1, nsegment1);
    printf("nsegment_cmp: %d\n", r); }
  { bool r = nsegment_eq(nsegment1, nsegment1);
    printf("nsegment_eq: %d\n", (int) r); }
  { bool r = nsegment_ge(nsegment1, nsegment1);
    printf("nsegment_ge: %d\n", (int) r); }
  { bool r = nsegment_gt(nsegment1, nsegment1);
    printf("nsegment_gt: %d\n", (int) r); }
  { bool r = nsegment_le(nsegment1, nsegment1);
    printf("nsegment_le: %d\n", (int) r); }
  { bool r = nsegment_lt(nsegment1, nsegment1);
    printf("nsegment_lt: %d\n", (int) r); }
  { bool r = nsegment_ne(nsegment1, nsegment1);
    printf("nsegment_ne: %d\n", (int) r); }
  /* SKIP npointset_in: needs ways cache */
  /* SKIP npointset_out: needs ways cache */
  /* SKIP npointset_make: needs ways cache */
  /* SKIP npoint_to_set: needs ways cache */
  /* SKIP npointset_end_value: needs ways cache */
  /* SKIP npointset_routes: needs ways cache */
  /* SKIP npointset_start_value: needs ways cache */
  /* SKIP npointset_value_n: needs ways cache */
  /* SKIP npointset_values: needs ways cache */
  /* SKIP contained_npoint_set: needs ways cache */
  /* SKIP contains_set_npoint: needs ways cache */
  /* SKIP intersection_npoint_set: needs ways cache */
  /* SKIP intersection_set_npoint: needs ways cache */
  /* SKIP minus_npoint_set: needs ways cache */
  /* SKIP minus_set_npoint: needs ways cache */
  /* SKIP npoint_union_transfn: aggregate state-handoff pattern incompatible with smoke-test ownership model */
  /* SKIP union_npoint_set: needs ways cache */
  /* SKIP union_set_npoint: needs ways cache */
  /* SKIP tnpoint_in: unmapped arg type 'char *' */
  { char *r = tnpoint_out(tnpoint1, 1);
    printf("tnpoint_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { TInstant * r = tnpointinst_make(npoint1, tstz1);
    printf("tnpointinst_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tgeompoint_to_tnpoint(tnpoint1);
    printf("tgeompoint_to_tnpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tnpoint_to_tgeompoint(tnpoint1);
    printf("tnpoint_to_tgeompoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tnpoint_cumulative_length(tnpoint1);
    printf("tnpoint_cumulative_length: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = tnpoint_length(tnpoint1);
    printf("tnpoint_length: %.6f\n", r); }
  { Nsegment * * r = tnpoint_positions(tnpoint1, &n_out);
    printf("tnpoint_positions: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  /* SKIP tnpoint_route: unmapped return type 'int64' */
  /* SKIP tnpoint_routes: needs ways cache */
  { Temporal * r = tnpoint_speed(tnpoint1);
    printf("tnpoint_speed: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tnpoint_trajectory: needs ways cache */
  { GSERIALIZED * r = tnpoint_twcentroid(tnpoint1);
    printf("tnpoint_twcentroid: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tnpoint_at_geom: needs ways cache */
  { Temporal * r = tnpoint_at_npoint(tnpoint1, npoint1);
    printf("tnpoint_at_npoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tnpoint_at_npointset(tnpoint1, npointset1);
    printf("tnpoint_at_npointset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tnpoint_at_stbox: needs ways cache */
  /* SKIP tnpoint_minus_geom: needs ways cache */
  { Temporal * r = tnpoint_minus_npoint(tnpoint1, npoint1);
    printf("tnpoint_minus_npoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tnpoint_minus_npointset(tnpoint1, npointset1);
    printf("tnpoint_minus_npointset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tnpoint_minus_stbox: needs ways cache */
  /* SKIP tdistance_tnpoint_npoint: needs ways cache */
  /* SKIP tdistance_tnpoint_point: needs ways cache */
  /* SKIP tdistance_tnpoint_tnpoint: needs ways cache */
  /* SKIP nad_tnpoint_geo: needs ways cache */
  /* SKIP nad_tnpoint_npoint: needs ways cache */
  /* SKIP nad_tnpoint_stbox: needs ways cache */
  /* SKIP nad_tnpoint_tnpoint: needs ways cache */
  /* SKIP nai_tnpoint_geo: needs ways cache */
  /* SKIP nai_tnpoint_npoint: needs ways cache */
  /* SKIP nai_tnpoint_tnpoint: needs ways cache */
  /* SKIP shortestline_tnpoint_geo: needs ways cache */
  /* SKIP shortestline_tnpoint_npoint: needs ways cache */
  /* SKIP shortestline_tnpoint_tnpoint: needs ways cache */
  /* SKIP tnpoint_tcentroid_transfn: aggregate state-handoff pattern incompatible with smoke-test ownership model */
  { int r = always_eq_npoint_tnpoint(npoint1, tnpoint1);
    printf("always_eq_npoint_tnpoint: %d\n", r); }
  { int r = always_eq_tnpoint_npoint(tnpoint1, npoint1);
    printf("always_eq_tnpoint_npoint: %d\n", r); }
  { int r = always_eq_tnpoint_tnpoint(tnpoint1, tnpoint1);
    printf("always_eq_tnpoint_tnpoint: %d\n", r); }
  { int r = always_ne_npoint_tnpoint(npoint1, tnpoint1);
    printf("always_ne_npoint_tnpoint: %d\n", r); }
  { int r = always_ne_tnpoint_npoint(tnpoint1, npoint1);
    printf("always_ne_tnpoint_npoint: %d\n", r); }
  { int r = always_ne_tnpoint_tnpoint(tnpoint1, tnpoint1);
    printf("always_ne_tnpoint_tnpoint: %d\n", r); }
  { int r = ever_eq_npoint_tnpoint(npoint1, tnpoint1);
    printf("ever_eq_npoint_tnpoint: %d\n", r); }
  { int r = ever_eq_tnpoint_npoint(tnpoint1, npoint1);
    printf("ever_eq_tnpoint_npoint: %d\n", r); }
  { int r = ever_eq_tnpoint_tnpoint(tnpoint1, tnpoint1);
    printf("ever_eq_tnpoint_tnpoint: %d\n", r); }
  { int r = ever_ne_npoint_tnpoint(npoint1, tnpoint1);
    printf("ever_ne_npoint_tnpoint: %d\n", r); }
  { int r = ever_ne_tnpoint_npoint(tnpoint1, npoint1);
    printf("ever_ne_tnpoint_npoint: %d\n", r); }
  { int r = ever_ne_tnpoint_tnpoint(tnpoint1, tnpoint1);
    printf("ever_ne_tnpoint_tnpoint: %d\n", r); }
  { Temporal * r = teq_tnpoint_npoint(tnpoint1, npoint1);
    printf("teq_tnpoint_npoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_tnpoint_npoint(tnpoint1, npoint1);
    printf("tne_tnpoint_npoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }

  /* tnpoint_inst1 is a fresh tinstant_copy() but freeing it triggers
   * tcache double-free (same pattern as tcbuffer_inst1). */
  if (tnpoint1) free(tnpoint1);
  if (tpoint1) free(tpoint1);
  free(stbox1);
  free(npointset1);
  free(nsegment1);
  free(npoint1);
  free(geom1);
  free(tstzspanset1);
  free(tstzspan1);

  meos_finalize();
  return 0;
}
