/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief MEOS smoke test for the tpose        public API.
 *
 * Auto-generated by meos/test/gen_smoketest.py — do not edit by hand.
 *
 * Each public symbol exported by meos_pose.h gets one smoke-test
 * call site here. Arguments come from a shared common-inputs block.
 * Pointer results are freed; a non-fatal MEOS error handler keeps the
 * run going past VALIDATE_* failures so a single bad input doesn't
 * mask the rest of the surface.
 *
 * Run under valgrind to catch leaks/OOB reads:
 *
 *     valgrind --leak-check=full --error-exitcode=1 ./tpose_smoketest
 *
 * Build:
 *   gcc -Wall -g -I/usr/local/include -o tpose_smoketest \
 *       tpose_smoketest.c -L/usr/local/lib -lmeos -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <meos.h>
#include <meos_geo.h>
#include <meos_pose.h>


#ifndef DatumDefined
typedef uintptr_t Datum;
#define DatumDefined 1
#endif

static void
test_error_handler(int level, int code, const char *msg)
{
  (void) level; (void) code;
  fprintf(stderr, "[meos warn] %s\n", msg);
}

int
main(void)
{
  meos_initialize();
  meos_initialize_timezone("UTC");
  meos_initialize_error_handler(test_error_handler);

  TimestampTz tstz1 = pg_timestamptz_in("2001-01-02", -1);
  Span *tstzspan1 = tstzspan_in("[2001-01-01, 2001-01-04]");
  Set *tstzset1 = tstzset_in("{2001-01-02, 2001-01-03}");
  SpanSet *tstzspanset1 = tstzspanset_in("{[2001-01-01, 2001-01-02], [2001-01-03, 2001-01-04]}");
  Interval *interv1 = NULL;
  GSERIALIZED *geom1 = geom_in("Point(0 0)", -1);
  GSERIALIZED *geom_out_param = NULL;
  Pose *pose1 = pose_in("Pose(Point(0 0), 0.0)");
  Pose *pose_out_param = NULL;
  STBox *stbox1 = stbox_in("STBOX X((0, 0), (10, 10))");
  Datum pose1_datum = (Datum) pose1;
  size_t size_out = 0;

  /* Build a tpose sequence directly from WKT — public tpose_in parses it. */
  Temporal *tpose1 = tpose_in(
    "[Pose(Point(0 0), 0.0)@2001-01-02, Pose(Point(1 0), 0.5)@2001-01-03]");
  TInstant *tpose_inst1 = (TInstant *) temporal_start_instant(tpose1);
  TSequence    *tpose_tseq1    = (TSequence *) tpose1;
  TSequenceSet *tpose_tseqset1 = NULL;
  Temporal *tpoint1 = tpose_to_tpoint(tpose1);
  int n_out = 0;


  printf("****************************************************************\n");
  printf("* tpose        MEOS smoke test%*s*\n", 32, "");
  printf("****************************************************************\n");

  { char *r = pose_as_ewkt(pose1, 1);
    printf("pose_as_ewkt: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { char *r = pose_as_hexwkb(pose1, 1, &size_out);
    printf("pose_as_hexwkb: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { char *r = pose_as_text(pose1, 1);
    printf("pose_as_text: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { uint8_t * r = pose_as_wkb(pose1, 1, &size_out);
    printf("pose_as_wkb: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP pose_from_wkb: unmapped arg type 'uint8_t *' */
  /* SKIP pose_from_hexwkb: unmapped arg type 'char *' */
  /* SKIP pose_in: unmapped arg type 'char *' */
  { char *r = pose_out(pose1, 1);
    printf("pose_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { Pose * r = pose_copy(pose1);
    printf("pose_copy: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Pose * r = pose_make_2d(1.0, 1.0, 1.0, 0);
    printf("pose_make_2d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Pose * r = pose_make_3d(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0);
    printf("pose_make_3d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Pose * r = pose_make_point2d(geom1, 1.0);
    printf("pose_make_point2d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Pose * r = pose_make_point3d(geom1, 1.0, 1.0, 1.0, 1.0);
    printf("pose_make_point3d: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = pose_to_point(pose1);
    printf("pose_to_point: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = pose_to_stbox(pose1);
    printf("pose_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP pose_hash: unmapped return type 'uint32' */
  /* SKIP pose_hash_extended: unmapped arg type 'uint64' */
  { double * r = pose_orientation(pose1);
    printf("pose_orientation: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = pose_rotation(pose1);
    printf("pose_rotation: %.6f\n", r); }
  { Pose * r = pose_round(pose1, 1);
    printf("pose_round: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP posearr_round: unmapped arg type 'Pose * *' */
  /* SKIP pose_set_srid: unmapped return type 'void' */
  /* SKIP pose_srid: unmapped return type 'int32_t' */
  { Pose * r = pose_transform(pose1, 0);
    printf("pose_transform: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP pose_transform_pipeline: unmapped arg type 'char *' */
  { STBox * r = pose_tstzspan_to_stbox(pose1, tstzspan1);
    printf("pose_tstzspan_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = pose_timestamptz_to_stbox(pose1, tstz1);
    printf("pose_timestamptz_to_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = distance_pose_geo(pose1, geom1);
    printf("distance_pose_geo: %.6f\n", r); }
  { double r = distance_pose_pose(pose1, pose1);
    printf("distance_pose_pose: %.6f\n", r); }
  { double r = distance_pose_stbox(pose1, stbox1);
    printf("distance_pose_stbox: %.6f\n", r); }
  { int r = pose_cmp(pose1, pose1);
    printf("pose_cmp: %d\n", r); }
  { bool r = pose_eq(pose1, pose1);
    printf("pose_eq: %d\n", (int) r); }
  { bool r = pose_ge(pose1, pose1);
    printf("pose_ge: %d\n", (int) r); }
  { bool r = pose_gt(pose1, pose1);
    printf("pose_gt: %d\n", (int) r); }
  { bool r = pose_le(pose1, pose1);
    printf("pose_le: %d\n", (int) r); }
  { bool r = pose_lt(pose1, pose1);
    printf("pose_lt: %d\n", (int) r); }
  { bool r = pose_ne(pose1, pose1);
    printf("pose_ne: %d\n", (int) r); }
  { bool r = pose_nsame(pose1, pose1);
    printf("pose_nsame: %d\n", (int) r); }
  { bool r = pose_same(pose1, pose1);
    printf("pose_same: %d\n", (int) r); }
  /* SKIP poseset_in: unmapped arg type 'char *' */
  { char *r = poseset_out(tstzset1, 1);
    printf("poseset_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  /* SKIP poseset_make: unmapped arg type 'Pose * *' */
  { Set * r = pose_to_set(pose1);
    printf("pose_to_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Pose * r = poseset_end_value(tstzset1);
    printf("poseset_end_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Pose * r = poseset_start_value(tstzset1);
    printf("poseset_start_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP poseset_value_n: unmapped arg type 'Pose * *' */
  { Pose * * r = poseset_values(tstzset1);
    printf("poseset_values: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { bool r = contained_pose_set(pose1, tstzset1);
    printf("contained_pose_set: %d\n", (int) r); }
  { bool r = contains_set_pose(tstzset1, pose1);
    printf("contains_set_pose: %d\n", (int) r); }
  { Set * r = intersection_pose_set(pose1, tstzset1);
    printf("intersection_pose_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = intersection_set_pose(tstzset1, pose1);
    printf("intersection_set_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = minus_pose_set(pose1, tstzset1);
    printf("minus_pose_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = minus_set_pose(tstzset1, pose1);
    printf("minus_set_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP pose_union_transfn: aggregate state-handoff pattern incompatible with smoke-test ownership model */
  { Set * r = union_pose_set(pose1, tstzset1);
    printf("union_pose_set: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = union_set_pose(tstzset1, pose1);
    printf("union_set_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpose_make(tpose1, tpose1);
    printf("tpose_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpose_to_tpoint(tpose1);
    printf("tpose_to_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Pose * r = tpose_end_value(tpose1);
    printf("tpose_end_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Set * r = tpose_points(tpose1);
    printf("tpose_points: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpose_rotation(tpose1);
    printf("tpose_rotation: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Pose * r = tpose_start_value(tpose1);
    printf("tpose_start_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = tpose_trajectory(tpose1);
    printf("tpose_trajectory: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP tpose_value_at_timestamptz: out-param Pose ** has no clean canned site; covered manually */
  /* SKIP tpose_value_n: unmapped arg type 'Pose * *' */
  { Pose * * r = tpose_values(tpose1, &n_out);
    printf("tpose_values: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { Temporal * r = tpose_at_geom(tpose1, geom1);
    printf("tpose_at_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpose_at_stbox(tpose1, stbox1, true);
    printf("tpose_at_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpose_at_pose(tpose1, pose1);
    printf("tpose_at_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpose_minus_geom(tpose1, geom1);
    printf("tpose_minus_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpose_minus_pose(tpose1, pose1);
    printf("tpose_minus_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tpose_minus_stbox(tpose1, stbox1, true);
    printf("tpose_minus_stbox: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_tpose_pose(tpose1, pose1);
    printf("tdistance_tpose_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_tpose_point(tpose1, geom1);
    printf("tdistance_tpose_point: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_tpose_tpose(tpose1, tpose1);
    printf("tdistance_tpose_tpose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = nad_tpose_geo(tpose1, geom1);
    printf("nad_tpose_geo: %.6f\n", r); }
  { double r = nad_tpose_pose(tpose1, pose1);
    printf("nad_tpose_pose: %.6f\n", r); }
  { double r = nad_tpose_stbox(tpose1, stbox1);
    printf("nad_tpose_stbox: %.6f\n", r); }
  { double r = nad_tpose_tpose(tpose1, tpose1);
    printf("nad_tpose_tpose: %.6f\n", r); }
  { TInstant * r = nai_tpose_geo(tpose1, geom1);
    printf("nai_tpose_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = nai_tpose_pose(tpose1, pose1);
    printf("nai_tpose_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = nai_tpose_tpose(tpose1, tpose1);
    printf("nai_tpose_tpose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_tpose_geo(tpose1, geom1);
    printf("shortestline_tpose_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_tpose_pose(tpose1, pose1);
    printf("shortestline_tpose_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_tpose_tpose(tpose1, tpose1);
    printf("shortestline_tpose_tpose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { int r = always_eq_pose_tpose(pose1, tpose1);
    printf("always_eq_pose_tpose: %d\n", r); }
  { int r = always_eq_tpose_pose(tpose1, pose1);
    printf("always_eq_tpose_pose: %d\n", r); }
  { int r = always_eq_tpose_tpose(tpose1, tpose1);
    printf("always_eq_tpose_tpose: %d\n", r); }
  { int r = always_ne_pose_tpose(pose1, tpose1);
    printf("always_ne_pose_tpose: %d\n", r); }
  { int r = always_ne_tpose_pose(tpose1, pose1);
    printf("always_ne_tpose_pose: %d\n", r); }
  { int r = always_ne_tpose_tpose(tpose1, tpose1);
    printf("always_ne_tpose_tpose: %d\n", r); }
  { int r = ever_eq_pose_tpose(pose1, tpose1);
    printf("ever_eq_pose_tpose: %d\n", r); }
  { int r = ever_eq_tpose_pose(tpose1, pose1);
    printf("ever_eq_tpose_pose: %d\n", r); }
  { int r = ever_eq_tpose_tpose(tpose1, tpose1);
    printf("ever_eq_tpose_tpose: %d\n", r); }
  { int r = ever_ne_pose_tpose(pose1, tpose1);
    printf("ever_ne_pose_tpose: %d\n", r); }
  { int r = ever_ne_tpose_pose(tpose1, pose1);
    printf("ever_ne_tpose_pose: %d\n", r); }
  { int r = ever_ne_tpose_tpose(tpose1, tpose1);
    printf("ever_ne_tpose_tpose: %d\n", r); }
  { Temporal * r = teq_pose_tpose(pose1, tpose1);
    printf("teq_pose_tpose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = teq_tpose_pose(tpose1, pose1);
    printf("teq_tpose_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_pose_tpose(pose1, tpose1);
    printf("tne_pose_tpose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_tpose_pose(tpose1, pose1);
    printf("tne_tpose_pose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }

  if (tpose_inst1) free(tpose_inst1);
  if (tpose1) free(tpose1);
  if (tpoint1) free(tpoint1);
  free(stbox1);
  free(pose1);
  free(geom1);
  free(tstzspanset1);
  free(tstzset1);
  free(tstzspan1);

  meos_finalize();
  return 0;
}
