/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief MEOS smoke test for the trgeometry public API.
 *
 * Auto-generated by meos/test/gen_smoketest.py — do not edit by hand.
 *
 * Each public symbol exported by meos_rgeo.h gets one smoke-test
 * call site here. Arguments come from a shared common-inputs block.
 * Pointer results are freed; a non-fatal MEOS error handler keeps the
 * run going past VALIDATE_* failures so a single bad input doesn't
 * mask the rest of the surface.
 *
 * Run under valgrind to catch leaks/OOB reads:
 *
 *     valgrind --leak-check=full --error-exitcode=1 ./trgeometry_test
 *
 * Build:
 *   gcc -Wall -g -I/usr/local/include -o trgeometry_test \
 *       trgeometry_test.c -L/usr/local/lib -lmeos -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <meos.h>
#include <meos_geo.h>
#include <meos_pose.h>
#include <meos_rgeo.h>

#ifndef DatumDefined
typedef uintptr_t Datum;
#define DatumDefined 1
#endif

static void
test_error_handler(int level, int code, const char *msg)
{
  (void) level; (void) code;
  fprintf(stderr, "[meos warn] %s\n", msg);
}

int
main(void)
{
  meos_initialize();
  meos_initialize_timezone("UTC");
  meos_initialize_error_handler(test_error_handler);

  TimestampTz tstz1 = pg_timestamptz_in("2001-01-02", -1);
  Span *tstzspan1 = tstzspan_in("[2001-01-01, 2001-01-04]");
  Set *tstzset1 = tstzset_in("{2001-01-02, 2001-01-03}");
  SpanSet *tstzspanset1 = tstzspanset_in("{[2001-01-01, 2001-01-02], [2001-01-03, 2001-01-04]}");
  Interval *interv1 = NULL;
  GSERIALIZED *geom1 = geom_in("Polygon((0 0,1 0,1 1,0 1,0 0))", -1);
  Pose *pose1 = pose_in("Pose(Point(0 0), 0.0)");
  STBox *stbox1 = stbox_in("STBOX X((0, 0), (10, 10))");
  Datum geom1_datum = (Datum) geom1;

  TInstant *trgeo_inst1 = trgeoinst_make(geom1, pose1, tstz1);
  TInstant *trgeo_inst2 = trgeoinst_make(geom1, pose1,
    pg_timestamptz_in("2001-01-03", -1));
  Temporal *trgeo_seq1 = (Temporal *) trgeo_inst1;
  trgeo_seq1 = trgeo_append_tinstant(trgeo_seq1, trgeo_inst2,
    LINEAR, 0.0, NULL, false);
  TSequence    *trgeo_tseq1    = (TSequence *) trgeo_seq1;
  Temporal *tpoint1 = trgeo_to_tpoint(trgeo_seq1);
  Temporal *tpose1 = trgeo_to_tpose(trgeo_seq1);
  int n_out = 0;


  printf("****************************************************************\n");
  printf("* trgeometry MEOS smoke test%*s*\n", 34, "");
  printf("****************************************************************\n");

  { char *r = trgeo_out(trgeo_seq1);
    printf("trgeo_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { TInstant * r = trgeoinst_make(geom1, pose1, tstz1);
    printf("trgeoinst_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = geo_tpose_to_trgeo(geom1, tpose1);
    printf("geo_tpose_to_trgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_to_tpose(trgeo_seq1);
    printf("trgeo_to_tpose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_to_tpoint(trgeo_seq1);
    printf("trgeo_to_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = trgeo_end_instant(trgeo_seq1);
    printf("trgeo_end_instant: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * r = trgeo_end_sequence(trgeo_seq1);
    printf("trgeo_end_sequence: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = trgeo_end_value(trgeo_seq1);
    printf("trgeo_end_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = trgeo_geom(trgeo_seq1);
    printf("trgeo_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = trgeo_instant_n(trgeo_seq1, 1);
    printf("trgeo_instant_n: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * * r = trgeo_instants(trgeo_seq1, &n_out);
    printf("trgeo_instants: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  /* SKIP trgeo_points: not yet implemented */
  /* SKIP trgeo_rotation: not yet implemented */
  /* SKIP trgeo_segments: not yet implemented */
  { TSequence * r = trgeo_sequence_n(trgeo_seq1, 1);
    printf("trgeo_sequence_n: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * * r = trgeo_sequences(trgeo_seq1, &n_out);
    printf("trgeo_sequences: %s n=%d\n", r ? "OK" : "NULL", n_out);
    if (r) {
      for (int _i = 0; _i < n_out; _i++) if (r[_i]) free(r[_i]);
      free(r);
    } }
  { TInstant * r = trgeo_start_instant(trgeo_seq1);
    printf("trgeo_start_instant: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * r = trgeo_start_sequence(trgeo_seq1);
    printf("trgeo_start_sequence: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = trgeo_start_value(trgeo_seq1);
    printf("trgeo_start_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP trgeo_value_n: out-param GSERIALIZED ** is exercised manually below */
  { GSERIALIZED * r = trgeo_traversed_area(trgeo_seq1, false);
    printf("trgeo_traversed_area: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = trgeo_convex_hull(trgeo_seq1);
    printf("trgeo_convex_hull: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_centroid(trgeo_seq1);
    printf("trgeo_centroid: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { STBox * r = trgeo_expand_space(trgeo_seq1, 1.0);
    printf("trgeo_expand_space: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Interval *interv = pg_interval_in("1 day", -1);
    Temporal * r = trgeo_simplify_min_tdelta(trgeo_seq1, interv);
    printf("trgeo_simplify_min_tdelta: %s\n", r ? "OK" : "NULL");
    if (r) free(r); free(interv); }
  { Temporal * r = trgeo_simplify_min_dist(trgeo_seq1, 1.0);
    printf("trgeo_simplify_min_dist: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_simplify_max_dist(trgeo_seq1, 1.0, true);
    printf("trgeo_simplify_max_dist: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_simplify_dp(trgeo_seq1, 1.0, true);
    printf("trgeo_simplify_dp: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_append_tinstant(trgeo_seq1, trgeo_inst1, LINEAR, 1.0, interv1, true);
    printf("trgeo_append_tinstant: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_append_tsequence(trgeo_seq1, trgeo_tseq1, true);
    printf("trgeo_append_tsequence: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_delete_timestamptz(trgeo_seq1, tstz1, true);
    printf("trgeo_delete_timestamptz: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_delete_tstzset(trgeo_seq1, tstzset1, true);
    printf("trgeo_delete_tstzset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_delete_tstzspan(trgeo_seq1, tstzspan1, true);
    printf("trgeo_delete_tstzspan: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_delete_tstzspanset(trgeo_seq1, tstzspanset1, true);
    printf("trgeo_delete_tstzspanset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_round(trgeo_seq1, 1);
    printf("trgeo_round: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_set_interp(trgeo_seq1, LINEAR);
    printf("trgeo_set_interp: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = trgeo_to_tinstant(trgeo_seq1);
    printf("trgeo_to_tinstant: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_after_timestamptz(trgeo_seq1, tstz1, true);
    printf("trgeo_after_timestamptz: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_before_timestamptz(trgeo_seq1, tstz1, true);
    printf("trgeo_before_timestamptz: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_restrict_value(trgeo_seq1, geom1_datum, true);
    printf("trgeo_restrict_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_restrict_values(trgeo_seq1, tstzset1, true);
    printf("trgeo_restrict_values: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_restrict_timestamptz(trgeo_seq1, tstz1, true);
    printf("trgeo_restrict_timestamptz: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_restrict_tstzset(trgeo_seq1, tstzset1, true);
    printf("trgeo_restrict_tstzset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_restrict_tstzspan(trgeo_seq1, tstzspan1, true);
    printf("trgeo_restrict_tstzspan: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeo_restrict_tstzspanset(trgeo_seq1, tstzspanset1, true);
    printf("trgeo_restrict_tstzspanset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_trgeo_geo(trgeo_seq1, geom1);
    printf("tdistance_trgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_trgeo_tpoint(trgeo_seq1, tpoint1);
    printf("tdistance_trgeo_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("tdistance_trgeo_trgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP nad_stbox_trgeo: not yet implemented */
  { double r = nad_trgeo_geo(trgeo_seq1, geom1);
    printf("nad_trgeo_geo: %.6f\n", r); }
  { double r = nad_trgeo_stbox(trgeo_seq1, stbox1);
    printf("nad_trgeo_stbox: %.6f\n", r); }
  { double r = nad_trgeo_tpoint(trgeo_seq1, tpoint1);
    printf("nad_trgeo_tpoint: %.6f\n", r); }
  { double r = nad_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("nad_trgeo_trgeo: %.6f\n", r); }
  { TInstant * r = nai_trgeo_geo(trgeo_seq1, geom1);
    printf("nai_trgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = nai_trgeo_tpoint(trgeo_seq1, tpoint1);
    printf("nai_trgeo_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = nai_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("nai_trgeo_trgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_trgeo_geo(trgeo_seq1, geom1);
    printf("shortestline_trgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_trgeo_tpoint(trgeo_seq1, tpoint1);
    printf("shortestline_trgeo_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("shortestline_trgeo_trgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { int r = econtains_geo_trgeo(geom1, trgeo_seq1);
    printf("econtains_geo_trgeo: %d\n", r); }
  { int r = acontains_geo_trgeo(geom1, trgeo_seq1);
    printf("acontains_geo_trgeo: %d\n", r); }
  { int r = econtains_trgeo_geo(trgeo_seq1, geom1);
    printf("econtains_trgeo_geo: %d\n", r); }
  { int r = acontains_trgeo_geo(trgeo_seq1, geom1);
    printf("acontains_trgeo_geo: %d\n", r); }
  { int r = econtains_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("econtains_trgeo_trgeo: %d\n", r); }
  { int r = acontains_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("acontains_trgeo_trgeo: %d\n", r); }
  { int r = ecovers_geo_trgeo(geom1, trgeo_seq1);
    printf("ecovers_geo_trgeo: %d\n", r); }
  { int r = acovers_geo_trgeo(geom1, trgeo_seq1);
    printf("acovers_geo_trgeo: %d\n", r); }
  { int r = ecovers_trgeo_geo(trgeo_seq1, geom1);
    printf("ecovers_trgeo_geo: %d\n", r); }
  { int r = acovers_trgeo_geo(trgeo_seq1, geom1);
    printf("acovers_trgeo_geo: %d\n", r); }
  { int r = ecovers_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("ecovers_trgeo_trgeo: %d\n", r); }
  { int r = acovers_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("acovers_trgeo_trgeo: %d\n", r); }
  { int r = edisjoint_geo_trgeo(geom1, trgeo_seq1);
    printf("edisjoint_geo_trgeo: %d\n", r); }
  { int r = adisjoint_geo_trgeo(geom1, trgeo_seq1);
    printf("adisjoint_geo_trgeo: %d\n", r); }
  { int r = edisjoint_trgeo_geo(trgeo_seq1, geom1);
    printf("edisjoint_trgeo_geo: %d\n", r); }
  { int r = adisjoint_trgeo_geo(trgeo_seq1, geom1);
    printf("adisjoint_trgeo_geo: %d\n", r); }
  { int r = edisjoint_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("edisjoint_trgeo_trgeo: %d\n", r); }
  { int r = adisjoint_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("adisjoint_trgeo_trgeo: %d\n", r); }
  { int r = eintersects_geo_trgeo(geom1, trgeo_seq1);
    printf("eintersects_geo_trgeo: %d\n", r); }
  { int r = aintersects_geo_trgeo(geom1, trgeo_seq1);
    printf("aintersects_geo_trgeo: %d\n", r); }
  { int r = eintersects_trgeo_geo(trgeo_seq1, geom1);
    printf("eintersects_trgeo_geo: %d\n", r); }
  { int r = aintersects_trgeo_geo(trgeo_seq1, geom1);
    printf("aintersects_trgeo_geo: %d\n", r); }
  { int r = eintersects_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("eintersects_trgeo_trgeo: %d\n", r); }
  { int r = aintersects_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("aintersects_trgeo_trgeo: %d\n", r); }
  { int r = etouches_geo_trgeo(geom1, trgeo_seq1);
    printf("etouches_geo_trgeo: %d\n", r); }
  { int r = atouches_geo_trgeo(geom1, trgeo_seq1);
    printf("atouches_geo_trgeo: %d\n", r); }
  { int r = etouches_trgeo_geo(trgeo_seq1, geom1);
    printf("etouches_trgeo_geo: %d\n", r); }
  { int r = atouches_trgeo_geo(trgeo_seq1, geom1);
    printf("atouches_trgeo_geo: %d\n", r); }
  { int r = etouches_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("etouches_trgeo_trgeo: %d\n", r); }
  { int r = atouches_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("atouches_trgeo_trgeo: %d\n", r); }
  { int r = edwithin_geo_trgeo(geom1, trgeo_seq1, 1.0);
    printf("edwithin_geo_trgeo: %d\n", r); }
  { int r = adwithin_geo_trgeo(geom1, trgeo_seq1, 1.0);
    printf("adwithin_geo_trgeo: %d\n", r); }
  { int r = edwithin_trgeo_geo(trgeo_seq1, geom1, 1.0);
    printf("edwithin_trgeo_geo: %d\n", r); }
  { int r = adwithin_trgeo_geo(trgeo_seq1, geom1, 1.0);
    printf("adwithin_trgeo_geo: %d\n", r); }
  { int r = edwithin_trgeo_trgeo(trgeo_seq1, trgeo_seq1, 1.0);
    printf("edwithin_trgeo_trgeo: %d\n", r); }
  { int r = adwithin_trgeo_trgeo(trgeo_seq1, trgeo_seq1, 1.0);
    printf("adwithin_trgeo_trgeo: %d\n", r); }
  { int r = always_eq_geo_trgeo(geom1, trgeo_seq1);
    printf("always_eq_geo_trgeo: %d\n", r); }
  { int r = always_eq_trgeo_geo(trgeo_seq1, geom1);
    printf("always_eq_trgeo_geo: %d\n", r); }
  { int r = always_eq_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("always_eq_trgeo_trgeo: %d\n", r); }
  { int r = always_ne_geo_trgeo(geom1, trgeo_seq1);
    printf("always_ne_geo_trgeo: %d\n", r); }
  { int r = always_ne_trgeo_geo(trgeo_seq1, geom1);
    printf("always_ne_trgeo_geo: %d\n", r); }
  { int r = always_ne_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("always_ne_trgeo_trgeo: %d\n", r); }
  { int r = ever_eq_geo_trgeo(geom1, trgeo_seq1);
    printf("ever_eq_geo_trgeo: %d\n", r); }
  { int r = ever_eq_trgeo_geo(trgeo_seq1, geom1);
    printf("ever_eq_trgeo_geo: %d\n", r); }
  { int r = ever_eq_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("ever_eq_trgeo_trgeo: %d\n", r); }
  { int r = ever_ne_geo_trgeo(geom1, trgeo_seq1);
    printf("ever_ne_geo_trgeo: %d\n", r); }
  { int r = ever_ne_trgeo_geo(trgeo_seq1, geom1);
    printf("ever_ne_trgeo_geo: %d\n", r); }
  { int r = ever_ne_trgeo_trgeo(trgeo_seq1, trgeo_seq1);
    printf("ever_ne_trgeo_trgeo: %d\n", r); }
  { Temporal * r = teq_geo_trgeo(geom1, trgeo_seq1);
    printf("teq_geo_trgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = teq_trgeo_geo(trgeo_seq1, geom1);
    printf("teq_trgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_geo_trgeo(geom1, trgeo_seq1);
    printf("tne_geo_trgeo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_trgeo_geo(trgeo_seq1, geom1);
    printf("tne_trgeo_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }

  /* Manually exercise trgeo_value_n (out-param GSERIALIZED **). */
  {
    GSERIALIZED *out_geom = NULL;
    bool ok = trgeo_value_n(trgeo_seq1, 1, &out_geom);
    printf("trgeo_value_n: ok=%d ptr=%s\n", (int) ok, out_geom ? "OK" : "NULL");
    if (out_geom) free(out_geom);
  }

  free(trgeo_inst1);
  free(trgeo_inst2);
  if (trgeo_seq1) free(trgeo_seq1);
  if (tpoint1) free(tpoint1);
  if (tpose1) free(tpose1);
  free(stbox1);
  free(pose1);
  free(geom1);
  free(tstzspanset1);
  free(tstzset1);
  free(tstzspan1);

  meos_finalize();
  return 0;
}
