/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2022, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2022, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS. 
 *
 *****************************************************************************/

/**
 * @brief A simple program that reads from a CSV file synthetic trip data in
 * Brussels generated by the MobilityDB-BerlinMOD generator
 * https://github.com/MobilityDB/MobilityDB-BerlinMOD
 * splits the trips and the speed of these trips into tiles, and computes
 * aggregate values of the duration, and distance of the tiles.
 *
 * Please read the assumptions made about the input file `trips.csv` in the
 * file `meos_disassemble_berlinmod.c` in the same directory.
 *
 * The program can be build as follows
 * @code
 * gcc -Wall -g -I/usr/local/include -o meos_tile_berlinmod meos_tile_berlinmod.c -L/usr/local/lib -lmeos
 * @endcode
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <meos.h>

/* Maximum length in characters of a trip in the input data */
#define MAX_LENGTH_TRIP 160000
/* Maximum length in characters of a geometry in the input data */
#define MAX_LENGTH_HEADER 1024
/* Maximum length in characters of a date in the input data */
#define MAX_LENGTH_DATE 12
/* Maximum number of buckets in each dimension */
#define MAX_NO_BUCKETS 10

/* Main program */
int main(void)
{
  /* Variables to read the input CSV file */
  char trip_buffer[MAX_LENGTH_TRIP];
  char header_buffer[MAX_LENGTH_HEADER];
  char date_buffer[MAX_LENGTH_DATE];

  /* Number of records */
  int no_records = 0;
  int no_nulls = 0;
  /* Iterator variables */
  int i, j, k;

  /* Initialize MEOS */
  meos_initialize(NULL);

  /* Compute the value and time tiles */
  Interval *duration = pg_interval_in("1 day", -1);
  TimestampTz torigin = pg_timestamptz_in("2020-06-01", -1);
  TBOX *extent = tbox_in("TBOX XT([0, 35),[2020-06-01, 2020-06-05))");
  int no_rows, no_cols;
  TBOX *speed_tiles = tbox_tile_list(extent, 10.0, duration, 0.0, torigin,
    &no_rows, &no_cols);
  /* Variables for the speeds of trips */
  Interval *speed_splits = malloc(sizeof(Interval) * no_rows * no_cols);
  memset(speed_splits, 0, sizeof(Interval) * no_rows * no_cols);

  /* Substitute the full file path in the first argument of fopen */
  FILE *file = fopen("trips.csv", "r");

  if (! file)
  {
    printf("Error opening file\n");
    return 1;
  }

  /* Read the first line of the file with the headers */
  fscanf(file, "%1024s\n", header_buffer);

  /* Continue reading the file */
  do
  {
    int tripId, vehId, seq;
    int read = fscanf(file, "%d,%d,%10[^,],%d,%160000[^\n]\n",
      &tripId, &vehId, date_buffer, &seq, trip_buffer);
    /* Transform the string representing the trip into a temporal value */
    Temporal *trip = temporal_from_hexwkb(trip_buffer);
    Temporal *speed = tpoint_speed(trip);

    if (read == 5)
      no_records++;

    if (read != 5 && !feof(file))
    {
      printf("Record with missing values ignored\n");
      no_nulls++;
    }

    if (ferror(file))
    {
      printf("Error reading file\n");
      fclose(file);
      return 1;
    }

    /* Split the temporal speed with the tiles and accumulate aggregate values */
    k = 0;
    for (i = 0; i < no_rows; i++)
    {
      for (j = 0; j < no_cols; j++)
      {
        Temporal *split = tnumber_at_tbox(speed, &speed_tiles[k]);
        if (split != NULL)
        {
          Interval *dur1 = temporal_duration(split);
          Interval *dur2 = pg_interval_pl(dur1, &speed_splits[k]);
          memcpy(&speed_splits[k], dur2, sizeof(Interval));
          free(split); free(dur1); free(dur2);
        }
        k++;
      }
    }

    free(trip);
    free(speed);

  } while (!feof(file));

  printf("\n%d records read.\n%d incomplete records ignored.\n",
    no_records, no_nulls);

  /* Print results */
  printf("-------------\n");
  printf(" Speed tiles \n");
  printf("-------------\n");
  k = 0;
  for (i = 0; i < no_rows; i++)
  {
    for (j = 0; j < no_cols; j++)
    {
      char *span_str = span_out(&speed_tiles[k].span, 0);
      char *period_str = span_out(&speed_tiles[k].period, 0);
      char *interval_str = pg_interval_out(&speed_splits[k]);
      printf("Tile: (%d,%d), Span: %s, Period: %s, Duration : %s\n",
        i, j, span_str, period_str, interval_str);
      free(span_str); free(period_str); free(interval_str);
      k++;
    }
  }

  /* Free memory */
  free(speed_tiles);

  /* Close the file */
  fclose(file);

  /* Finalize MEOS */
  meos_finish();

  return 0;
}
