/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2022, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2022, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS. 
 *
 *****************************************************************************/

/**
 * @brief A simple program that reads from a CSV file synthetic trip data in
 * Brussels generated by the MobilityDB-BerlinMOD generator,
 * https://github.com/MobilityDB/MobilityDB-BerlinMOD
 * and performs a temporal count aggregation.
 *
 * Please read the assumptions made about the input file `trips.csv` in the
 * file `meos_disassemble_berlinmod.c` in the same directory.
 *
 * The program can be build as follows
 * @code
 * gcc -Wall -g -I/usr/local/include -o meos_aggregate_berlinmod meos_aggregate_berlinmod.c -L/usr/local/lib -lmeos
 * @endcode
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "meos.h"

typedef struct
{
  int tripid;
  int vehid;
  DateADT day;
  int seq;
  Temporal *trip;
} trip_record;

trip_record trip_rec;

/* Maximum length in characters of a header in the input CSV file */
#define MAX_LENGTH_HEADER 1024
/* Maximum length in characters of a date in the input data */
#define MAX_LENGTH_DATE 12
/* Maximum length in characters of a trip in the input data */
#define MAX_LENGTH_TRIP 160000

/* Variables to read the input CSV file */
char text_buffer[MAX_LENGTH_HEADER];
char date_buffer[MAX_LENGTH_DATE];
char trip_buffer[MAX_LENGTH_TRIP];

/* Main program */
int main(void)
{
  /* Initialize MEOS */
  meos_initialize(NULL);

  /* You may substitute the full file path in the first argument of fopen */
  FILE *file = fopen("trips.csv", "r");

  if (! file)
  {
    printf("Error opening file\n");
    return 1;
  }

  int i = 0;

  /* Read the first line of the file with the headers */
  fscanf(file, "%1024s\n", text_buffer);

  /* Variable keeping the current aggregate state */
  SkipList *state = NULL;
  STBOX *extent = NULL;
  Interval *interval = pg_interval_in("1 hour", -1);
  TimestampTz origin = pg_timestamptz_in("2020-06-01", -1);

  /* Continue reading the file */
  do
  {
    int read = fscanf(file, "%d,%d,%10[^,],%d,%160000[^\n]\n",
      &trip_rec.tripid, &trip_rec.vehid, date_buffer, &trip_rec.seq, trip_buffer);
    /* Transform the string representing the date into a date value */
    DateADT day = pg_date_in(date_buffer);
    /* Transform the string representing the trip into a temporal value */
    Temporal *trip = temporal_from_hexwkb(trip_buffer);

    /* Save the trip record */
    trip_rec.day = day;
    trip_rec.trip = trip;

    if (read == 5)
      i++;

    if (read != 5 && !feof(file))
    {
      printf("Trip record with missing values\n");
      fclose(file);
      return 1;
    }

    if (ferror(file))
    {
      printf("Error reading file\n");
      fclose(file);
      return 1;
    }

    /* Add the current value to the running aggregate state */
    extent = tpoint_extent_transfn(extent, trip);

    state = temporal_tcount_transfn(state, trip, interval, origin);

  } while (!feof(file));

  printf("\n%d trip records read\n\n", i);

  printf("Extent\n");
  printf("------\n\n");
  printf("\%s\n\n", stbox_out(extent, 6));

  printf("Temporal count\n");
  printf("--------------\n\n");
  int seqcount;
  Temporal *tcount = temporal_tagg_finalfn(state);
  Temporal **tcount_seqs = (Temporal **) temporal_sequences(tcount, &seqcount);
  for (int i = 0; i < seqcount; i++)
    printf("\%s\n", tint_out(tcount_seqs[i]));

  /* Free memory */
  skiplist_free(state);
  free(tcount_seqs);

  /* Close the input file */
  fclose(file);

  /* Finalize MEOS */
  meos_finish();

  return 0;
}
