#!/usr/bin/env python3
"""Inherited-behaviour SQL generator for Temporal<T> subclasses."""
# Emits the SQL surface that every TNumber<T> / TSpatial<T> subtype INHERITS via
# late binding + lifting (compops, topops, posops, spatialrels, ...). These files
# are pure wiring to the generic Tspatial_* / Temporal_* wrappers and are identical
# across families modulo the type tokens, so they are generated from one template
# per behaviour rather than hand-maintained per family (see memory
# temporal-oo-late-binding-architecture + meos-api-codegen-regularity).
#
#   python tools/codegen/inherited/generate.py            # emit new (non-reference) types
#   python tools/codegen/inherited/generate.py --check     # dry-run, list target paths
#   python tools/codegen/inherited/generate.py --validate   # self-regen reference == committed
from __future__ import annotations
import argparse
import pathlib
import re
import sys

try:
    import yaml  # pyyaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
MANIFEST = HERE / "manifest.yaml"
TEMPLATES = HERE / "templates"

BANNER = (
    "/* GENERATED by tools/codegen/inherited/generate.py from "
    "templates/{tmpl} — DO NOT EDIT BY HAND;\n"
    " * edit the template + tools/codegen/inherited/manifest.yaml and re-run. */\n")


# Additive @IF flags: a block that only a minority of families carry defaults OFF,
# so a family opts IN explicitly rather than opting out. front_back guards the Z
# (front/back) position operators, which only the 3-D-capable spatial families
# (tpose, trgeometry, and the tgeo reference) have; every other family omits them.
DEFAULT_FALSE_FLAGS = {"front_back"}


def apply_conditionals(text: str, sub: dict) -> str:
    """Strip ``-- @IF <flag>`` / ``-- @ENDIF`` blocks whose flag is false."""
    # A subtractive flag defaults to true (the reference keeps the block; an
    # exception strips it, e.g. a cell-index sets scalar_stbox_cast: false). An
    # additive flag (DEFAULT_FALSE_FLAGS) defaults to false: the reference omits
    # the block and a carrying family opts in (e.g. tpose sets front_back: true).
    # Blocks nest: a level is emitted only when it AND every enclosing level are
    # kept, so an outer flag can drop a whole preamble whose inner flags still
    # give partially-suppressing families their finer control (e.g. box_extraction
    # wraps the scalar_stbox_cast / stboxes sub-blocks).
    out, stack = [], []  # stack[-1] = effective skip (this level or any ancestor)
    for line in text.splitlines(keepends=True):
        s = line.strip()
        if s.startswith("-- @IF "):
            flag = s[len("-- @IF "):].strip()
            this_skip = not sub.get(flag, flag not in DEFAULT_FALSE_FLAGS)
            stack.append(this_skip or (stack[-1] if stack else False))
            continue
        if s.startswith("-- @ENDIF"):
            if stack:
                stack.pop()
            continue
        if not (stack and stack[-1]):
            out.append(line)
    return "".join(out)


def render(behaviour: str, sub: dict) -> str:
    tmpl = apply_conditionals((TEMPLATES / f"{behaviour}.sql.tmpl").read_text(), sub)
    # The cell-boundary function name defaults to `<temp>CellToBoundary`
    # (e.g. tquadbinCellToBoundary), but the h3 family - whose cell functions carry
    # the pg-h3 name temporalized by a bare `t` prefix (h3CellToBoundary ->
    # th3CellToBoundary, NOT th3indexCellToBoundary) - overrides it via `boundary_fn`.
    boundary = sub.get("boundary_fn", sub["temp"] + "CellToBoundary")
    # Capitalized base = the C-symbol stem for the scalar base::stbox cast
    # (Cbuffer_to_stbox, Pose_to_stbox, Npoint_to_stbox — all base.capitalize()).
    # Families whose C symbol does not follow that rule override it via `cbase`.
    cbase = sub.get("cbase", sub["base"].capitalize())
    # Symbol stem of the base-value comparison C wrappers (Ever_eq_<basesym>_<temp>).
    # It equals the SQL base type for every family EXCEPT trgeometry, whose base
    # comparison is against a `geometry` (SQL type) but whose wrapper stem is `geo`.
    basesym = sub.get("basesym", sub["base"])
    body = (tmpl.replace("{TEMP}", sub["temp"])
                .replace("{BASESYM}", basesym)
                .replace("{BASE}", sub["base"])
                .replace("{CBASE}", cbase)
                .replace("{BRIEF}", sub["brief"])
                .replace("{BOUNDARY}", boundary))
    return BANNER.format(tmpl=f"{behaviour}.sql.tmpl") + body


# --- C boxops (box-type axis) --------------------------------------------
# The bounding-box topological operator wrappers are generated per BOX TYPE
# (stbox/tbox/tstzspan/tpcbox) into the region between these markers, which live
# inside a hand-written .c file that also holds non-generated helpers (trajectory
# tiling, NAD, ...). Only the marked region is owned by the generator.
def _boxops_markers(box: str):
    """BEGIN/END markers keyed by box type, so one file can host several
    generated regions (temporal_boxops.c holds both tstzspan and tbox)."""
    begin = (f"/* GENERATED-BOXOPS-BEGIN {box} — tools/codegen/inherited/generate.py "
             "from templates/boxops.c.tmpl; DO NOT EDIT BY HAND;\n"
             " * edit the template + manifest.yaml (boxtypes) and re-run. */\n")
    return begin, f"/* GENERATED-BOXOPS-END {box} */\n"
# The template defines one implementation per OP (overlaps/contains/contained/
# same/adjacent) as three "direction kinds", reused across every box type:
#   0 = box-first    Boxop_{BOX}_{TSIDE}   dispatch {DISPBOX}  (INVERT)
#   1 = tside-first  Boxop_{TSIDE}_{BOX}   dispatch {DISPBOX}  (INVERT_NO)
#   2 = tside-tside  Boxop_{TSIDE}_{TSIDE} dispatch {DISPTT}
# A box type is a LIST of directions. A plain box (stbox/tpcbox/tstzspan) has the
# three template directions. A composite box (tbox) whose value dimension is a
# span<T> prepends a `valspan` sub-block — its 2 box-directions (numspan_tnumber,
# tnumber_numspan) dispatch on span primitives — before its own 3 box-directions.
# This is the single generation mechanism for {tstzspan, stbox, tpcbox, tbox, …}.


def _boxops_blocks():
    """boxops.c.tmpl split on blank lines: [header], 3 dispatchers (kinds 0/1/2),
    then per op [banner, wrap0, wrap1, wrap2], [trailer]. Roundtrips exactly."""
    blocks = (TEMPLATES / "boxops.c.tmpl").read_text().split("\n\n")
    header, trailer = blocks[0], blocks[-1]
    dispatch = blocks[1:4]
    ops = [(blocks[4 + i * 4], blocks[5 + i * 4:8 + i * 4]) for i in range(5)]
    return header, dispatch, ops, trailer


def _boxops_directions(bt: dict) -> list:
    """Ordered directions for a box type: an optional value-span sub-block (kinds
    0,1 on span primitives) followed by the box's own 3 directions (kinds 0,1,2)."""
    dirs = []
    vs = bt.get("valspan")
    if vs:
        dirs += [{**vs, "kind": k} for k in (0, 1)]
    dirs += [{**bt, "kind": k} for k in (0, 1, 2)]
    return dirs


def _boxops_sub(fragment: str, d: dict, bt: dict) -> str:
    """Substitute the per-direction tokens into one template block. {PRIM} is the
    box name for a self-contained box (overlaps_stbox_stbox) but differs for a
    span<T> instance (overlaps_span_span for tstzspan/numspan) — defaults to box."""
    vals = {
        "BOX": d["box"], "BOXC": d["boxc"], "GETARG": d["getarg"],
        "PRIM": d.get("prim", d["box"]),
        "DISPBOX": d.get("dispbox", ""), "DISPTT": d.get("disptt", bt.get("disptt", "")),
        "BOXDESC": d.get("boxdesc", bt["boxdesc"]),
        "BOXDESCPL": d.get("boxdescpl", bt["boxdescpl"]),
        "TSIDE": bt["tside"], "VALDESC": bt["valdesc"], "INGROUP": bt["ingroup"],
    }
    for k, v in vals.items():
        fragment = fragment.replace("{" + k + "}", v)
    return fragment


def render_boxops(bt: dict) -> str:
    header, dispatch, ops, trailer = _boxops_blocks()
    dirs = _boxops_directions(bt)
    out = [header]
    out += [_boxops_sub(dispatch[d["kind"]], d, bt) for d in dirs]
    for banner, wraps in ops:
        out.append(banner)
        out += [_boxops_sub(wraps[d["kind"]], d, bt) for d in dirs]
    out.append(trailer)
    return "\n\n".join(out)


def splice_boxops(filetext: str, box: str, rendered: str) -> str:
    """Replace the text strictly between the box's BEGIN/END markers with `rendered`."""
    begin, end = _boxops_markers(box)
    b = filetext.index(begin) + len(begin)
    e = filetext.index(end)
    return filetext[:b] + rendered + filetext[e:]


def extract_boxops(filetext: str, box: str) -> str:
    """Return the current text between the box's BEGIN/END markers (for --validate)."""
    begin, end = _boxops_markers(box)
    b = filetext.index(begin) + len(begin)
    e = filetext.index(end)
    return filetext[b:e]


# --- C spatialrels (predicate axis) --------------------------------------
# The ever/always PG wrapper surface (E<Rel>/A<Rel>_<dir> + @sqlfn) is generated
# per FAMILY into the region between the GENERATED-SPATIALRELS markers of a
# hand-written .c file (mirroring boxops). Each predicate contributes a section
# banner + one wrapper block per (direction, quantifier); every block just
# dispatches to the hand-written MEOS ea_<rel>_<dir> kernel with EVER/ALWAYS, so
# the whole surface is 100% mechanical from (predicate, quantifier, direction) —
# which makes a missing overload or a wrong-direction/quantifier tag impossible.
def _spatialrels_markers(family: str):
    begin = (f"/* GENERATED-SPATIALRELS-BEGIN {family} — "
             "tools/codegen/inherited/generate.py from templates/spatialrels.c.tmpl;\n"
             " * DO NOT EDIT BY HAND; edit the template + manifest.yaml "
             "(spatialrel_families) and re-run. */\n")
    return begin, f"/* GENERATED-SPATIALRELS-END {family} */\n"


# The three ever/always directions in file order and the generic PG dispatcher
# each maps to. Each direction emits an EVER then ALWAYS wrapper; the @brief noun
# phrase is per-predicate (transitive "X contains Y" vs symmetric "X and Y are
# disjoint"), so it comes from the manifest `briefs` map, not a shared subj/obj.
# A predicate may restrict itself to a subset of directions (`directions:`), swap
# the dispatcher (`disp:`, e.g. dwithin's EA_dwithin_* which carries a distance),
# and pin one MEOS kernel across both arg orders (`meos_fixed:`, dwithin's
# ea_dwithin_tgeo_geo) — every other predicate uses the defaults below.
_SR_ORDER = ["geo_tgeo", "tgeo_geo", "tgeo_tgeo"]
_SR_DISP = {
    "geo_tgeo":  "EA_spatialrel_geo_tspatial",
    "tgeo_geo":  "EA_spatialrel_tspatial_geo",
    "tgeo_tgeo": "EA_spatialrel_tspatial_tspatial",
}


def _wrap_brief(text: str, width: int = 80) -> str:
    """Greedy word-wrap a @brief string to the 80-column house style. The first
    line carries the ` * @brief ` prefix, continuation lines ` * `; returns the
    text to substitute for {BRIEF} (continuation lines already prefixed)."""
    first, cont = " * @brief ", " * "
    lines, cur, prefix = [], "", first
    for w in text.split(" "):
        cand = w if not cur else cur + " " + w
        if len(prefix) + len(cand) <= width:
            cur = cand
        else:
            lines.append(cur)
            cur, prefix = w, cont
    lines.append(cur)
    return lines[0] + "".join("\n" + cont + l for l in lines[1:])


def render_spatialrels(fam: dict) -> str:
    """Render the ever/always PG wrapper region for one family: per predicate a
    banner + wrapper blocks (one per direction x ever/always). Roundtrips exactly."""
    banner_t, block_t = (TEMPLATES / "spatialrels.c.tmpl").read_text().split("\n\n")
    block_t = block_t.rstrip("\n")
    # A family whose type is not tgeo (e.g. tcbuffer) overrides the geo defaults:
    # its own @ingroup (mobilitydb_<fam>_rel_ever), its own direction order (the
    # cbuffer 5-direction shape adds the base-value directions), and its own
    # dispatcher map. contains/covers/... inherit these; a predicate may still
    # subset the directions or swap one dispatcher.
    ingroup = fam.get("ingroup", "mobilitydb_geo_rel_ever")
    order = fam.get("order", _SR_ORDER)
    disp_map = fam.get("disp", _SR_DISP)
    out = []
    for pred in fam["predicates"]:
        out.append(banner_t.replace("{BANNER}", pred["banner"]))
        disp_over = pred.get("disp", {})
        meos_fixed = pred.get("meos_fixed")
        for direc in pred.get("directions", order):
            disp = disp_over.get(direc, disp_map[direc])
            meos = meos_fixed or f"ea_{pred['rel']}_{direc}"
            for ea, word, low in (("E", "ever", "e"), ("A", "always", "a")):
                brief = _wrap_brief(
                    "Return true if " + pred["briefs"][direc].replace("{word}", word))
                # The return statement wraps to the 80-column house style when the
                # dispatcher + kernel names are long (the cbuffer base-value
                # directions); the geo directions stay on one line unchanged.
                eaq = "EVER" if ea == "E" else "ALWAYS"
                ret = f"  return {disp}(fcinfo, &{meos}, {eaq});"
                if len(ret) > 80:
                    ret = f"  return {disp}(fcinfo, &{meos},\n    {eaq});"
                sub = {
                    "FN": f"{ea}{pred['rel']}_{direc}",
                    "BRIEF": brief,
                    "SQLFN": f"{low}{pred['Rel']}",
                    "RETURN": ret,
                    "INGROUP": ingroup,
                }
                frag = block_t
                for k, v in sub.items():
                    frag = frag.replace("{" + k + "}", v)
                out.append(frag)
    # Trailing newline so the region ends "}\n" before the END marker line
    # (mirrors the boxops convention where the region content ends with "\n").
    return "\n\n".join(out) + "\n"


def splice_spatialrels(filetext: str, family: str, rendered: str) -> str:
    begin, end = _spatialrels_markers(family)
    b = filetext.index(begin) + len(begin)
    e = filetext.index(end)
    return filetext[:b] + rendered + filetext[e:]


def extract_spatialrels(filetext: str, family: str) -> str:
    begin, end = _spatialrels_markers(family)
    b = filetext.index(begin) + len(begin)
    e = filetext.index(end)
    return filetext[b:e]


# --- SQL accessors (per-family, region-in-file) --------------------------
# The Temporal<T> accessor surface (tempSubtype..segments) is declared INLINE in
# each family's type file (052_tgeo, 202_tcbuffer, ...), not a separate numbered
# file. It follows ONE canonical order for every temporal type — the order of the
# "Accessors" <sect1> in doc/temporal_types_p1.xml — so a single generic template
# (templates/accessors.sql.tmpl) emits the whole block; the only per-family
# variation is the tokens {TEMP} (the temporal type), {BASE} (its base value type)
# and {BASESET} (the base value-collection type). The generator emits the region
# between the GENERATED-ACCESSORS markers in `file`. `reference: true` = the
# committed region must self-regenerate byte-for-byte.
def _accessors_markers(family: str):
    begin = (f"-- GENERATED-ACCESSORS-BEGIN {family} — "
             "tools/codegen/inherited/generate.py from templates/accessors.sql.tmpl;\n"
             "-- DO NOT EDIT BY HAND; edit the template + manifest.yaml "
             "(accessor_families) and re-run.\n")
    return begin, f"-- GENERATED-ACCESSORS-END {family}\n"


def render_accessors(fam: dict) -> str:
    """Render the accessor region for one family from its per-base-type `types`
    table. ONE renderer serves every family: a spatial subtype is a single-element
    `types` (one function per accessor, and — carrying no numeric/orderable flag —
    none of the gated TNumber accessors), the base Temporal<T> is all five base
    types. An old {temp/base/baseset} family is normalized to a one-element table,
    so this reproduces the merged subtype regions byte-for-byte. Groups are emitted
    accessor-outer / type-inner and separated by one blank line; the gated accessors
    slot in at their canonical positions for the types that carry them."""
    types = fam.get("types") or [{"temp": fam["temp"],
                                  "base": fam.get("base", ""),
                                  "baseset": fam.get("baseset", "")}]
    pools = {"numeric": [t for t in types if t.get("numeric")],
             "orderable": [t for t in types if t.get("orderable")]}
    groups = []
    for comment, fns, name in _accessor_blocks((TEMPLATES / "accessors.sql.tmpl").read_text()):
        groups.append(_render_group(comment, fns, types))
        for gname in _GATED_AFTER.get(name, []):
            groups.append(_render_group("", _GATED[gname], pools[_GATED_PRESENCE[gname]]))
    return "\n" + "\n\n".join(g for g in groups if g) + "\n"


# --- SQL accessors: base Temporal<T> multi-base-type mode ----------------
# The base type file (022_temporal) declares the SAME accessor surface, but for
# EVERY base type (tbool/tint/tbigint/tfloat/ttext) in one region, grouped
# accessor-outer / type-inner (all types' getValue, then all types' getTimestamp,
# ...). It also carries the TNumber/orderable-only accessors that the spatial
# subtypes lack: valueSet (the discrete value set, numeric only), minValue/maxValue
# (orderable), avgValue (numeric) and minInstant/maxInstant (orderable). These are
# emitted from the same canonical order as the shared template, with the gated
# accessors slotted at their canonical positions (valueSet with the value-collection
# group after getValues; the value/instant reductions after valueN, before
# valueAtTimestamp — doc/temporal_alpha.xml `talpha_accessors`). A `temporal` family
# in the manifest carries `types:` (a per-base-type token table) instead of the
# single {TEMP}/{BASE}/{BASESET}, which selects this multi-type renderer.
#
# The gated fragments are NOT in the shared subtype template (the spatial families
# have none of them), so they live here as literal blocks with their own tokens:
# {VSET} = the discrete value-set type (intset/bigintset/floatset). getValue/
# startValue/endValue/valueN/valueAtTimestamp/minValue/maxValue all return {BASE};
# avgValue returns float; minInstant/maxInstant return {TEMP}.
_GATED = {
    "valueSet": ("CREATE FUNCTION valueSet({TEMP})\n"
                 "  RETURNS {VSET}\n"
                 "  AS 'MODULE_PATHNAME', 'Temporal_valueset'\n"
                 "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;"),
    "minValue": ("CREATE FUNCTION minValue({TEMP})\n"
                 "  RETURNS {BASE}\n"
                 "  AS 'MODULE_PATHNAME', 'Temporal_min_value'\n"
                 "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;"),
    "maxValue": ("CREATE FUNCTION maxValue({TEMP})\n"
                 "  RETURNS {BASE}\n"
                 "  AS 'MODULE_PATHNAME', 'Temporal_max_value'\n"
                 "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;"),
    "avgValue": ("CREATE FUNCTION avgValue({TEMP})\n"
                 "  RETURNS float\n"
                 "  AS 'MODULE_PATHNAME', 'Tnumber_avg_value'\n"
                 "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;"),
    "minInstant": ("CREATE FUNCTION minInstant({TEMP})\n"
                   "  RETURNS {TEMP}\n"
                   "  AS 'MODULE_PATHNAME', 'Temporal_min_instant'\n"
                   "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;"),
    "maxInstant": ("CREATE FUNCTION maxInstant({TEMP})\n"
                   "  RETURNS {TEMP}\n"
                   "  AS 'MODULE_PATHNAME', 'Temporal_max_instant'\n"
                   "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;"),
}
# Which base types carry each gated accessor: `numeric` = tint/tbigint/tfloat
# (a type entry sets numeric: true), `orderable` = those + ttext (orderable: true).
_GATED_PRESENCE = {
    "valueSet": "numeric", "avgValue": "numeric",
    "minValue": "orderable", "maxValue": "orderable",
    "minInstant": "orderable", "maxInstant": "orderable",
}
# Gated accessors inserted AFTER the named common accessor's group, in order.
_GATED_AFTER = {
    "getValues": ["valueSet"],
    "valueN": ["minValue", "maxValue", "avgValue", "minInstant", "maxInstant"],
}


def _accessor_blocks(template_text: str):
    """Split the shared template into ordered groups. Each group is
    (lead_comment, fn_text, first_fn_name): the leading ``-- ...`` comment lines
    (emitted once per group) and the CREATE FUNCTION body/bodies (one, or the
    tempSubtype+tempBasetype pair) that repeat per base type."""
    groups = []
    for blk in template_text.strip("\n").split("\n\n"):
        lines = blk.split("\n")
        comment = "\n".join(l for l in lines if l.startswith("--"))
        fns = "\n".join(l for l in lines if not l.startswith("--"))
        name = next((l.split("(")[0].removeprefix("CREATE FUNCTION ").strip()
                     for l in lines if l.startswith("CREATE FUNCTION")), "")
        groups.append((comment, fns, name))
    return groups


def _sub_type(text: str, t: dict) -> str:
    """Substitute one base type's tokens into a group/fragment body. {VSET} first
    (it is only present in valueSet), then {BASESET}, then {BASE}, then {TEMP}.
    {GVSYM} is the getValues C symbol: Temporal_valueset by default, but the value
    domain of a number is a spanset, so a numeric type overrides it (Tnumber_valuespans).
    {VALRET}/{VALSYM} are the return type and C-symbol stem of the materialized-value
    accessors (startValue/endValue/valueN/valueAtTimestamp): {BASE} via Temporal_* by
    default, but a family whose value is materialized from a companion payload overrides
    them (trgeometry re-applies the pose to its reference geometry -> geometry via
    Trgeometry_*), while getValue keeps the raw stored {BASE}."""
    return (text.replace("{VSET}", t.get("valueset", ""))
                .replace("{GVSYM}", t.get("gvsym", "Temporal_valueset"))
                .replace("{VALRET}", t.get("valret", t["base"]))
                .replace("{VALSYM}", t.get("valsym", "Temporal"))
                .replace("{BASESET}", t.get("baseset", ""))
                .replace("{BASE}", t["base"])
                .replace("{TEMP}", t["temp"]))


def _render_group(comment: str, fns: str, types: list) -> str:
    """One canonical accessor group emitted for each applicable base type, the
    lead comment printed once (house style: no blank line between the per-type
    functions within a group)."""
    if not types:
        return ""
    body = "\n".join(_sub_type(fns, t) for t in types)
    return (comment + "\n" + body) if comment else body


def splice_accessors(filetext: str, family: str, rendered: str) -> str:
    begin, end = _accessors_markers(family)
    b = filetext.index(begin) + len(begin)
    e = filetext.index(end)
    return filetext[:b] + rendered + filetext[e:]


def extract_accessors(filetext: str, family: str) -> str:
    begin, end = _accessors_markers(family)
    b = filetext.index(begin) + len(begin)
    e = filetext.index(end)
    return filetext[b:e]


def _accessor_names() -> set:
    """Every SQL function name the generated accessor region can carry: the shared
    template's functions plus the gated TNumber/orderable reductions. Used to find and
    remove the pre-existing hand-written definitions when bootstrapping a new family.
    # BINDING-HEADER-PARSE-OK: reads the SQL accessors.sql.tmpl template (not a C
    # header), exactly as render_accessors/_accessor_blocks already do; this is the
    # inherited SQL-region generator, not a catalog-consuming binding."""
    tmpl = (TEMPLATES / "accessors.sql.tmpl").read_text()
    return set(re.findall(r"CREATE FUNCTION (\w+)\(", tmpl)) | set(_GATED)


def bootstrap_accessors(filetext: str, fam: dict, rendered: str) -> str:
    """Create the GENERATED-ACCESSORS region for a family that does not have one yet,
    so adding an accessor family is fully declarative (a manifest entry) with NO
    hand-placed marker. The region is inserted where the family's FIRST canonical
    accessor is currently hand-written, and every hand-written definition of a canonical
    accessor (for the family's temporal type(s), wherever it sits in the file — e.g. a
    `valueAtTimestamp` parked in a restriction section) is removed so the region is the
    single source. Idempotent on the next run: the markers now exist, so the normal
    splice/validate path takes over."""
    temps = [t["temp"] for t in (fam.get("types") or [{"temp": fam["temp"]}])]
    names = _accessor_names()

    def block_re(name: str, temp: str):
        return re.compile(rf"^CREATE FUNCTION {re.escape(name)}\({re.escape(temp)}\b"
                          rf"[^;]*?LANGUAGE[^;]*;\n", re.S | re.M)

    first = None
    for name in names:
        for temp in temps:
            m = block_re(name, temp).search(filetext)
            if m and (first is None or m.start() < first):
                first = m.start()
    if first is None:
        raise SystemExit(f"bootstrap accessors {fam['family']}: no canonical accessor "
                         f"of {temps} found in {fam['file']}")
    prefix, rest = filetext[:first], filetext[first:]
    for name in names:
        for temp in temps:
            rest = block_re(name, temp).sub("", rest)
    rest = re.sub(r"\A\n+", "", rest)  # the region supplies its own leading blank line
    begin, end = _accessors_markers(fam["family"])
    text = prefix + begin + rendered + end + "\n" + rest
    return re.sub(r"\n\n\n+", "\n\n", text)  # tidy the blank runs left by the removals


def target_path(behaviour: str, sub: dict, positions: dict) -> pathlib.Path:
    # The within-50-bin offset defaults to the shared `positions` map (the tight
    # cbuffer-anchored layout); a family on the tgeo-aligned layout overrides a
    # behaviour's offset via a per-subtype `positions` map (rgeo: indexes at +23).
    pos = {**positions, **sub.get("positions", {})}
    num = sub["bin"] + pos[behaviour]
    # The SQL family directory defaults to the base type name (quadbin, cbuffer),
    # but a family whose directory differs from its base type (h3: dir `h3`, base
    # `h3index`) overrides it with an explicit `fam`.
    fam = sub.get("fam", sub["base"])
    # The filename type token defaults to the temp type, but a family whose files
    # abbreviate it (rgeo: type `trgeometry`, files `..._trgeo_...`) overrides it
    # with an explicit `stem`.
    stem = sub.get("stem", sub["temp"])
    return ROOT / "mobilitydb" / "sql" / fam / f"{num}_{stem}_{behaviour}.in.sql"


def strip_banner(text: str) -> str:
    """Drop a leading GENERATED banner from a generated file."""
    # Lets the generated text be compared to a hand-written committed reference
    # (which has none).
    i = text.find("/*****")
    return text[i:] if i != -1 else text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="dry-run: list target paths")
    ap.add_argument("--validate", action="store_true",
                    help="regenerate reference subtypes and diff vs committed")
    ap.add_argument("--only", help="restrict to one temp type (e.g. tquadbin)")
    args = ap.parse_args()

    mf = yaml.safe_load(MANIFEST.read_text())
    positions = mf["positions"]
    subs = mf["subtypes"]
    if args.only:
        subs = [s for s in subs if s["temp"] == args.only]

    if args.validate:
        ok = True
        for sub in mf["subtypes"]:
            if not sub.get("reference"):
                continue
            for beh in sub["files"]:
                p = target_path(beh, sub, positions)
                gen = strip_banner(render(beh, sub))
                cur = p.read_text() if p.exists() else ""
                same = gen == cur
                ok = ok and same
                print(f"[{'OK ' if same else 'DIFF'}] self-regen {sub['temp']} "
                      f"{beh} -> {p.relative_to(ROOT)}")
                if not same:
                    g, c = gen.splitlines(), cur.splitlines()
                    for n, (a, b) in enumerate(zip(g, c), 1):
                        if a != b:
                            print(f"     first diff line {n}:\n       gen: {a!r}\n"
                                  f"       cur: {b!r}")
                            break
                    if len(g) != len(c):
                        print(f"     line count gen={len(g)} cur={len(c)}")
        for bt in mf.get("boxtypes", []):
            if not bt.get("reference"):
                continue
            p = ROOT / bt["file"]
            gen = render_boxops(bt)
            cur = extract_boxops(p.read_text(), bt["box"]) if p.exists() else ""
            same = gen == cur
            ok = ok and same
            print(f"[{'OK ' if same else 'DIFF'}] self-regen boxops {bt['box']} "
                  f"-> {pathlib.Path(bt['file'])}")
            if not same:
                g, c = gen.splitlines(), cur.splitlines()
                for n, (a, b) in enumerate(zip(g, c), 1):
                    if a != b:
                        print(f"     first diff line {n}:\n       gen: {a!r}\n"
                              f"       cur: {b!r}")
                        break
                if len(g) != len(c):
                    print(f"     line count gen={len(g)} cur={len(c)}")
        for fam in mf.get("spatialrel_families", []):
            if not fam.get("reference"):
                continue
            p = ROOT / fam["file"]
            gen = render_spatialrels(fam)
            cur = extract_spatialrels(p.read_text(), fam["family"]) if p.exists() else ""
            same = gen == cur
            ok = ok and same
            print(f"[{'OK ' if same else 'DIFF'}] self-regen spatialrels {fam['family']} "
                  f"-> {pathlib.Path(fam['file'])}")
            if not same:
                g, c = gen.splitlines(), cur.splitlines()
                for n, (a, b) in enumerate(zip(g, c), 1):
                    if a != b:
                        print(f"     first diff line {n}:\n       gen: {a!r}\n"
                              f"       cur: {b!r}")
                        break
                if len(g) != len(c):
                    print(f"     line count gen={len(g)} cur={len(c)}")
        for fam in mf.get("accessor_families", []):
            if not fam.get("reference"):
                continue
            p = ROOT / fam["file"]
            gen = render_accessors(fam)
            cur = extract_accessors(p.read_text(), fam["family"]) if p.exists() else ""
            same = gen == cur
            ok = ok and same
            print(f"[{'OK ' if same else 'DIFF'}] self-regen accessors {fam['family']} "
                  f"-> {pathlib.Path(fam['file'])}")
            if not same:
                g, c = gen.splitlines(), cur.splitlines()
                for n, (a, b) in enumerate(zip(g, c), 1):
                    if a != b:
                        print(f"     first diff line {n}:\n       gen: {a!r}\n"
                              f"       cur: {b!r}")
                        break
                if len(g) != len(c):
                    print(f"     line count gen={len(g)} cur={len(c)}")
        return 0 if ok else 1

    for sub in subs:
        if sub.get("reference"):
            continue
        for beh in sub["files"]:
            p = target_path(beh, sub, positions)
            if args.check:
                print(f"would write {p.relative_to(ROOT)}")
                continue
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(render(beh, sub))
            print(f"wrote {p.relative_to(ROOT)}")

    for bt in mf.get("boxtypes", []):
        if bt.get("reference"):
            continue
        p = ROOT / bt["file"]
        if args.check:
            print(f"would splice boxops {bt['box']} -> {bt['file']}")
            continue
        p.write_text(splice_boxops(p.read_text(), bt["box"], render_boxops(bt)))
        print(f"spliced boxops {bt['box']} -> {bt['file']}")

    for fam in mf.get("spatialrel_families", []):
        if fam.get("reference"):
            continue
        p = ROOT / fam["file"]
        if args.check:
            print(f"would splice spatialrels {fam['family']} -> {fam['file']}")
            continue
        p.write_text(splice_spatialrels(p.read_text(), fam["family"],
                                        render_spatialrels(fam)))
        print(f"spliced spatialrels {fam['family']} -> {fam['file']}")

    for fam in mf.get("accessor_families", []):
        p = ROOT / fam["file"]
        text = p.read_text()
        begin, _ = _accessors_markers(fam["family"])
        if begin not in text:
            # No region yet -> BOOTSTRAP it once from the manifest entry (no hand-placed
            # marker). After this the markers exist and the reference/splice path owns it.
            if args.check:
                print(f"would bootstrap accessors {fam['family']} -> {fam['file']}")
                continue
            p.write_text(bootstrap_accessors(text, fam, render_accessors(fam)))
            print(f"bootstrapped accessors {fam['family']} -> {fam['file']}")
            continue
        if fam.get("reference"):
            continue
        if args.check:
            print(f"would splice accessors {fam['family']} -> {fam['file']}")
            continue
        p.write_text(splice_accessors(text, fam["family"], render_accessors(fam)))
        print(f"spliced accessors {fam['family']} -> {fam['file']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
