#!/usr/bin/env python3
"""Inherited-behaviour SQL generator for Temporal<T> subclasses."""
# Emits the SQL surface that every TNumber<T> / TSpatial<T> subtype INHERITS via
# late binding + lifting (compops, topops, posops, spatialrels, ...). These files
# are pure wiring to the generic Tspatial_* / Temporal_* wrappers and are identical
# across families modulo the type tokens, so they are generated from one template
# per behaviour rather than hand-maintained per family (see memory
# temporal-oo-late-binding-architecture + meos-api-codegen-regularity).
#
#   python tools/codegen/inherited/generate.py            # emit new (non-reference) types
#   python tools/codegen/inherited/generate.py --check     # dry-run, list target paths
#   python tools/codegen/inherited/generate.py --validate   # self-regen reference == committed
from __future__ import annotations
import argparse
import pathlib
import sys

try:
    import yaml  # pyyaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
MANIFEST = HERE / "manifest.yaml"
TEMPLATES = HERE / "templates"

BANNER = (
    "/* GENERATED by tools/codegen/inherited/generate.py from "
    "templates/{tmpl} — DO NOT EDIT BY HAND;\n"
    " * edit the template + tools/codegen/inherited/manifest.yaml and re-run. */\n")


def apply_conditionals(text: str, sub: dict) -> str:
    """Strip ``-- @IF <flag>`` / ``-- @ENDIF`` blocks whose flag is false."""
    # The flag defaults to true in the subtype. Marker lines are always removed,
    # so a subtype with the flag on reproduces the reference byte-for-byte (e.g.
    # cbuffer keeps its scalar stbox cast; a cell-index like quadbin sets
    # scalar_stbox_cast: false to drop it).
    out, skip = [], False
    for line in text.splitlines(keepends=True):
        s = line.strip()
        if s.startswith("-- @IF "):
            skip = not sub.get(s[len("-- @IF "):].strip(), True)
            continue
        if s.startswith("-- @ENDIF"):
            skip = False
            continue
        if not skip:
            out.append(line)
    return "".join(out)


def render(behaviour: str, sub: dict) -> str:
    tmpl = apply_conditionals((TEMPLATES / f"{behaviour}.sql.tmpl").read_text(), sub)
    # The cell-boundary function name defaults to `<temp>CellToBoundary`
    # (e.g. tquadbinCellToBoundary), but the h3 family - whose cell functions carry
    # the pg-h3 name temporalized by a bare `t` prefix (h3CellToBoundary ->
    # th3CellToBoundary, NOT th3indexCellToBoundary) - overrides it via `boundary_fn`.
    boundary = sub.get("boundary_fn", sub["temp"] + "CellToBoundary")
    body = (tmpl.replace("{TEMP}", sub["temp"])
                .replace("{BASE}", sub["base"])
                .replace("{BRIEF}", sub["brief"])
                .replace("{BOUNDARY}", boundary))
    return BANNER.format(tmpl=f"{behaviour}.sql.tmpl") + body


def target_path(behaviour: str, sub: dict, positions: dict) -> pathlib.Path:
    num = sub["bin"] + positions[behaviour]
    # The SQL family directory defaults to the base type name (quadbin, cbuffer),
    # but a family whose directory differs from its base type (h3: dir `h3`, base
    # `h3index`) overrides it with an explicit `fam`.
    fam = sub.get("fam", sub["base"])
    # The filename type token defaults to the temp type, but a family whose files
    # abbreviate it (rgeo: type `trgeometry`, files `..._trgeo_...`) overrides it
    # with an explicit `stem`.
    stem = sub.get("stem", sub["temp"])
    return ROOT / "mobilitydb" / "sql" / fam / f"{num}_{stem}_{behaviour}.in.sql"


def strip_banner(text: str) -> str:
    """Drop a leading GENERATED banner from a generated file."""
    # Lets the generated text be compared to a hand-written committed reference
    # (which has none).
    i = text.find("/*****")
    return text[i:] if i != -1 else text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="dry-run: list target paths")
    ap.add_argument("--validate", action="store_true",
                    help="regenerate reference subtypes and diff vs committed")
    ap.add_argument("--only", help="restrict to one temp type (e.g. tquadbin)")
    args = ap.parse_args()

    mf = yaml.safe_load(MANIFEST.read_text())
    positions = mf["positions"]
    subs = mf["subtypes"]
    if args.only:
        subs = [s for s in subs if s["temp"] == args.only]

    if args.validate:
        ok = True
        for sub in mf["subtypes"]:
            if not sub.get("reference"):
                continue
            for beh in sub["files"]:
                p = target_path(beh, sub, positions)
                gen = strip_banner(render(beh, sub))
                cur = p.read_text() if p.exists() else ""
                same = gen == cur
                ok = ok and same
                print(f"[{'OK ' if same else 'DIFF'}] self-regen {sub['temp']} "
                      f"{beh} -> {p.relative_to(ROOT)}")
                if not same:
                    g, c = gen.splitlines(), cur.splitlines()
                    for n, (a, b) in enumerate(zip(g, c), 1):
                        if a != b:
                            print(f"     first diff line {n}:\n       gen: {a!r}\n"
                                  f"       cur: {b!r}")
                            break
                    if len(g) != len(c):
                        print(f"     line count gen={len(g)} cur={len(c)}")
        return 0 if ok else 1

    for sub in subs:
        if sub.get("reference"):
            continue
        for beh in sub["files"]:
            p = target_path(beh, sub, positions)
            if args.check:
                print(f"would write {p.relative_to(ROOT)}")
                continue
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(render(beh, sub))
            print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
