#!/usr/bin/env python3
# This MobilityDB code is provided under The PostgreSQL License.
# Copyright (c) 2016-2026, Universite libre de Bruxelles and MobilityDB
# contributors
"""Generate the SQL for the set-set spatial-join functions.

The set-set spatial joins generalise the scalar ever/always/temporal spatial
relationships to two arrays of temporal geos, returning the qualifying (i, j)
index pairs (and, for the temporal predicates, the periods during which each
pair holds).  Every SQL function is a thin wrapper over one of the twelve
type-generic C functions; the surface is therefore fully derivable from the
predicate x type matrix below, which mirrors the type coverage of the scalar
spatial relationships:

  - the within-distance, intersects, and disjoint predicates are defined for
    temporal points (tgeompoint, tgeogpoint) and temporal geometries
    (tgeometry, tgeography);
  - the touches predicate is defined for temporal geometries only (the GEOS
    DE-9IM relate matrix is planar-only, so geodetic touches is undefined);
  - the temporal within-distance predicate is defined for the planar types
    only (tgeompoint, tgeometry).

Run this script from the repository root to regenerate the two output files in
mobilitydb/sql/geo/.  Do not edit the generated files by hand.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
OUTDIR = os.path.join(ROOT, "mobilitydb", "sql", "geo")

HEADER = (
    "/*****************************************************************************\n"
    " *\n"
    " * This MobilityDB code is provided under The PostgreSQL License.\n"
    " * Copyright (c) 2016-2026, Universite libre de Bruxelles and MobilityDB\n"
    " * contributors\n"
    " *\n"
    " * MobilityDB includes portions of PostGIS version 3 source code released\n"
    " * under the GNU General Public License (GPLv2 or later).\n"
    " * Copyright (c) 2001-2025, PostGIS contributors\n"
    " *\n"
    " * Permission to use, copy, modify, and distribute this software and its\n"
    " * documentation for any purpose, without fee, and without a written\n"
    " * agreement is hereby granted, provided that the above copyright notice and\n"
    " * this paragraph and the following two paragraphs appear in all copies.\n"
    " *\n"
    " * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR\n"
    " * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING\n"
    " * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,\n"
    " * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY\n"
    " * OF SUCH DAMAGE.\n"
    " *\n"
    " * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,\n"
    " * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY\n"
    " * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON\n"
    " * AN \"AS IS\" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO\n"
    " * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
    " *\n"
    " *****************************************************************************/\n"
    "\n"
    "/**\n"
    " * @file\n"
    " * @brief Set-set spatial-join functions for temporal %s.\n"
    " *\n"
    " * GENERATED by tools/setset_join/generate.py -- DO NOT EDIT.\n"
    " * Each function is a thin wrapper over a type-generic C kernel; the surface\n"
    " * mirrors the type coverage of the scalar spatial relationships.\n"
    " */\n"
)

# (SQL name, C wrapper, has_dist)
EA = [
    ("eDwithinPairs", "Edwithin_tgeoarr_tgeoarr", True),
    ("aDwithinPairs", "Adwithin_tgeoarr_tgeoarr", True),
    ("eIntersectsPairs", "Eintersects_tgeoarr_tgeoarr", False),
    ("aIntersectsPairs", "Aintersects_tgeoarr_tgeoarr", False),
    ("eDisjointPairs", "Edisjoint_tgeoarr_tgeoarr", False),
    ("aDisjointPairs", "Adisjoint_tgeoarr_tgeoarr", False),
]
EA_TOUCHES = [
    ("eTouchesPairs", "Etouches_tgeoarr_tgeoarr", False),
    ("aTouchesPairs", "Atouches_tgeoarr_tgeoarr", False),
]
T_DWITHIN = ("tDwithinPairs", "Tdwithin_tgeoarr_tgeoarr", True)
T_BOTH = [
    ("tIntersectsPairs", "Tintersects_tgeoarr_tgeoarr", False),
    ("tDisjointPairs", "Tdisjoint_tgeoarr_tgeoarr", False),
]
T_TOUCHES = ("tTouchesPairs", "Ttouches_tgeoarr_tgeoarr", False)


def emit(name, T, wrapper, dist, periods):
    args = "%s[], %s[]" % (T, T)
    if dist:
        args += ", dist float"
    outs = "OUT i integer, OUT j integer"
    if periods:
        outs += ", OUT periods tstzspanset"
    return (
        "CREATE FUNCTION %s(%s,\n    %s)\n"
        "  RETURNS setof record\n"
        "  AS 'MODULE_PATHNAME', '%s'\n"
        "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;\n" % (name, args, outs, wrapper)
    )


def base_geo(T):
    """Return the static geometry type matching a temporal geo type."""
    return "geography" if T in ("tgeogpoint", "tgeography") else "geometry"


def mindist_functions(types):
    """Emit the set-set minDistance forms for the given temporal geo types.

    The forms are the array-to-array minimum distance, the scalar overloads
    against a static geometry (which reduce to the nearest-approach distance),
    and the 2-ary aggregate over pairs of temporal values.
    """
    fns = []
    for T in types:
        fns.append(
            "CREATE FUNCTION minDistance(%s[], %s[])\n"
            "  RETURNS float\n"
            "  AS 'MODULE_PATHNAME', 'Mindistance_tgeoarr_tgeoarr'\n"
            "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;\n" % (T, T)
        )
    for T in types:
        geo = base_geo(T)
        fns.append(
            "CREATE FUNCTION minDistance(%s, %s)\n"
            "  RETURNS float\n"
            "  AS 'MODULE_PATHNAME', 'NAD_tgeo_geo'\n"
            "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;\n"
            "CREATE FUNCTION minDistance(%s, %s)\n"
            "  RETURNS float\n"
            "  AS 'MODULE_PATHNAME', 'NAD_geo_tgeo'\n"
            "  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;\n" % (T, geo, geo, T)
        )
    for T in types:
        fns.append(
            "CREATE FUNCTION minDistance_transfn(float, %s, %s)\n"
            "  RETURNS float\n"
            "  AS 'MODULE_PATHNAME', 'Mindistance_transfn'\n"
            "  LANGUAGE C IMMUTABLE PARALLEL SAFE;\n"
            "CREATE AGGREGATE minDistance(%s, %s) (\n"
            "  SFUNC = minDistance_transfn,\n"
            "  STYPE = float,\n"
            "  COMBINEFUNC = float8smaller,\n"
            "  PARALLEL = SAFE\n"
            ");\n" % (T, T, T, T)
        )
    return fns


def point_functions():
    fns = mindist_functions(("tgeompoint", "tgeogpoint"))
    # ever / always: dwithin, intersects, disjoint over both point types
    for T in ("tgeompoint", "tgeogpoint"):
        for n, w, d in EA:
            fns.append(emit(n, T, w, d, False))
    # temporal: dwithin (planar point only), intersects and disjoint (both)
    fns.append(emit(T_DWITHIN[0], "tgeompoint", T_DWITHIN[1], True, True))
    for T in ("tgeompoint", "tgeogpoint"):
        for n, w, d in T_BOTH:
            fns.append(emit(n, T, w, d, True))
    return fns


def geo_functions():
    fns = mindist_functions(("tgeometry", "tgeography"))
    # ever / always: dwithin, intersects, disjoint over both geo types
    for T in ("tgeometry", "tgeography"):
        for n, w, d in EA:
            fns.append(emit(n, T, w, d, False))
    # touches: geometry only
    for n, w, d in EA_TOUCHES:
        fns.append(emit(n, "tgeometry", w, d, False))
    # temporal: dwithin (planar geometry only), intersects and disjoint (both),
    # touches (geometry only)
    fns.append(emit(T_DWITHIN[0], "tgeometry", T_DWITHIN[1], True, True))
    for T in ("tgeometry", "tgeography"):
        for n, w, d in T_BOTH:
            fns.append(emit(n, T, w, d, True))
    fns.append(emit(T_TOUCHES[0], "tgeometry", T_TOUCHES[1], False, True))
    return fns


def write_file(basename, label, fns):
    path = os.path.join(OUTDIR, basename)
    body = HEADER % label + "\n" + "\n".join(fns)
    with open(path, "w") as fh:
        fh.write(body)
    return path, len(fns)


def main():
    total = 0
    for path, n in (
        write_file("071_tpoint_setset.in.sql", "points", point_functions()),
        write_file("071_tgeo_setset.in.sql", "geometries", geo_functions()),
    ):
        print("%s: %d functions" % (os.path.basename(path), n))
        total += n
    print("total: %d functions" % total)


if __name__ == "__main__":
    main()
