var searchData=
[
  ['functions_20for_20base_20and_20time_20types_0',['Functions for base and time types',['../group__meos__base__types.html',1,'']]],
  ['functions_20for_20box_20types_1',['Functions for box types',['../group__mobilitydb__box.html',1,'']]],
  ['functions_20for_20circular_20buffer_20sets_2',['Functions for circular buffer sets',['../group__meos__cbuffer__set.html',1,'(Global Namespace)'],['../group__meos__internal__cbuffer__set.html',1,'(Global Namespace)'],['../group__mobilitydb__cbuffer__set.html',1,'(Global Namespace)']]],
  ['functions_20for_20geometry_20sets_3',['Functions for geometry sets',['../group__meos__internal__geo__set.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__set.html',1,'(Global Namespace)']]],
  ['functions_20for_20json_20sets_4',['Functions for JSON sets',['../group__meos__json__set.html',1,'(Global Namespace)'],['../group__mobilitydb__json__set.html',1,'(Global Namespace)']]],
  ['functions_20for_20network_20point_20sets_5',['Functions for network point sets',['../group__meos__internal__npoint__set.html',1,'(Global Namespace)'],['../group__meos__npoint__set.html',1,'(Global Namespace)'],['../group__mobilitydb__npoint__set.html',1,'(Global Namespace)']]],
  ['functions_20for_20pcpointset_20_2f_20pcpatchset_6',['Functions for pcpointset / pcpatchset',['../group__meos__pointcloud__set.html',1,'']]],
  ['functions_20for_20pose_20sets_7',['Functions for pose sets',['../group__meos__internal__pose__set.html',1,'(Global Namespace)'],['../group__meos__pose__set.html',1,'(Global Namespace)'],['../group__mobilitydb__pose__set.html',1,'(Global Namespace)']]],
  ['functions_20for_20set_20and_20span_20types_8',['Functions for set and span types',['../group__meos__internal__setspan.html',1,'(Global Namespace)'],['../group__meos__setspan.html',1,'(Global Namespace)'],['../group__mobilitydb__setspan.html',1,'(Global Namespace)']]],
  ['functions_20for_20spatial_20sets_9',['Functions for spatial sets',['../group__meos__geo__set.html',1,'']]],
  ['functions_20for_20spatiotemporal_20boxes_10',['Functions for spatiotemporal boxes',['../group__meos__geo__box.html',1,'(Global Namespace)'],['../group__meos__internal__geo__box.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__box.html',1,'(Global Namespace)']]],
  ['functions_20for_20static_20circular_20buffers_11',['Functions for static circular buffers',['../group__meos__cbuffer__base.html',1,'(Global Namespace)'],['../group__meos__internal__cbuffer__base.html',1,'(Global Namespace)'],['../group__mobilitydb__cbuffer__base.html',1,'(Global Namespace)']]],
  ['functions_20for_20static_20geometries_12',['Functions for static geometries',['../group__meos__geo__base.html',1,'(Global Namespace)'],['../group__meos__internal__geo__base.html',1,'(Global Namespace)']]],
  ['functions_20for_20static_20h3_20cell_20indices_13',['Functions for static H3 cell indices',['../group__meos__h3__base.html',1,'(Global Namespace)'],['../group__mobilitydb__h3__base.html',1,'(Global Namespace)']]],
  ['functions_20for_20static_20json_20types_14',['Functions for static JSON types',['../group__meos__json__base.html',1,'']]],
  ['functions_20for_20static_20network_20points_15',['Functions for static network points',['../group__meos__internal__npoint__base.html',1,'(Global Namespace)'],['../group__meos__npoint__base.html',1,'(Global Namespace)'],['../group__mobilitydb__npoint__base.html',1,'(Global Namespace)']]],
  ['functions_20for_20static_20pcpoint_20_2f_20pcpatch_16',['Functions for static pcpoint / pcpatch',['../group__meos__pointcloud__base.html',1,'']]],
  ['functions_20for_20static_20poses_17',['Functions for static poses',['../group__meos__internal__pose__base.html',1,'(Global Namespace)'],['../group__meos__pose__base.html',1,'(Global Namespace)'],['../group__mobilitydb__pose__base.html',1,'(Global Namespace)']]],
  ['functions_20for_20temporal_20boxes_18',['Functions for temporal boxes',['../group__meos__box.html',1,'(Global Namespace)'],['../group__meos__internal__box.html',1,'(Global Namespace)']]],
  ['functions_20for_20temporal_20circular_20buffers_19',['Functions for temporal circular buffers',['../group__meos__cbuffer.html',1,'(Global Namespace)'],['../group__meos__internal__cbuffer.html',1,'(Global Namespace)'],['../group__mobilitydb__cbuffer.html',1,'(Global Namespace)']]],
  ['functions_20for_20temporal_20geometries_20',['Functions for temporal geometries',['../group__meos__geo.html',1,'(Global Namespace)'],['../group__meos__internal__geo.html',1,'(Global Namespace)'],['../group__mobilitydb__geo.html',1,'(Global Namespace)']]],
  ['functions_20for_20temporal_20json_20types_21',['Functions for temporal JSON types',['../group__meos__json.html',1,'']]],
  ['functions_20for_20temporal_20network_20points_22',['Functions for temporal network points',['../group__meos__internal__npoint.html',1,'(Global Namespace)'],['../group__meos__npoint.html',1,'(Global Namespace)'],['../group__mobilitydb__npoint.html',1,'(Global Namespace)']]],
  ['functions_20for_20temporal_20pgpointcloud_20types_23',['Functions for temporal pgpointcloud types',['../group__meos__pointcloud.html',1,'(Global Namespace)'],['../group__mobilitydb__pointcloud.html',1,'(Global Namespace)']]],
  ['functions_20for_20temporal_20poses_24',['Functions for temporal poses',['../group__meos__internal__pose.html',1,'(Global Namespace)'],['../group__meos__pose.html',1,'(Global Namespace)'],['../group__mobilitydb__pose.html',1,'(Global Namespace)']]],
  ['functions_20for_20temporal_20rigid_20geometries_25',['Functions for temporal rigid geometries',['../group__meos__internal__rgeo.html',1,'(Global Namespace)'],['../group__meos__rgeo.html',1,'(Global Namespace)'],['../group__mobilitydb__rgeo.html',1,'(Global Namespace)']]],
  ['functions_20for_20temporal_20types_26',['Functions for temporal types',['../group__meos__internal__temporal.html',1,'(Global Namespace)'],['../group__meos__temporal.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal.html',1,'(Global Namespace)']]],
  ['functions_20for_20the_20boolean_20type_27',['Functions for the boolean type',['../group__meos__base__bool.html',1,'']]],
  ['functions_20for_20the_20date_20type_28',['Functions for the date type',['../group__meos__base__date.html',1,'']]],
  ['functions_20for_20the_20float_20types_29',['Functions for the float types',['../group__meos__base__float.html',1,'']]],
  ['functions_20for_20the_20integer_20types_30',['Functions for the integer types',['../group__meos__base__int.html',1,'']]],
  ['functions_20for_20the_20interval_20type_31',['Functions for the interval type',['../group__meos__base__interval.html',1,'']]],
  ['functions_20for_20the_20json_20types_32',['Functions for the JSON types',['../group__meos__base__json.html',1,'']]],
  ['functions_20for_20the_20numeric_20type_33',['Functions for the numeric type',['../group__meos__base__numeric.html',1,'']]],
  ['functions_20for_20the_20text_20type_34',['Functions for the text type',['../group__meos__base__text.html',1,'']]],
  ['functions_20for_20the_20time_20type_35',['Functions for the time type',['../group__meos__base__time.html',1,'']]],
  ['functions_20for_20the_20timestamp_20types_36',['Functions for the timestamp types',['../group__meos__base__timestamp.html',1,'']]],
  ['functions_20for_20the_20tpcbox_20bounding_2dbox_20type_37',['Functions for the TPCBox bounding-box type',['../group__meos__pointcloud__box.html',1,'']]]
];
