var searchData=
[
  ['temporal_20comparison_20functions_0',['Temporal comparison functions',['../group__meos__internal__temporal__comp__temp.html',1,'(Global Namespace)'],['../group__meos__temporal__comp__temp.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__comp__temp.html',1,'(Global Namespace)']]],
  ['temporal_20spatial_20relationship_20functions_1',['Temporal spatial relationship functions',['../group__meos__temporal__spatial__rel__temp.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__spatial__rel__temp.html',1,'(Global Namespace)']]],
  ['text_20functions_2',['Text functions',['../group__meos__temporal__text.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__text.html',1,'(Global Namespace)']]],
  ['tile_20functions_3',['Tile functions',['../group__meos__temporal__analytics__tile.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__analytics__tile.html',1,'(Global Namespace)']]],
  ['topological_20functions_4',['Topological functions',['../group__meos__box__bbox__topo.html',1,'(Global Namespace)'],['../group__meos__internal__setspan__topo.html',1,'(Global Namespace)'],['../group__meos__setspan__topo.html',1,'(Global Namespace)'],['../group__meos__temporal__bbox__topo.html',1,'(Global Namespace)'],['../group__mobilitydb__box__topo.html',1,'(Global Namespace)'],['../group__mobilitydb__setspan__topo.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__bbox__topo.html',1,'(Global Namespace)']]],
  ['traditional_20comparison_20functions_5',['Traditional comparison functions',['../group__meos__internal__temporal__comp__trad.html',1,'(Global Namespace)'],['../group__meos__temporal__comp__trad.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__comp__trad.html',1,'(Global Namespace)']]],
  ['transformation_20functions_6',['Transformation functions',['../group__meos__box__transf.html',1,'(Global Namespace)'],['../group__meos__internal__box__transf.html',1,'(Global Namespace)'],['../group__meos__internal__setspan__transf.html',1,'(Global Namespace)'],['../group__meos__internal__temporal__transf.html',1,'(Global Namespace)'],['../group__meos__setspan__transf.html',1,'(Global Namespace)'],['../group__meos__temporal__transf.html',1,'(Global Namespace)'],['../group__mobilitydb__box__transf.html',1,'(Global Namespace)'],['../group__mobilitydb__setspan__transf.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__transf.html',1,'(Global Namespace)']]]
];
