var searchData=
[
  ['schema_20cache_20helpers_0',['Schema cache helpers',['../group__meos__pointcloud__schema__cache.html',1,'']]],
  ['set_20functions_1',['Set functions',['../group__meos__box__set.html',1,'(Global Namespace)'],['../group__meos__geo__box__set.html',1,'(Global Namespace)'],['../group__meos__internal__box__set.html',1,'(Global Namespace)'],['../group__meos__internal__geo__box__set.html',1,'(Global Namespace)'],['../group__meos__internal__setspan__set.html',1,'(Global Namespace)'],['../group__meos__setspan__set.html',1,'(Global Namespace)'],['../group__mobilitydb__box__set.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__box__set.html',1,'(Global Namespace)'],['../group__mobilitydb__setspan__set.html',1,'(Global Namespace)']]],
  ['set_20operations_2',['Set operations',['../group__meos__cbuffer__set__setops.html',1,'(Global Namespace)'],['../group__meos__geo__set__setops.html',1,'(Global Namespace)'],['../group__meos__internal__cbuffer__set__setops.html',1,'(Global Namespace)'],['../group__meos__internal__geo__set__setops.html',1,'(Global Namespace)'],['../group__meos__internal__npoint__set__setops.html',1,'(Global Namespace)'],['../group__meos__internal__pose__set__setops.html',1,'(Global Namespace)'],['../group__meos__json__set__setops.html',1,'(Global Namespace)'],['../group__meos__npoint__set__setops.html',1,'(Global Namespace)'],['../group__meos__pointcloud__box__setops.html',1,'(Global Namespace)'],['../group__meos__pointcloud__set__setops.html',1,'(Global Namespace)'],['../group__meos__pose__set__setops.html',1,'(Global Namespace)'],['../group__mobilitydb__pointcloud__box__setops.html',1,'(Global Namespace)']]],
  ['set_2dreturning_20functions_3',['Set-returning functions',['../group__mobilitydb__h3__set.html',1,'']]],
  ['similarity_20functions_4',['Similarity functions',['../group__meos__temporal__analytics__similarity.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__analytics__similarity.html',1,'(Global Namespace)']]],
  ['simplification_20functions_5',['Simplification functions',['../group__meos__temporal__analytics__simplify.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__analytics__simplify.html',1,'(Global Namespace)']]],
  ['spatial_20accessor_20functions_6',['Spatial accessor functions',['../group__meos__internal__temporal__spatial__accessor.html',1,'']]],
  ['spatial_20functions_7',['Spatial functions',['../group__meos__internal__temporal__spatial.html',1,'']]],
  ['spatial_20processing_20functions_8',['Spatial processing functions',['../group__meos__geo__base__spatial.html',1,'(Global Namespace)'],['../group__meos__internal__geo__base__spatial.html',1,'(Global Namespace)']]],
  ['spatial_20reference_20system_20functions_9',['Spatial reference system functions',['../group__meos__box__srid.html',1,'(Global Namespace)'],['../group__meos__cbuffer__base__srid.html',1,'(Global Namespace)'],['../group__meos__geo__base__srid.html',1,'(Global Namespace)'],['../group__meos__geo__box__srid.html',1,'(Global Namespace)'],['../group__meos__geo__set__srid.html',1,'(Global Namespace)'],['../group__meos__geo__srid.html',1,'(Global Namespace)'],['../group__meos__internal__cbuffer__base__srid.html',1,'(Global Namespace)'],['../group__meos__internal__geo__base__srid.html',1,'(Global Namespace)'],['../group__meos__internal__geo__box__srid.html',1,'(Global Namespace)'],['../group__meos__internal__geo__srid.html',1,'(Global Namespace)'],['../group__meos__internal__pose__base__srid.html',1,'(Global Namespace)'],['../group__meos__npoint__base__srid.html',1,'(Global Namespace)'],['../group__meos__pose__base__srid.html',1,'(Global Namespace)'],['../group__meos__setspan__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__cbuffer__base__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__cbuffer__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__box__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__set__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__npoint__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__pose__base__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__pose__srid.html',1,'(Global Namespace)']]],
  ['spatial_20relationship_20functions_10',['Spatial relationship functions',['../group__meos__cbuffer__base__rel.html',1,'(Global Namespace)'],['../group__meos__cbuffer__rel.html',1,'(Global Namespace)'],['../group__meos__geo__base__rel.html',1,'(Global Namespace)'],['../group__meos__geo__rel.html',1,'(Global Namespace)'],['../group__meos__internal__cbuffer__rel.html',1,'(Global Namespace)'],['../group__meos__internal__geo__base__rel.html',1,'(Global Namespace)'],['../group__meos__internal__geo__rel.html',1,'(Global Namespace)'],['../group__meos__internal__rgeo__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__cbuffer__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__npoint__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__pose__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__rgeo__rel.html',1,'(Global Namespace)']]],
  ['spatial_20transformation_20functions_11',['Spatial transformation functions',['../group__meos__internal__temporal__spatial__transf.html',1,'']]],
  ['spatiotemporal_20relationship_20functions_12',['Spatiotemporal relationship functions',['../group__mobilitydb__cbuffer__rel__temp.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__rel__temp.html',1,'(Global Namespace)'],['../group__mobilitydb__npoint__rel__temp.html',1,'(Global Namespace)'],['../group__mobilitydb__pose__rel__temp.html',1,'(Global Namespace)'],['../group__mobilitydb__rgeo__rel__temp.html',1,'(Global Namespace)']]],
  ['split_20functions_13',['Split functions',['../group__meos__geo__bbox__split.html',1,'(Global Namespace)'],['../group__meos__setspan__bbox__split.html',1,'(Global Namespace)'],['../group__meos__temporal__bbox__split.html',1,'(Global Namespace)']]],
  ['splitting_20functions_14',['Splitting functions',['../group__mobilitydb__temporal__bbox__split.html',1,'']]],
  ['srid_20functions_15',['SRID functions',['../group__mobilitydb__npoint__base__srid.html',1,'']]]
];
