var searchData=
[
  ['set_20functions_0',['Set functions',['../group__meos__box__set.html',1,'(Global Namespace)'],['../group__meos__geo__box__set.html',1,'(Global Namespace)'],['../group__meos__internal__box__set.html',1,'(Global Namespace)'],['../group__meos__internal__geo__box__set.html',1,'(Global Namespace)'],['../group__meos__internal__setspan__set.html',1,'(Global Namespace)'],['../group__meos__setspan__set.html',1,'(Global Namespace)'],['../group__mobilitydb__box__set.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__box__set.html',1,'(Global Namespace)'],['../group__mobilitydb__setspan__set.html',1,'(Global Namespace)']]],
  ['set_20operations_1',['Set operations',['../group__meos__cbuffer__set__setops.html',1,'(Global Namespace)'],['../group__meos__geo__set__setops.html',1,'(Global Namespace)'],['../group__meos__internal__cbuffer__set__setops.html',1,'(Global Namespace)'],['../group__meos__internal__geo__set__setops.html',1,'(Global Namespace)'],['../group__meos__internal__npoint__set__setops.html',1,'(Global Namespace)'],['../group__meos__internal__pose__set__setops.html',1,'(Global Namespace)'],['../group__meos__npoint__set__setops.html',1,'(Global Namespace)'],['../group__meos__pose__set__setops.html',1,'(Global Namespace)']]],
  ['similarity_20functions_2',['Similarity functions',['../group__meos__temporal__analytics__similarity.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__analytics__similarity.html',1,'(Global Namespace)']]],
  ['simplification_20functions_3',['Simplification functions',['../group__meos__temporal__analytics__simplify.html',1,'(Global Namespace)'],['../group__mobilitydb__temporal__analytics__simplify.html',1,'(Global Namespace)']]],
  ['spatial_20accessor_20functions_4',['Spatial accessor functions',['../group__meos__internal__temporal__spatial__accessor.html',1,'']]],
  ['spatial_20functions_5',['Spatial functions',['../group__meos__internal__temporal__spatial.html',1,'']]],
  ['spatial_20processing_20functions_6',['Spatial processing functions',['../group__meos__geo__base__spatial.html',1,'(Global Namespace)'],['../group__meos__internal__geo__base__spatial.html',1,'(Global Namespace)']]],
  ['spatial_20reference_20system_20functions_7',['Spatial reference system functions',['../group__meos__box__srid.html',1,'(Global Namespace)'],['../group__meos__cbuffer__base__srid.html',1,'(Global Namespace)'],['../group__meos__geo__base__srid.html',1,'(Global Namespace)'],['../group__meos__geo__box__srid.html',1,'(Global Namespace)'],['../group__meos__geo__srid.html',1,'(Global Namespace)'],['../group__meos__internal__cbuffer__base__srid.html',1,'(Global Namespace)'],['../group__meos__internal__geo__base__srid.html',1,'(Global Namespace)'],['../group__meos__internal__geo__box__srid.html',1,'(Global Namespace)'],['../group__meos__internal__geo__srid.html',1,'(Global Namespace)'],['../group__meos__internal__pose__base__srid.html',1,'(Global Namespace)'],['../group__meos__pose__base__srid.html',1,'(Global Namespace)'],['../group__meos__setspan__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__cbuffer__base__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__cbuffer__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__box__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__set__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__npoint__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__pose__base__srid.html',1,'(Global Namespace)'],['../group__mobilitydb__pose__srid.html',1,'(Global Namespace)']]],
  ['spatial_20relationship_20functions_8',['Spatial relationship functions',['../group__meos__geo__base__rel.html',1,'(Global Namespace)'],['../group__meos__geo__rel.html',1,'(Global Namespace)'],['../group__meos__internal__geo__base__rel.html',1,'(Global Namespace)'],['../group__meos__internal__geo__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__cbuffer__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__geo__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__npoint__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__pose__rel.html',1,'(Global Namespace)'],['../group__mobilitydb__rgeo__rel.html',1,'(Global Namespace)']]],
  ['spatial_20transformation_20functions_9',['Spatial transformation functions',['../group__meos__internal__temporal__spatial__transf.html',1,'']]],
  ['splitting_20functions_10',['Splitting functions',['../group__mobilitydb__temporal__bbox__split.html',1,'']]],
  ['srid_20functions_11',['SRID functions',['../group__mobilitydb__npoint__base__srid.html',1,'']]]
];
