/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/* GENERATED by tools/codegen/inherited/generate.py from templates/compops.sql.tmpl — DO NOT EDIT BY HAND;
 * edit the template + tools/codegen/inherited/manifest.d and re-run. */

/**
 * @file
 * @brief Ever/always and temporal comparison functions and operators for
 * temporal H3 cells
 */

/*****************************************************************************
 * Ever/Always Comparison Functions
 *****************************************************************************/

CREATE FUNCTION eEqual(h3index, th3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_eq_h3index_th3index'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?= (
  LEFTARG = h3index, RIGHTARG = th3index,
  PROCEDURE = eEqual,
  NEGATOR = %<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aEqual(h3index, th3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_eq_h3index_th3index'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %= (
  LEFTARG = h3index, RIGHTARG = th3index,
  PROCEDURE = aEqual,
  NEGATOR = ?<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION eNotEqual(h3index, th3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_ne_h3index_th3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?<> (
  LEFTARG = h3index, RIGHTARG = th3index,
  PROCEDURE = eNotEqual,
  NEGATOR = %=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aNotEqual(h3index, th3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_ne_h3index_th3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %<> (
  LEFTARG = h3index, RIGHTARG = th3index,
  PROCEDURE = aNotEqual,
  NEGATOR = ?=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

/*****************************************************************************/

CREATE FUNCTION eEqual(th3index, h3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_eq_th3index_h3index'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?= (
  LEFTARG = th3index, RIGHTARG = h3index,
  PROCEDURE = eEqual,
  NEGATOR = %<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aEqual(th3index, h3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_eq_th3index_h3index'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %= (
  LEFTARG = th3index, RIGHTARG = h3index,
  PROCEDURE = aEqual,
  NEGATOR = ?<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION eNotEqual(th3index, h3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_ne_th3index_h3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?<> (
  LEFTARG = th3index, RIGHTARG = h3index,
  PROCEDURE = eNotEqual,
  NEGATOR = %=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aNotEqual(th3index, h3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_ne_th3index_h3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %<> (
  LEFTARG = th3index, RIGHTARG = h3index,
  PROCEDURE = aNotEqual,
  NEGATOR = ?=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

/*****************************************************************************/

CREATE FUNCTION eEqual(th3index, th3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_eq_th3index_th3index'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?= (
  LEFTARG = th3index, RIGHTARG = th3index,
  PROCEDURE = eEqual,
  NEGATOR = %<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aEqual(th3index, th3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_eq_th3index_th3index'
  SUPPORT tspatial_supportfn
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %= (
  LEFTARG = th3index, RIGHTARG = th3index,
  PROCEDURE = aEqual,
  NEGATOR = ?<>,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION eNotEqual(th3index, th3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Ever_ne_th3index_th3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR ?<> (
  LEFTARG = th3index, RIGHTARG = th3index,
  PROCEDURE = eNotEqual,
  NEGATOR = %=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

CREATE FUNCTION aNotEqual(th3index, th3index)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'Always_ne_th3index_th3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR %<> (
  LEFTARG = th3index, RIGHTARG = th3index,
  PROCEDURE = aNotEqual,
  NEGATOR = ?=,
  RESTRICT = tspatial_sel, JOIN = tspatial_joinsel
);

/*****************************************************************************
 * Temporal equal
 *****************************************************************************/

CREATE FUNCTION tEqual(h3index, th3index)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Teq_h3index_th3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tEqual(th3index, h3index)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Teq_th3index_h3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tEqual(th3index, th3index)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Teq_temporal_temporal'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR #= (
  PROCEDURE = tEqual,
  LEFTARG = h3index, RIGHTARG = th3index,
  COMMUTATOR = #=
);
CREATE OPERATOR #= (
  PROCEDURE = tEqual,
  LEFTARG = th3index, RIGHTARG = h3index,
  COMMUTATOR = #=
);
CREATE OPERATOR #= (
  PROCEDURE = tEqual,
  LEFTARG = th3index, RIGHTARG = th3index,
  COMMUTATOR = #=
);

/*****************************************************************************
 * Temporal not equal
 *****************************************************************************/

CREATE FUNCTION tNotEqual(h3index, th3index)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Tne_h3index_th3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tNotEqual(th3index, h3index)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Tne_th3index_h3index'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
CREATE FUNCTION tNotEqual(th3index, th3index)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Tne_temporal_temporal'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR #<> (
  PROCEDURE = tNotEqual,
  LEFTARG = h3index, RIGHTARG = th3index,
  COMMUTATOR = #<>
);
CREATE OPERATOR #<> (
  PROCEDURE = tNotEqual,
  LEFTARG = th3index, RIGHTARG = h3index,
  COMMUTATOR = #<>
);
CREATE OPERATOR #<> (
  PROCEDURE = tNotEqual,
  LEFTARG = th3index, RIGHTARG = th3index,
  COMMUTATOR = #<>
);
/*****************************************************************************/
