/* GENERATED by tools/codegen/inherited/generate.py from templates/spatialrels.sql.tmpl — DO NOT EDIT BY HAND;
 * edit the template + tools/codegen/inherited/manifest.d and re-run. */
/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2025, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice
 * and this paragraph and the following two paragraphs appear in all
 * copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY
 * FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
 * INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND
 * ITS DOCUMENTATION, EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 * PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE
 * BRUXELLES HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/*
 * Spatial relationships for temporal cell indices.
 *
 * Each th3index value carries one cell per instant. The spatial
 * relations defined here operate on the cell's BOUNDARY POLYGON (not
 * the cell's centre point), matching the prefilter semantics in
 * `geoToH3IndexSet` / `everIntersectsH3IndexSet_Th3Index` and the user
 * intuition that "the cell occupies its tessellation footprint".
 *
 * Implementation: each function delegates to the tgeometry spatial-rel
 * via `cellToBoundary(th3index) :: tgeometry`. The cell boundary
 * is generated by the libh3 `cellToBoundary` routine and serialised as
 * a tgeography polygon-per-instant; the cast to tgeometry strips the
 * geodetic flag while preserving the coordinates (SRID 4326). Inputs
 * not in SRID 4326 should be transformed beforehand.
 *
 * For SRID-4326 inputs the SQL composition is exact under the cell-
 * boundary semantics that underpin H3's hexagonal tessellation; no
 * cell-centre approximation. Spark / DuckDB consumers that previously
 * had to construct these predicates manually via the prefilter pattern
 * (`geoToH3IndexSet(geom, res) && trip_h3`) can now write the natural
 * `WHERE eIntersects(region.geom, trips.trip_h3)` form.
 */

/*****************************************************************************
 * Ever/always contains
 *****************************************************************************/

CREATE FUNCTION eContains(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eContains($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aContains(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aContains($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

CREATE FUNCTION eContains(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eContains(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aContains(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aContains(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eContains(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eContains(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                          @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aContains(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aContains(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                          @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always covers
 *****************************************************************************/

CREATE FUNCTION eCovers(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eCovers($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aCovers(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aCovers($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

CREATE FUNCTION eCovers(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eCovers(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aCovers(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aCovers(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eCovers(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eCovers(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                        @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aCovers(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aCovers(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                        @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always disjoint
 *****************************************************************************/

CREATE FUNCTION eDisjoint(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aDisjoint(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

CREATE FUNCTION eDisjoint(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aDisjoint(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eDisjoint(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                          @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aDisjoint(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                          @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always intersects
 *****************************************************************************/

CREATE FUNCTION eIntersects(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aIntersects(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

CREATE FUNCTION eIntersects(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aIntersects(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eIntersects(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                            @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aIntersects(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                            @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always touches
 *****************************************************************************/

CREATE FUNCTION eTouches(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eTouches($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aTouches(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aTouches($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

CREATE FUNCTION eTouches(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eTouches(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aTouches(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aTouches(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eTouches(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eTouches(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                         @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION aTouches(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aTouches(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                         @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always dwithin
 *****************************************************************************/

CREATE FUNCTION eDwithin(geometry, th3index, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry, $3) $$;
CREATE FUNCTION aDwithin(geometry, th3index, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry, $3) $$;

CREATE FUNCTION eDwithin(th3index, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2, $3) $$;
CREATE FUNCTION aDwithin(th3index, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2, $3) $$;

CREATE FUNCTION eDwithin(th3index, th3index, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                         @extschema@.cellToBoundary($2)::@extschema@.tgeometry, $3) $$;
CREATE FUNCTION aDwithin(th3index, th3index, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                         @extschema@.cellToBoundary($2)::@extschema@.tgeometry, $3) $$;

/*****************************************************************************/
