/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice
 * and this paragraph and the following two paragraphs appear in all
 * copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY
 * FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
 * INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND
 * ITS DOCUMENTATION, EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 * PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE
 * BRUXELLES HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/*
 * 290_th3index_spatialrels.in.sql
 *
 * Spatial relationships for temporal H3 cell indices.
 *
 * Each th3index value carries one H3 cell per instant. The spatial
 * relations defined here operate on the cell's BOUNDARY POLYGON (not
 * the cell's centre point), matching the prefilter semantics in
 * `geoToH3IndexSet` / `everIntersectsH3IndexSet_Th3Index` and the user
 * intuition that "the cell occupies its tessellation footprint".
 *
 * Implementation: each function delegates to the tgeometry spatial-rel
 * via `h3_cell_to_boundary(th3index) :: tgeometry`. The cell boundary
 * is generated by the libh3 `cellToBoundary` routine and serialised as
 * a tgeography polygon-per-instant; the cast to tgeometry strips the
 * geodetic flag while preserving the coordinates (SRID 4326). Inputs
 * not in SRID 4326 should be transformed beforehand.
 *
 * For SRID-4326 inputs the SQL composition is exact under the cell-
 * boundary semantics that underpin H3's hexagonal tessellation; no
 * cell-centre approximation. Spark / DuckDB consumers that previously
 * had to construct these predicates manually via the prefilter pattern
 * (`geoToH3IndexSet(geom, res) && trip_h3`) can now write the natural
 * `WHERE eIntersects(region.geom, trips.trip_h3)` form.
 */

/*****************************************************************************
 * Ever/always contains
 *****************************************************************************/

CREATE FUNCTION eContains(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eContains($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aContains(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aContains($1, h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION eContains(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eContains(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aContains(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aContains(h3_cell_to_boundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eContains(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eContains(h3_cell_to_boundary($1)::tgeometry,
                          h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aContains(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aContains(h3_cell_to_boundary($1)::tgeometry,
                          h3_cell_to_boundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always covers
 *****************************************************************************/

CREATE FUNCTION eCovers(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eCovers($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aCovers(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aCovers($1, h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION eCovers(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eCovers(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aCovers(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aCovers(h3_cell_to_boundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eCovers(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eCovers(h3_cell_to_boundary($1)::tgeometry,
                        h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aCovers(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aCovers(h3_cell_to_boundary($1)::tgeometry,
                        h3_cell_to_boundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always disjoint
 *****************************************************************************/

CREATE FUNCTION eDisjoint(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDisjoint($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aDisjoint(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDisjoint($1, h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION eDisjoint(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDisjoint(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aDisjoint(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDisjoint(h3_cell_to_boundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eDisjoint(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDisjoint(h3_cell_to_boundary($1)::tgeometry,
                          h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aDisjoint(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDisjoint(h3_cell_to_boundary($1)::tgeometry,
                          h3_cell_to_boundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always intersects
 *****************************************************************************/

CREATE FUNCTION eIntersects(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eIntersects($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aIntersects(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aIntersects($1, h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION eIntersects(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eIntersects(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aIntersects(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aIntersects(h3_cell_to_boundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eIntersects(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eIntersects(h3_cell_to_boundary($1)::tgeometry,
                            h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aIntersects(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aIntersects(h3_cell_to_boundary($1)::tgeometry,
                            h3_cell_to_boundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always touches
 *****************************************************************************/

CREATE FUNCTION eTouches(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eTouches($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aTouches(geometry, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aTouches($1, h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION eTouches(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eTouches(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aTouches(th3index, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aTouches(h3_cell_to_boundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eTouches(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eTouches(h3_cell_to_boundary($1)::tgeometry,
                         h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION aTouches(th3index, th3index)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aTouches(h3_cell_to_boundary($1)::tgeometry,
                         h3_cell_to_boundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always dwithin
 *****************************************************************************/

CREATE FUNCTION eDwithin(geometry, th3index, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDwithin($1, h3_cell_to_boundary($2)::tgeometry, $3) $$;
CREATE FUNCTION aDwithin(geometry, th3index, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDwithin($1, h3_cell_to_boundary($2)::tgeometry, $3) $$;

CREATE FUNCTION eDwithin(th3index, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDwithin(h3_cell_to_boundary($1)::tgeometry, $2, $3) $$;
CREATE FUNCTION aDwithin(th3index, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDwithin(h3_cell_to_boundary($1)::tgeometry, $2, $3) $$;

CREATE FUNCTION eDwithin(th3index, th3index, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDwithin(h3_cell_to_boundary($1)::tgeometry,
                         h3_cell_to_boundary($2)::tgeometry, $3) $$;
CREATE FUNCTION aDwithin(th3index, th3index, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDwithin(h3_cell_to_boundary($1)::tgeometry,
                         h3_cell_to_boundary($2)::tgeometry, $3) $$;

/*****************************************************************************
 * Temporal spatial relationships
 *
 * Each function returns a tbool whose value at instant t is the static
 * spatial relation applied to the cell boundary at t. Composition is
 * the same as the ever/always above: cast the cell boundary to
 * tgeometry and delegate to tgeometry's temporal spatial-rel kernel.
 *****************************************************************************/

CREATE FUNCTION tContains(geometry, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tContains($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION tContains(th3index, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tContains(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tContains(th3index, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tContains(h3_cell_to_boundary($1)::tgeometry,
                          h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION tCovers(geometry, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tCovers($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION tCovers(th3index, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tCovers(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tCovers(th3index, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tCovers(h3_cell_to_boundary($1)::tgeometry,
                        h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION tDisjoint(geometry, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDisjoint($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION tDisjoint(th3index, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDisjoint(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tDisjoint(th3index, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDisjoint(h3_cell_to_boundary($1)::tgeometry,
                          h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION tIntersects(geometry, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tIntersects($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION tIntersects(th3index, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tIntersects(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tIntersects(th3index, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tIntersects(h3_cell_to_boundary($1)::tgeometry,
                            h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION tTouches(geometry, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tTouches($1, h3_cell_to_boundary($2)::tgeometry) $$;
CREATE FUNCTION tTouches(th3index, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tTouches(h3_cell_to_boundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tTouches(th3index, th3index)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tTouches(h3_cell_to_boundary($1)::tgeometry,
                         h3_cell_to_boundary($2)::tgeometry) $$;

CREATE FUNCTION tDwithin(geometry, th3index, dist float)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDwithin($1, h3_cell_to_boundary($2)::tgeometry, $3) $$;
CREATE FUNCTION tDwithin(th3index, geometry, dist float)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDwithin(h3_cell_to_boundary($1)::tgeometry, $2, $3) $$;
CREATE FUNCTION tDwithin(th3index, th3index, dist float)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDwithin(h3_cell_to_boundary($1)::tgeometry,
                         h3_cell_to_boundary($2)::tgeometry, $3) $$;

/*****************************************************************************/
