/* GENERATED by scripts/inherited/generate.py from templates/spatialrels.sql.tmpl — DO NOT EDIT BY HAND;
 * edit the template + scripts/inherited/manifest.yaml and re-run. */
/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice
 * and this paragraph and the following two paragraphs appear in all
 * copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY
 * FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
 * INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND
 * ITS DOCUMENTATION, EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 * PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE
 * BRUXELLES HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/*
 * 290_th3index_spatialrels.in.sql
 *
 * Spatial relationships for temporal cell indices.
 *
 * Each tquadbin value carries one cell per instant. The spatial
 * relations defined here operate on the cell's BOUNDARY POLYGON (not
 * the cell's centre point), matching the prefilter semantics in
 * `geoToH3IndexSet` / `everIntersectsH3IndexSet_Th3Index` and the user
 * intuition that "the cell occupies its tessellation footprint".
 *
 * Implementation: each function delegates to the tgeometry spatial-rel
 * via `tquadbinCellToBoundary(tquadbin) :: tgeometry`. The cell boundary
 * is generated by the libh3 `cellToBoundary` routine and serialised as
 * a tgeography polygon-per-instant; the cast to tgeometry strips the
 * geodetic flag while preserving the coordinates (SRID 4326). Inputs
 * not in SRID 4326 should be transformed beforehand.
 *
 * For SRID-4326 inputs the SQL composition is exact under the cell-
 * boundary semantics that underpin H3's hexagonal tessellation; no
 * cell-centre approximation. Spark / DuckDB consumers that previously
 * had to construct these predicates manually via the prefilter pattern
 * (`geoToH3IndexSet(geom, res) && trip_h3`) can now write the natural
 * `WHERE eIntersects(region.geom, trips.trip_h3)` form.
 */

/*****************************************************************************
 * Ever/always contains
 *****************************************************************************/

CREATE FUNCTION eContains(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eContains($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aContains(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aContains($1, tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION eContains(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eContains(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aContains(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aContains(tquadbinCellToBoundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eContains(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eContains(tquadbinCellToBoundary($1)::tgeometry,
                          tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aContains(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aContains(tquadbinCellToBoundary($1)::tgeometry,
                          tquadbinCellToBoundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always covers
 *****************************************************************************/

CREATE FUNCTION eCovers(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eCovers($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aCovers(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aCovers($1, tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION eCovers(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eCovers(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aCovers(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aCovers(tquadbinCellToBoundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eCovers(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eCovers(tquadbinCellToBoundary($1)::tgeometry,
                        tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aCovers(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aCovers(tquadbinCellToBoundary($1)::tgeometry,
                        tquadbinCellToBoundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always disjoint
 *****************************************************************************/

CREATE FUNCTION eDisjoint(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDisjoint($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aDisjoint(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDisjoint($1, tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION eDisjoint(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDisjoint(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aDisjoint(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDisjoint(tquadbinCellToBoundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eDisjoint(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDisjoint(tquadbinCellToBoundary($1)::tgeometry,
                          tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aDisjoint(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDisjoint(tquadbinCellToBoundary($1)::tgeometry,
                          tquadbinCellToBoundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always intersects
 *****************************************************************************/

CREATE FUNCTION eIntersects(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eIntersects($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aIntersects(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aIntersects($1, tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION eIntersects(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eIntersects(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aIntersects(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aIntersects(tquadbinCellToBoundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eIntersects(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eIntersects(tquadbinCellToBoundary($1)::tgeometry,
                            tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aIntersects(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aIntersects(tquadbinCellToBoundary($1)::tgeometry,
                            tquadbinCellToBoundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always touches
 *****************************************************************************/

CREATE FUNCTION eTouches(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eTouches($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aTouches(geometry, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aTouches($1, tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION eTouches(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eTouches(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION aTouches(tquadbin, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aTouches(tquadbinCellToBoundary($1)::tgeometry, $2) $$;

CREATE FUNCTION eTouches(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eTouches(tquadbinCellToBoundary($1)::tgeometry,
                         tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION aTouches(tquadbin, tquadbin)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aTouches(tquadbinCellToBoundary($1)::tgeometry,
                         tquadbinCellToBoundary($2)::tgeometry) $$;

/*****************************************************************************
 * Ever/always dwithin
 *****************************************************************************/

CREATE FUNCTION eDwithin(geometry, tquadbin, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDwithin($1, tquadbinCellToBoundary($2)::tgeometry, $3) $$;
CREATE FUNCTION aDwithin(geometry, tquadbin, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDwithin($1, tquadbinCellToBoundary($2)::tgeometry, $3) $$;

CREATE FUNCTION eDwithin(tquadbin, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDwithin(tquadbinCellToBoundary($1)::tgeometry, $2, $3) $$;
CREATE FUNCTION aDwithin(tquadbin, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDwithin(tquadbinCellToBoundary($1)::tgeometry, $2, $3) $$;

CREATE FUNCTION eDwithin(tquadbin, tquadbin, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT eDwithin(tquadbinCellToBoundary($1)::tgeometry,
                         tquadbinCellToBoundary($2)::tgeometry, $3) $$;
CREATE FUNCTION aDwithin(tquadbin, tquadbin, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT aDwithin(tquadbinCellToBoundary($1)::tgeometry,
                         tquadbinCellToBoundary($2)::tgeometry, $3) $$;

/*****************************************************************************
 * Temporal spatial relationships
 *
 * Each function returns a tbool whose value at instant t is the static
 * spatial relation applied to the cell boundary at t. Composition is
 * the same as the ever/always above: cast the cell boundary to
 * tgeometry and delegate to tgeometry's temporal spatial-rel kernel.
 *****************************************************************************/

CREATE FUNCTION tContains(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tContains($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION tContains(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tContains(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tContains(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tContains(tquadbinCellToBoundary($1)::tgeometry,
                          tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION tCovers(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tCovers($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION tCovers(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tCovers(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tCovers(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tCovers(tquadbinCellToBoundary($1)::tgeometry,
                        tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION tDisjoint(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDisjoint($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION tDisjoint(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDisjoint(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tDisjoint(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDisjoint(tquadbinCellToBoundary($1)::tgeometry,
                          tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION tIntersects(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tIntersects($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION tIntersects(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tIntersects(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tIntersects(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tIntersects(tquadbinCellToBoundary($1)::tgeometry,
                            tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION tTouches(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tTouches($1, tquadbinCellToBoundary($2)::tgeometry) $$;
CREATE FUNCTION tTouches(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tTouches(tquadbinCellToBoundary($1)::tgeometry, $2) $$;
CREATE FUNCTION tTouches(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tTouches(tquadbinCellToBoundary($1)::tgeometry,
                         tquadbinCellToBoundary($2)::tgeometry) $$;

CREATE FUNCTION tDwithin(geometry, tquadbin, dist float)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDwithin($1, tquadbinCellToBoundary($2)::tgeometry, $3) $$;
CREATE FUNCTION tDwithin(tquadbin, geometry, dist float)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDwithin(tquadbinCellToBoundary($1)::tgeometry, $2, $3) $$;
CREATE FUNCTION tDwithin(tquadbin, tquadbin, dist float)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT tDwithin(tquadbinCellToBoundary($1)::tgeometry,
                         tquadbinCellToBoundary($2)::tgeometry, $3) $$;

/*****************************************************************************/
