/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/* GENERATED by tools/codegen/inherited/generate.py from templates/tempspatialrels.sql.tmpl — DO NOT EDIT BY HAND;
 * edit the template + tools/codegen/inherited/manifest.d and re-run. */

/**
 * @file
 * @brief Temporal spatial relationships for temporal QUADBIN cells
 * @details Each function returns a tbool whose value at an instant is the
 * static spatial relationship applied to the cell boundary at that instant: it
 * casts the cell boundary to tgeometry and delegates to the temporal spatial
 * relationship of the temporal geometry.
 */

/*****************************************************************************
 * tContains
 *****************************************************************************/

CREATE FUNCTION tContains(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tContains($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION tContains(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tContains(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION tContains(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tContains(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                          @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * tCovers
 *****************************************************************************/

CREATE FUNCTION tCovers(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tCovers($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION tCovers(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tCovers(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION tCovers(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tCovers(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                        @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * tDisjoint
 *****************************************************************************/

CREATE FUNCTION tDisjoint(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tDisjoint($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION tDisjoint(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tDisjoint(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION tDisjoint(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tDisjoint(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                          @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * tIntersects
 *****************************************************************************/

CREATE FUNCTION tIntersects(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tIntersects($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION tIntersects(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tIntersects(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION tIntersects(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tIntersects(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                            @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * tTouches
 *****************************************************************************/

CREATE FUNCTION tTouches(geometry, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tTouches($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;
CREATE FUNCTION tTouches(tquadbin, geometry)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tTouches(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION tTouches(tquadbin, tquadbin)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tTouches(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                         @extschema@.cellToBoundary($2)::@extschema@.tgeometry) $$;

/*****************************************************************************
 * tDwithin
 *****************************************************************************/

CREATE FUNCTION tDwithin(geometry, tquadbin, dist float)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tDwithin($1, @extschema@.cellToBoundary($2)::@extschema@.tgeometry, $3) $$;
CREATE FUNCTION tDwithin(tquadbin, geometry, dist float)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tDwithin(@extschema@.cellToBoundary($1)::@extschema@.tgeometry, $2, $3) $$;
CREATE FUNCTION tDwithin(tquadbin, tquadbin, dist float)
  RETURNS tbool
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.tDwithin(@extschema@.cellToBoundary($1)::@extschema@.tgeometry,
                         @extschema@.cellToBoundary($2)::@extschema@.tgeometry, $3) $$;
