/* GENERATED by tools/codegen/inherited/generate.py from templates/spatialrels.sql.tmpl — DO NOT EDIT BY HAND;
 * edit the template + tools/codegen/inherited/manifest.d and re-run. */
/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice
 * and this paragraph and the following two paragraphs appear in all
 * copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY
 * FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
 * INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND
 * ITS DOCUMENTATION, EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 * PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE
 * BRUXELLES HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/*
 * Ever/always spatial relationships for temporal network points.
 *
 * A temporal network point (tnpoint) is defined over the road/rail
 * network's position space (route identifier + fractional position
 * along the route), not over free geographical space. Each function
 * converts its network-point operand(s) to a temporal geometry point
 * via the standard tnpoint::tgeompoint cast (the point resolved along
 * its route) and then to tgeometry, and delegates to the tgeometry
 * ever/always spatial relationship.
 *
 * Two temporal network points whose routes belong to different
 * networks, or to different connected components of the same
 * network, cannot be related through network distance; the free-space
 * relationship computed here is still well defined and is the
 * documented behaviour for that case.
 */

/*****************************************************************************
 * Ever/always contains
 *****************************************************************************/

CREATE FUNCTION eContains(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eContains($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aContains(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aContains($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

CREATE FUNCTION eContains(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eContains($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aContains(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aContains($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eContains(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eContains($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                          $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aContains(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aContains($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                          $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always covers
 *****************************************************************************/

CREATE FUNCTION eCovers(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eCovers($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aCovers(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aCovers($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

CREATE FUNCTION eCovers(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eCovers($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aCovers(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aCovers($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eCovers(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eCovers($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                        $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aCovers(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aCovers($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                        $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always disjoint
 *****************************************************************************/

CREATE FUNCTION eDisjoint(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aDisjoint(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

CREATE FUNCTION eDisjoint(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aDisjoint(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eDisjoint(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDisjoint($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                          $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aDisjoint(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDisjoint($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                          $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always intersects
 *****************************************************************************/

CREATE FUNCTION eIntersects(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aIntersects(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

CREATE FUNCTION eIntersects(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aIntersects(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eIntersects(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eIntersects($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                            $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aIntersects(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aIntersects($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                            $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always touches
 *****************************************************************************/

CREATE FUNCTION eTouches(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eTouches($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aTouches(geometry, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aTouches($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

CREATE FUNCTION eTouches(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eTouches($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;
CREATE FUNCTION aTouches(tnpoint, geometry)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aTouches($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2) $$;

CREATE FUNCTION eTouches(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eTouches($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                         $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;
CREATE FUNCTION aTouches(tnpoint, tnpoint)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aTouches($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                         $2::@extschema@.tgeompoint::@extschema@.tgeometry) $$;

/*****************************************************************************
 * Ever/always dwithin
 *****************************************************************************/

CREATE FUNCTION eDwithin(geometry, tnpoint, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry, $3) $$;
CREATE FUNCTION aDwithin(geometry, tnpoint, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin($1, $2::@extschema@.tgeompoint::@extschema@.tgeometry, $3) $$;

CREATE FUNCTION eDwithin(tnpoint, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2, $3) $$;
CREATE FUNCTION aDwithin(tnpoint, geometry, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin($1::@extschema@.tgeompoint::@extschema@.tgeometry, $2, $3) $$;

CREATE FUNCTION eDwithin(tnpoint, tnpoint, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.eDwithin($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                         $2::@extschema@.tgeompoint::@extschema@.tgeometry, $3) $$;
CREATE FUNCTION aDwithin(tnpoint, tnpoint, dist float)
  RETURNS boolean
  LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE
  AS $$ SELECT @extschema@.aDwithin($1::@extschema@.tgeompoint::@extschema@.tgeometry,
                         $2::@extschema@.tgeompoint::@extschema@.tgeometry, $3) $$;

/*****************************************************************************/
