name: Docker image
on:
  push:
    branches:
      - 'develop'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build & push docker image
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
          psql: [12,13,14,15,16]
          postgis: [3.4]
          os: [ubuntu-latest]

    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Info
        run: echo "Parameters. ${{ github.event.base_ref }}, ${{ github.ref_type }}, ${{ github.ref }}, ${{ github.ref_name }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (develop)
        uses: docker/build-push-action@v5
        if: ${{ github.ref_type == 'branch' }}
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: mobilitydb/mobilitydb:${{ matrix.psql }}-${{ matrix.postgis }}-develop
          build-args: |
            POSTGRES_VERSION=${{ matrix.psql }}
            POSTGIS_VERSION=${{ matrix.postgis }}

      - name: Build and push Docker image (release / tag)
        uses: docker/build-push-action@v5
        if: ${{ github.ref_type == 'tag' }}
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            mobilitydb/mobilitydb:${{ matrix.psql }}-${{ matrix.postgis }}-latest
            mobilitydb/mobilitydb:${{ matrix.psql }}-${{ matrix.postgis }}-${}
          build-args: |
            POSTGRES_VERSION=${{ matrix.psql }}
            POSTGIS_VERSION=${{ matrix.postgis }}
