name: Build for windows using msys2
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain

      - name: Install dependencies
        run: |
          pacman -S mingw-w64-x86_64-cmake
          pacman -S mingw-w64-x86_64-postgresql
          pacman -S mingw-w64-x86_64-postgis
          pacman -S mingw-w64-x86_64-proj
          pacman -S mingw-w64-x86_64-geos
          pacman -S mingw-w64-x86_64-json-c
          pacman -S mingw-w64-x86_64-gsl
          pacman -S mingw-w64-i686-xz
          xzcat --version

      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh